- content/learn/book/getting-started/setup/_index.md
Update documentation to reflect the Windows cargo config uses the Rust bundled rust-lld.
Add mention of `cargo +nightly ...`.
Complement to [this PR](https://github.com/bevyengine/bevy/pull/150).
> Update "Enable Fast Compiles" to reflect Windows doesn't require installing lld.

- config.toml
- templates/base.html
The current RSS feed configuration is broken as of the latest Zola version. See commits for details.
> Fix Atom feed

- content/news/2020-08-10-introducing-bevy/index.md
Add default plugins so `movement` system runs repeatedly.
`add_default_plugins()` was already introduced earlier, so it's not a new concept.  Without it, the `movement` system runs only once, which makes it hard to see the difference between `add_startup_system` and `add_system`.
If the extra line is still deemed too much or distracting, I'm happy to just close the pull request.
> Improve Ergonomics Example

- templates/learn.html
This adds a link to the [Awesome Bevy](https://github.com/bevyengine/awesome-bevy) repo, under Bevy Rust API Docs, in Learn.
Feel free to replace the card description with something else, currently it's:
> Learn by example with an awesome-style list of cool Bevy projects.
> Add link to the awesome-bevy repo in Learn

- content/learn/book/getting-started/_index.md
Not a big deal, but when you double click to copy the command and paste in your terminal, a bit of whitespace comes with it.
> Remove whitespace from getting started command

- .github/workflows/main.yml
I noticed in https://github.com/bevyengine/bevy-website/pull/23 that the CI (luckily) failed to deploy the changed website to production.
Thrashing the web site with deployments from every commit of every pull request is _probably_ not what was intended, so this change makes it so that pull requests only attempt to _build_ the web site.  Later, when the pul request is merged to master then it will build _and_ deploy the web site.  Pushes straight to master will also build and deploy.
> Only 'build' for pull requests. Build AND deploy for pushes (merges) to master.

- content/learn/book/getting-started/setup/_index.md
It was changed to use rust-lld instead, but it doesn't specify that you need to install cargo-binutils, as rust-lld is not shipped by default for most platforms. Cargo-binutils adds rust-lld, and llvm-tools-preview adds the actual lld executable to your toolchain.
> Change windows to include using binutils

- content/news/2020-09-19-bevy-0.2/index.md
Point to the new location as of this commit:
https://github.com/mrk-its/bevy-robbo/commit/948587440919c9d05ababa488623d6c5e1f5785a
> Fix broken link to Wasm javascript function

- templates/base.html
Previously they defaulted to the "Features" message.
> Fix header-message in news and book sections

- sass/_book-nav.scss
- sass/_headerbar.scss
- sass/_variables.scss
- sass/site.scss
- templates/base.html
- templates/book-section.html
Here's my solution to fix the book navigation not being visible on mobile. Basically what my changes do is if the url path starts with `/learn/book` it replaces the bevy mobile logo with bars to toggle the nav. When the bars are pressed or clicked the book-nav will slide in. Currently I've coded it so that the book-content will slide to the right when the book-nav is open, but if you'd prefer another solution, for example, maybe the book-nav should cover the content instead of it sliding to the right, just let me know. I can change the code to do that.
Closes #37
> Added book nav toggle for mobile

- content/news/2020-11-03-bevy-0.3/index.md
Both myself and a HN reader independently were confused by this section. This change removes that confusion at the point where they are most likely to solidify their mental model of what they're reading.
> Disambiguate scale of get component

- content/learn/book/getting-started/_index.md
- content/learn/book/getting-started/setup/_index.md
Since the example code in the book uses features new in Bevy 0.3 (plugin groups), I updated the cargo snippets to 0.3 to make it easier for new users.
> Update the bevy version number in the cargo snippets

- content/learn/book/getting-started/setup/_index.md
When setting up a project for the first time, I found it confusing that the guide says to put the config in `.cargo/config`, while a comment in the [recommended config][1] says to put it in `.cargo/config.toml`. Apparently, `cargo` will look for the config in both places, but the [cargo documentation][2] recommends the path with the `.toml` extension included.
[1]: https://github.com/bevyengine/bevy/blob/master/.cargo/config_fast_builds
[2]: https://doc.rust-lang.org/cargo/reference/config.html
> getting-started/setup: s/config/config.toml

- content/learn/book/getting-started/_index.md
I agree with [this](https://github.com/bevyengine/bevy/issues/890#issuecomment-730862427) comment, so I added some scary warnings.
> Make using bevy as a git dependency more scary

- sass/_book-nav.scss
Currently the book nav is broken on mobile since the sass variables don't work in a css calc without [sass interpolation](https://sass-lang.com/documentation/interpolation). The pr fixes that.
> Fix variables in css calc

- sass/_book-nav.scss
- sass/_content.scss
- sass/_features.scss
- sass/_headerbar.scss
- sass/_news.scss
Chrome was rendering a "slightly too small" version of the font, which appeared "vertically crunched". Scaling up slightly makes it render as it does in firefox (which is what I wanted it to look like).
> fix font size (yes this matters)

- content/learn/book/getting-started/setup/_index.md
This is a dependency as per: https://github.com/bevyengine/bevy/issues/939
> Add Visual Studio 2019 build tools as windows

- content/learn/book/getting-started/setup/_index.md
Enabling Bevy's Dynamic Linking Feature fails if Bevy isn't in Cargo.toml which might throw beginners off, so let's re-organise it like this to help those.
> Tell people to add Bevy to their Cargo.toml before suggesting Fast Compiles

- content/learn/book/contributing/code/_index.md
Quick fix for the broken link. Not sure why the diff destroys and recreates line 31, sorry.
> Fixed link to bevy engine github on contributing code page

- content/learn/book/next-steps/_index.md
This changes the link
from https://github.com/bevyengine/bevy/tree/master/examples
to https://github.com/bevyengine/bevy/tree/master/examples#examples
so that the user sees the warning about differences in master and previous release examples immediately instead of being hidden beyond the scroll. An alternative would be to make the link point to 0.3, but this avoids letting the url become outdated.
> Change examples url

- templates/header-macros.html
Noticed that the active items on the navbar weren't getting highlighted (except `Features`), this PR fixes that.
The change,
- Concatenating a `/` to the `name` variable so that the `starting_with` comparison passes for valid items
> Highlight navbar items when active

- content/news/2020-08-10-introducing-bevy/index.md
- templates/shortcodes/rust_type.html
While I had the 0.1 announcement post open, I noticed that the (very cool) doc links were broken.
Fixing these seems like a no-brainer, as there's a nice orange "go to latest version" link at the top of docs.rs.
I thought it was probably okay to fix the links into the bevy git repo as well.
Testing the waters with this, and if you're into it there's some more `{{rust_type}}` in the 0.4 blog post that could be future-proofed as well as a few bevy master links in the 0.3 and 0.2 posts that I wouldn't mind fixing up.
There's no tag on the repo for 0.1 so I linked to the commit that adds the 0.1 news link to the readme.
> Fix broken docs and bevy git links in 0.1 news post

- content/news/2020-09-19-bevy-0.2/index.md
- content/news/2020-11-03-bevy-0.3/index.md
- content/news/2020-12-19-bevy-0.4/index.md
- templates/shortcodes/rust_mod.html
I don't think any of these were actually broken (yet) but it seems like a good bet that they will break at some point in the future.
> Future-proof github and docs links in 0.2, 0.3 and 0.4 announcement posts

- content/learn/book/getting-started/_index.md
Saw a few commits switching over to main but I think we missed two occurrences in the bevy book.
> Link to main branch in bevy book > getting started

- content/learn/book/contributing/code/_index.md
I was mindlessly following instructions and discovered this was missing. I didn't add --all-features because I got a linker crash on execution: `note: LINK : fatal error LNK1189: library limit of 65535 objects exceeded`.
> Add `cargo test` to contributing code

- templates/community.html
Add an "awesome-bevy" card to the "community" page.
I didn't know what logo to use, so I reused the github logo. I think it is a little ugly to have this duplication, so I hope we can come up with something else. Another suggestion: perhaps use the Bevy logo?
This should address #2 .
> Community: feature awesome-bevy

- content/learn/book/introduction/_index.md
- content/learn/book/next-steps/_index.md
- templates/learn.html
There are 2 changes to the Official Bevy Book that I want to make with this PR:
I want people reading the official book to know where they can find community-made projects (awesome-bevy), and specifically to know about the existence of unofficial / community-made learning resources. (this is why I also added a separate link to the learning section of awesome-bevy)
I don't want people coming to the book to be discouraged by thinking that what's covered in the book is all there is.
I want to prominently direct them to also check out other resources early on, in the introduction, to manage expectations and make the book more useful.
> Book: improve discoverability of additional learning resources

- templates/shortcodes/rust_mod.html
- templates/shortcodes/rust_type.html
When clicking on any documentation that is not `std` in the book, you get `The requested version does not exist.`
This is because docs.rs changed their url scheme from ```https://docs.rs/std/<crate>``` to  ```https://docs.rs/latest/<crate>``` in order to obtain the docs for the newest version.
> fix broken docs.rs links

- content/learn/book/getting-started/_index.md
- content/learn/book/next-steps/_index.md
- templates/learn.html
1. Change all links to point to the `latest` branch (which is the release version, not `main`)
2. Explicitly instruct users to `git checkout` the correct version when they clone the repo to run the examples
- I suspect this "getting started" book page was a big cause of misdirected/confused new users
- See also: https://github.com/bevyengine/bevy/pull/1624 for a similar change to the README in the main repo
3. Add a card on the `Learn` page linking to the examples
> Help users discover the correct version of the official examples

- content/learn/book/migration-guides/0.4-0.5/_index.md
The previous section talking about `insert` method of `Commands` was written pre-`EntityBuilder` and seemed wrong.
Also, the links to `Commands` and `World` docs were broken.
Here's a very minimal section about the new Commands API that touches on the most important stuff, probably.
And also a ChangedRes section that I found half-written in my local repo.
> More migration guide

- content/news/_index.md
- sass/_base.scss
- templates/anchor-link.html
Fixes #125 by inserting a link via [Zola's anchor insertion](https://www.getzola.org/documentation/content/linking/#anchor-insertion). 
Screenshot:
> Add anchor links to headers in the news section

- content/news/2021-04-06-bevy-0.5/index.md
The new World Metadata collections must be references to work inside systems.
https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/src/system/system_param.rs#L890
https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/src/system/system_param.rs#L922
https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/src/system/system_param.rs#L954
https://github.com/bevyengine/bevy/blob/main/crates/bevy_ecs/src/system/system_param.rs#L986
> World Metadata in systems must be references

- templates/shortcodes/file_code_block.html
Adds the ability to embed external files as code blocks in markdown text. This opens up the doors to validating these files using other tooling (such as `cargo build` for rust).
The syntax is:
```
{{file_code_block(path="templates/base.html" lang="html")}}
```
More context in #143
> external file code block: initial implementation

- content/learn/book/migration-guides/0.4-0.5/_index.md
A small fix to documentation. (The migration guide mentions `changed()` which actually is `is_changed()` )
> Small fix to migration guide 0.4-0.5, where changed() is mentioned but should be is_changed()

- content/learn/book/getting-started/setup/_index.md
The "veryrealemail.com" domain is actually owned by some individual (check the whois record). 
The [IANA has some reserved domains](https://www.iana.org/domains/reserved) for this purpose: example.com and example.org. Alternatively [RFC2606](https://datatracker.ietf.org/doc/html/rfc2606) also specifies an illustrative TLD, *.example*, that could also be appropriate: i.e. you@veryrealemail.example
> Use example.com for illustrative email addresses

- content/learn/book/getting-started/setup/_index.md
Using a ```rust-toolchain``` file is much simpler to set up, compared to manual rustup overrides. Also, using the ```rust-toolchain``` file allows other people that download a repository to get going immediately without any manual configuration of their local toolchain.
Finally, in my opinion the toolchain version should be checked into source control anyway, since a codebase written with the nightly compiler in mind may not compile on stable rust. This makes the toolchain basically a build-dependency, and we obviously value checking in other build-dependencies via ```Cargo.toml```.
> Recommend using the Rustup toolchain-file for nightly rust

- content/learn/book/getting-started/_index.md
Cargo looks for a "master" branch, but bevy changed it's convention to "main" causing the following error:
```
error: failed to get `bevy` as a dependency of package `xxx`
Caused by:
failed to load source for dependency `bevy`
Caused by:
Unable to update https://github.com/bevyengine/bevy
Caused by:
failed to find branch `master`
Caused by:
cannot locate remote-tracking branch 'origin/master'; class=Reference (4); code=NotFound (-3)
```
This change suggested by @mockersf fixes that.
> Fix dependency error

- .github/workflows/deploy.yml
This should stop the deploy action from running on forks where it fails
> only run deploy action if repo is owned by bevyengine

- content/learn/book/getting-started/_index.md
Support was added as of 1.53.0, I believe this is no longer needed.
https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html#head-branch-name-support-in-cargo
Closes #171
> removed explicit branch="main" in dependencies

- content/learn/book/getting-started/setup/_index.md
The authors field is no longer included in Cargo.toml for new projects from Cargo 1.53 so it is removed from the setup guide.
"https://bevyengine.org/learn/book/getting-started/setup/"
> Remove author section in Cargo.toml in _index.md

- config.toml
- sass/site.scss
- move the config option to the correct section
- fix the background color
> fix code highlighting after zola 0.14

- sass/_headerbar.scss
The logo currently fills up too much vertical space on the navbar. This PR shrinks it and the `header-message` by 25% to provide more vertical negative space.
> Add more vertical negative space to navbar logo

- content/learn/book/getting-started/setup/_index.md
This is pretty simple, but all other files had extensions, so I think it's better to keep consistency.
> Add extension to rust-toolchain filename

- .github/workflows/deploy.yml
- generate-wasm-examples/generate_wasm_examples.sh
added to the deploy workflow
since https://github.com/bevyengine/bevy/pull/3421 I also added an audio example
> Actually build and deploy wasm examples page

- generate-wasm-examples/generate_wasm_examples.sh
This bug is fixed in wgpu, workaround is no longer needed
To merge after https://github.com/bevyengine/bevy/pull/3489
(also, next rebuild will have 3d examples working as bug in naga has been fixed and a patch has been released)
> do not remove msaa from examples

- content/learn/book/migration-guides/0.5-0.6/_index.md
This PR starts a new Migration guide, with the following changes:
1. bevyengine/bevy#2531
2. Optional `.system()` from bevyengine/bevy#2398, bevyengine/bevy#2403, bevyengine/bevy#2422 and bevyengine/bevy#2431,
3. bevyengine/bevy#2793
4. bevyengine/bevy#1778
5. bevyengine/bevy#2605
6. bevyengine/bevy#2283
7. bevyengine/bevy#2254
8. bevyengine/bevy#1781
Ignored Changes:
1. bevyengine/bevy#1959: Changes might be obsoleted/lumped in with the render rework
2. bevyengine/bevy#2623: The PR has the `S-Needs-Migration-Guide` Label, but the feature was already broken in `0.5` and originally fixed in bevyengine/bevy#2024
3. bevyengine/bevy#2606: The change is small and the old `.add_plugin(bevy::app::ScheduleRunnerPlugin {})` syntax still compiles in `0.6`.
I started this, before noticing that #134 …
> Start 0.5 -> 0.6 Migration guide

- content/learn/book/migration-guides/0.5-0.6/_index.md
Link was pointing at bevy_ecs::query::QuerySet (which doesn't exist) rather than bevy_ecs::query::QueryState.
> 0.5-0.6 migration guide link correction

- content/learn/book/getting-started/ecs/_index.md
- content/learn/book/getting-started/plugins/_index.md
- content/learn/book/getting-started/resources/_index.md
> Remove references to AppBuilder in 0.6

- content/news/2022-01-08-bevy-0.6/index.md
Use `combinations` for consistency. See also [the discussion on wording](https://github.com/bevyengine/bevy/pull/1763#issuecomment-808781977).
Resolves this [reddit complaint](https://www.reddit.com/r/rust/comments/rz612l/comment/hru3tkk/?utm_source=reddit&utm_medium=web2x&context=3)
> permutations -> combinations

- content/learn/book/migration-guides/0.5-0.6/_index.md
The transition to Rust 2021 is easily missed from the news announcement, and will lead to confusing errors.
The actual explanation is simply copied from the news article, as it was very well explained there.
> Mention Rust 2021 first in the migration guide

- templates/index.html
Just adding "shadows" to the list of 3d renderer features, and promoting "Web" to a supported platform.
I think it would be great to update the 3d renderer image as well in a way that showcases the new renderer.
> Update main page for bevy 0.6

- content/learn/book/migration-guides/0.5-0.6/_index.md
Let me know if there are any strong opinions about how I laid this out. I thought about showing the "simple examples" and then linking off to `contributors.rs` for the "advanced" stuff, but it seemed a bit harder to dig the relevant info out of that example.
> Add SpriteBundle section to 0.5 -> 0.6 migration guide

- content/learn/book/migration-guides/0.5-0.6/_index.md
This adds a note on the changes with Visibility. I'm open to suggestions on the is_transparent text
> Add Visible -> Visibility to migration guide

- content/learn/book/getting-started/ecs/_index.md
The `system()` call has been removed from the paragraph explaining it, but the whole sentence does not make sense anymore with `v0.6`.
> Remove outdated paragraph (v0.6 fix)

- content/news/2022-01-08-bevy-0.6/index.md
The newspost said it was super-exponential, but simple analysis shows that it should only be exponential.
The number of combinations is exponential at the size of the combination, so unless visiting each combination is super-exponential - the overall complexity should also be exponential. The bulk logic of visiting each combination is done in [`QueryCombinationIter::fetch_next_aliased_unchecked`](https://github.com/bevyengine/bevy/blob/v0.6.0/crates/bevy_ecs/src/query/iter.rs#L227), which seems polynomial. Not even exponential - definitely not super-exponential.
> Fix complexity description for iter_combinations

- templates/index.html
* `AudioOutput` is an internal, non-send resource; the user-facing resource to play audio on is `Audio`
* We can load multiple audio encodings, so I removed the `mp3` to make it more general
* Stray whitespace that my IDE removes on its own :bowtie:
> Correct audio block on the landing page

- templates/index.html
The current landing page only states MIT and fails to mention Apache 2.0. This PR fixes that.
> Update landing page to reflect relicense

- generate-errors/Cargo.lock
- generate-errors/Cargo.toml
- generate-errors/src/lib.rs
After the readme was added, it started showing up on the website: https://bevyengine.org/learn/errors/#readme
> Skip readme when generating error codes

- content/news/2021-04-06-bevy-0.5/index.md
- content/news/2022-01-08-bevy-0.6/index.md
- content/news/2022-04-15-bevy-0.7/index.md
Recent donate button style changes broke the donate button in blog posts. This aligns it with the new style. Might be worth abstracting this out with templates to avoid needing to keep everything in sync, but thats a problem for another day.
> Fix the donate button in blog posts

- content/news/2023-03-06-bevy-0.10/index.md
0.10 release post is different from previous posts, the author is `Bevy Contributors` instead of `Carter Anderson`. Maybe it's better to use `we're` somewhere.
> I'm -> we're in 0.10 release post

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- templates/book-section.html
We're using the `main` naming convention everywhere else in the Bevy Org. We should use it here too.
> master -> main branch

- content/learn/book/migration-guides/0.9-0.10/_index.md
these were [vetoed ](https://github.com/bevyengine/bevy/pull/7790#issuecomment-1442156182) in the original PR but the migration guide was never updated.
> on_enter and on_exit are not a thing

- content/learn/book/migration-guides/0.9-0.10/_index.md
> Improve 0.9 -> 0.10 scheduling migration advice

- content/news/2021-04-06-bevy-0.5/index.md
- content/news/2022-01-08-bevy-0.6/index.md
- content/news/2022-04-15-bevy-0.7/index.md
- content/news/2022-07-30-bevy-0.8/index.md
- content/news/2022-11-12-bevy-0.9/index.md
- content/news/2023-03-06-bevy-0.10/index.md
Fix broken links.
`learn/book/migration-guides` -> `learn/migration-guides`
> Fix links to migration guides in news posts

- content/learn/migration-guides/0.9-0.10/_index.md
- content/news/2023-03-06-bevy-0.10/index.md
Fixes a missing `Clone` and `Hash` derives in the Bevy 0.10 blog post.
Spotted by user `jengamon` on Discord.
This also fixes a rogue linebreak I noticed in the migration guide while looking at this.
> Fix missing Clone and Hash derives in blog post

- sass/_vars.scss
- sass/components/_header.scss
- sass/components/_logo.scss
- sass/components/_main-menu.scss
- sass/pages/_features.scss
- templates/index.html
- templates/layouts/base.html
- templates/macros/header.html
- Remove "Get Started" from header
- Move it to home page
- Add "Getting Started" entry in mobile menu
- Tweak GitHub link in header:
- Remove weird space to the right
- Make it a tiny bit smaller
- Tweak desktop header menu font-size: make it a tiny bit smaller so it breaths more in "Migration Guide"/"Supporting Bevy" pages
- Revert `tablet-landscape` breakpoint size, so we don't push mobile design to desktop users
https://user-images.githubusercontent.com/188612/225563581-b58f4a24-4699-41ec-9e12-50558a2ec92c.mp4
> Tweak header

- content/learn/book/getting-started/setup/_index.md
This pull request enhances the setup instructions for installing OS dependencies for Windows, located at https://bevyengine.org/learn/book/getting-started/setup/#install-os-dependencies
This fixes the issue I raised here: https://github.com/bevyengine/bevy-website/issues/622
**Operating System**: Windows 10 Pro 64-Bit (10.0, Build 19045)
**Processor**: AMD Ryzen 7 1800X Eight-Core Processor
> Improve setup instructions for Windows

- templates/index.html
Adds a `<link rel="me"` to the site so that the official account can be [verified](https://docs.joinmastodon.org/user/profile/#verification).
> Add mastodon verification to index.html

- content/learn/book/getting-started/setup/_index.md
I tested the dynamic linking on Windows 11 and it works. I also heard from others in the Discord chats that it seems to be a resolved issue. Thus a small PR to update the docs to reflect that.
Here is the relevant discussion with Alice in the General room on Discord where they call out that they believe it is fixed: https://discord.com/channels/691052431525675048/691052431974465548/1103445630237540362
> Removing outdated note about Windows support for dynamic_linking

- static/restart-audio-context.js
- templates/example-webgpu.html
- templates/example.html
- templates/examples-webgpu.html
in browsers, audio doesn't start unless the user interacted with the page first.
This adds the workaround to resume the audio context after an interaction.
Fix taken from https://github.com/bevyengine/bevy_github_ci_template/pull/30
Also, some light cleanup of comments I forgot to remove
> resume audio context in wasm examples

- templates/example-webgpu.html
- templates/examples-webgpu.html
- Link to the `main` branch instead of `latest`.
- Add spacing between the 'Support Warning' text and the example canvas.
- Spelling of 'been'.
> Fixes for the WebGPU pages

- content/learn/book/contributing/docs/_index.md
I'm guessing `{{curly_open()}}` was something that worked in an older version of zola.
Now `{{/*` and `*/}}` can be used to escape `{{` and `}}`.
Fixes #580.
> Fix book contributing doc page

- content/community/_index.md
- content/faq/index.md
- content/learn/index.md
- content/news/_index.md
- content/sponsorship-pledge/_index.md
- generate-wasm-examples/generate_wasm_examples.sh
- templates/assets.html
- templates/layouts/base.html
The titles on some pages are a bit messy. The most heinous being news articles like "Bevy - Bevy 0.10" and "Bevy - Bevy + WebGPU".
This PR favors "direct" section titles in more places and changes the formatting in a couple of other places (ex: "Bevy - Community" is now "Bevy Community") .
> Simpler / clearer titles

- templates/example-webgpu.html
- templates/example.html
Prevent the `fit_canvas_to_parent` setting from growing the canvas by locking the aspect ratio to that of the initial resolution of the bevy `Window`.
Fixes #432.
> Fix example canvas growing on resize

- templates/example-webgpu.html
During startup winit is using an exception as a part of its control flow. This is exception is "normal" and not a error but will end up in the browsers error console like this:
This PR adds a simple exception handler that will silently drop this specific exception and propagate all other exceptions.
> Filter out unavoidable winit control flow exception in WebGPU examples

- content/learn/book/getting-started/ecs/_index.md
This is a very minor change.
I noticed at least two people on the Bevy discord (example, not to shame just to illustrate: https://discord.com/channels/691052431525675048/1111845037035225118) who got confused following the current Book because the example at https://bevyengine.org/learn/book/getting-started/ecs/ doesn't repeat `use bevy::prelude::*`.
Even though the page tells them to add the code to their main.rs file (which, if they followed the book in order should contain the import: https://bevyengine.org/learn/book/getting-started/apps/), it looks like a standalone code because of the `use bevy::app::App` and they just copy-paste it, and it doesn't work.
This can lead to a frustrating first experience, and can easily be fixed by adding the correct import again (which contains `App` …
> Fix import confusion in Learn > Book > Getting Started > ECS

- content/learn/book/contributing/docs/_index.md
- content/learn/book/getting-started/apps/_index.md
- content/learn/migration-guides/0.5-0.6/_index.md
- content/news/2020-08-10-introducing-bevy/index.md
- content/news/2020-12-19-bevy-0.4/index.md
- content/news/2021-04-06-bevy-0.5/index.md
- content/news/2021-08-10-bevys-first-birthday/index.md
- content/news/2022-01-08-bevy-0.6/index.md
- templates/shortcodes/rust_type.html
For a type called `App` that is plural, it should look like this:
> `App`s
and not
> `Apps`
because the latter makes it sound like a singular type named "Apps".
> Properly handle plurals and code blocks

- generate-release/src/github_client.rs
This release cycle we used merge queues instead of Bors. This adapts our release note generator to read that state instead of the bors merge state from the title.
> Adapt release notes generator to use merge state instead of bors

- content/news/2023-07-07-bevy-0.11/index.md
I tried to keep it short but the code block is still a bit big for my liking.
> 0.11 Section: Simpler RenderGraph construction

- content/learn/book/getting-started/setup/_index.md
Provides some clarification on what `cargo-binutils` is doing, and addresses a questions along the lines of "once I've installed the LLD linker, how do I use it?"
> Clarify what the cargo-binutils is doing

- content/news/2023-07-07-bevy-0.11/index.md
Not necessarily the cover image we will roll with, but it is Good Enough(TM) for now.
> 0.11: Whats Next and Cover Image

- sass/components/_image_compare.scss
- sass/site.scss
- static/components.js
- templates/news-page.html
Adds a side-by-side image-compare widget for usage in news posts.
Usage in a document should look as follows
```html
<main>
<div class="image-compare" style="aspect-ratio: 16 / 9" data-title-a="Apples" data-title-b="Oranges">
</div>
</main>
<script type="module">
import { enable_image_compare } from '/components.js';
document.addEventListener("DOMContentLoaded", function() {
enable_image_compare();
});
</script>
```
The `aspect-ratio` should be set to match the aspect ratio of the images, but it will default to 16/9.
---
I tested this on Windows with Firefox, Chrome, & Edge. Additional testing for Safari & others would be appreciated.
> Add image-compare widget

- content/learn/migration-guides/0.10-0.11/_index.md
Following https://github.com/bevyengine/bevy-website/pull/655.
Some PRs didn't have the C-Breaking-Changes label, but had a migration guide in the PR description, those were not added to the Migration Guide.
I found them semi-manually using this: https://discord.com/channels/691052431525675048/692572690833473578/1127412213037150269 , the list is here: https://discord.com/channels/691052431525675048/692572690833473578/1127550222126563399
This PR has a lot of copy/paste, even though I changed a few things, so there might be some errors.
I tried to keep the loose sorting by section order.
https://github.com/bevyengine/bevy/pull/7778 is still missing a migration guide.
https://github.com/bevyengine/bevy/pull/6846 could maybe explain how to get around this (?)
> Add missing breaking change PRs without label to 0.10 -> 0.11 migration guide

- content/news/2023-07-09-bevy-0.11/index.md
A sentence from the news release was corrected from "(aka blendshapes, aka keyshapes, and a slew of other name)." to "(aka blendshapes, aka keyshapes, and a slew of other names)."
> Fix grammar in 0.11 news release  (name -> names)

- content/learn/migration-guides/0.10-0.11/_index.md
I discovered an additional migration pain point related to TypePath when registering structs with generic types to the type registry. See the related issue for details: https://github.com/bevyengine/bevy/issues/9094
This PR adds examples of how to handle this to the migration guide.
> Migration guide for TypePath required for generic types

- content/news/2023-07-09-bevy-0.11/index.md
- sass/components/_image_compare.scss
- static/components.js
- add UI handle & cursor affordances to visually indicate interactivity to end-user,
- add padding fix to image-titles,
- add slight blur-shadow to image-titles to improve readability,
- allow widget-user to override slider configuration.
generally improves code quality
before & after:
> Improve image-compare widget

- templates/examples.html
Add a easy way to access the examples-wgpu page. I always struggle to find it.
Add a link to [examples-wgpu](https://bevyengine.org/examples-webgpu) in the [examples section](https://bevyengine.org/examples/)
> Add link to examples-wgpu in the examples page

- content/learn/migration-guides/0.10-0.11/_index.md
The auto-generated guide for Audio from the original PR is outdated. Seems like Cart changed the code last minute, so the code that is in migration guide is invalid. I guess I am the first one to notice that...
So I changed this:
To this: 
Source (Cart himself): [Link to PR](https://github.com/bevyengine/bevy/pull/8424)
> Migration guide 0.10 -> 0.11 Audio API FIX

- templates/example-webgpu.html
- templates/examples-webgpu.html
WebGPU support has been launched with 0.11, so there is no longer a need to inform people that WebGPU examples are compiled with main branch (even though that's still the case for now).
> Remove outdated notice in WebGPU examples

- content/learn/migration-guides/0.10-0.11/_index.md
Mentions that the new tonemapper requires the `ktx2`, `tonemapping_luts`, and `zstd` features, and recommends `SomewhatBoringDisplayTransform` if for whatever reason you don't want to use those features.
edit: Also explicitly mentions scene turning pink so if people search for that, they will hopefully find it.
> Expand upon the 0.11 tonemapping migration guide

- content/learn/book/getting-started/ecs/_index.md
Hello!
I was following the getting started part of the book and noticed this tiny error. The greet_people system was missing its underscore leading to an error, and I thought I'd pop in and offer a fix.
Thanks for a great guide so far!
> Fix typo in getting-started/ecs

- generate-assets/src/lib.rs
Following https://github.com/bevyengine/bevy-website/pull/648
- Move `parse_assets` in the code, it makes more sense it would be above `visit_dirs` to me.
- Rename some functions.
- Comment a lot of them.
This PR should not change any logic.
> Comment and reorganize the asset generation algorithm

- static/components.js
This addresses the issue raised in https://github.com/bevyengine/bevy-website/pull/703#pullrequestreview-1522440159 regarding the Vivaldi browser behaving incorrectly. 
The fix is simply to manually clamp the value, which is effectively a no-op on other (well-behaved) browsers
> fix range input min/max handling on vivaldi

- content/news/2023-07-09-bevy-0.11/index.md
Added a snippet to the blog post which mentions the `PlaybackSettings` struct which allows users to manage an audio entity's lifetime.
> Showcase PlaybackMode in the Bevy 0.11 changelog

- sass/pages/_assets.scss
- static/assets.js
- templates/assets.html
WIP for Issue #450 
I created a search bar that can filter cards in JS. The problem is that the cards are in a `grid` and when setting `display:none` it will leave around empty spaces. The only way I see to do it properly would be to change the display of the cards to `flex-row` instead of `grid` (which I think makes more sense for this layout anyway), but that requires quite a bit of work making sure everything is responsive and that there are no regressions.
Result when searching for "MIT"
Any thoughts on this?
> Asset page filtering

- templates/404.html
`https://bevyengine.org/learn1/` not works.
> Fix 404 page logo

- content/learn/book/getting-started/ecs/_index.md
Change the type of the query parameter from `Query<&Transform>` to `Query<&Position>`. 
The first Component that's introduced in the lines above is `Position`, not `Transform`. Seeing the difference in type got me a bit confused. Aligning the types in hopes that 
- Initially used `Position` in #2aa8193
- Changed to `Transform` in #73
> Align the type of the first System's Query to that of the first Component

- templates/examples-webgpu.html
- templates/examples.html
Since #734 we have a search bar on the assets page, I think it will be good to add it to the example page as well.
> Add Search on Examples page

- content/learn/book/troubleshooting/_index.md
This change adds a troubleshooting section including a workaround for https://github.com/bevyengine/bevy/issues/2589
There may be a better solution to this issue and we might have to get in touch with the relevant VSCode extension maintainers but for now, this is a functional workaround.
It seems to be an issue with both cppvsdbg and codelldb.
> Add Troubleshooting: Unable to debug dynamically linked Bevy application in VSCode

- content/learn/book/getting-started/resources/_index.md
Fixes #753. [Comment](https://github.com/bevyengine/bevy/issues/10095#issuecomment-1759481728)
Following the above comment, changed crate from `bevy_core` to `bevy_time` as it has been replaced in the docs
> Changed bevy_core to bevy_time

- content/news/2023-10-21-bevy-0.12/index.md
I added docs to the blog post for the PR `Added HSL methods to Color struct` that I did. It's nothing extraordinary, just QoL feature. I also just wanted to try out working with Git on a bigger project so I hope I did PR properly and as Cart said in the directions 😃 
<div class="release-feature-authors">authors: @idedary</div>
You can now use `h()`, `s()`, `l()` together with their `set_h()`, `set_s()`, `set_l()` and `with_h()`, `with_s()`, `with_l()` variants to manipulate *Hue*, *Saturation* and *Lightness* values of a `Color` struct without cloning. Previously you could do that with only RGBA values.
```rust
// Returns HSL component values
let color = Color::ORANGE;
let hue = color.h();
// ...
// Changes the HSL component values
let mut color = Color::PINK;
color.set_s(0.5);
// ...
// …
```
> Bevy 0.12 Blog Post - Feature "Added HSL methods to `Color` struct"

- content/news/2023-10-21-bevy-0.12/index.md
@hymm @mockersf please let me know if you don't like what I've done with the authors block or have any other feedback.
I tried to keep this as short as possible. IMO, any other info folks need is in the migration guide. Maybe another sentence explicitly mentioning that `SpatialListener` exists would be nice?
> 0.12: Add spatial audio API ergonomics section

- content/news/2023-10-21-bevy-0.12/index.md
Added section on the new throttling that applies when an app has no focused windows.
> 0.12 - Limit Background FPS

- content/news/2023-10-21-bevy-0.12/index.md
Added section for Reflect Commands
> 0.12: Add Reflect Commands section

- content/news/2023-10-21-bevy-0.12/index.md
Writing is hard. Let me know if there's anything I should add/remove. I'm not quite sure how much space I'm allowed to hog.
Some things I left out:
- removing registered systems
- run_system_once_with
> 0.12: One-Shot Systems

- content/learn/migration-guides/0.10-0.11/_index.md
- content/learn/migration-guides/0.4-0.5/_index.md
- content/learn/migration-guides/0.5-0.6/_index.md
- content/learn/migration-guides/0.6-0.7/_index.md
- content/learn/migration-guides/0.7-0.8/_index.md
- content/learn/migration-guides/0.9-0.10/_index.md
- content/learn/migration-guides/introduction/_index.md
- templates/macros/docs.html
Use reverse ordering for the migration guide so that we don't need to update all the weights every release
This require a bit of a hack in the docs.html template to detect that we are on the migration guide page
> Reverse migration guide ordering

- generate-release/src/migration_guide.rs
Instead of looking for PRs with the `C-Breaking-Change` label, look for all PRs that have a Migration Guide section. Still check for PRs with the label to detect if there's any missing migration guide.
> Check all PRs for migration guides

- content/learn/book/getting-started/setup/_index.md
It's probably obvious for someone familiar with installing Fedora packages, but nice to have it spelled out. The linux_dependencies.md doc has Fedora between Ubuntu and Arch so I added these in the same place.
> add lld/mold install instructions for Fedora Linux

- content/learn/book/getting-started/setup/_index.md
mold is now available for MacOS as *sold*.
mold is planning to be released via *sold* as well for windows, but is not available yet, updated new github issue to track progress.
> update info on mold availability on Windows and MacOS.

- content/learn/book/getting-started/ecs/_index.md
Avoid using `Teletype` style for words which are not actual code. And use `Teletype` style consistently for words which are. Replace "emphasis quotes" with _italics_. And a few other similarly minor tweaks.
> Cosmetic changes to _index.md

- content/news/2023-10-21-bevy-0.12/index.md
> 0.12: TypePath

- content/learn/migration-guides/0.11-0.12/_index.md
This type wasn't pub in bevy 0.11 / still isn't, as far as I can tell. Seems to be / have been `pub(crate)`.
> Remove migration guide section on NamedTypePathDef which was not pub

- templates/macros/images.html
avoid failing on missing example screenshot: display Bevy logo as a placeholder
> display Bevy logo if an image is missing

- templates/macros/images.html
after #804, the resize macro adds spaces around image URLs
remove those, and change the placeholder path to an absolute url
> Fix image resize spaces

- content/learn/migration-guides/0.11-0.12/_index.md
This was missed by #798 because [bevy#10339](https://github.com/bevyengine/bevy/pull/10339#) did not have a migration guide section / breaking change label.
> Add migration guide for the default clearcolor change

- content/learn/migration-guides/0.11-0.12/_index.md
Fixes #821 
- Removed note for maintainers
- Add an explicit mention of `into_world_mut` which also got moved to `EntityWorldMut`.
- Replaced `EntityMut` with the new `EntityWorldMut`, checked that the rest of the example code compiles.
> Update migration guide for PRs 9419 and 9604

- content/learn/migration-guides/0.11-0.12/_index.md
It is not uncommon for apps to depend on bevy without `default-features`.
e.g.
- A 2d game that does not want to compile `bevy_pbr`, animation code, etc.
- Anyone who doesn't want the default font.
- Anyone who is doing a webgpu build and needs to disable `webgl2`.
If these apps don't add `multi-threaded`, they are going to have a bad time.
I added some text for that scenario and strengthened the suggestion a bit.
(There also seems to be a bug with `bevy_tasks` not actually working single-threaded? https://discord.com/channels/691052431525675048/1019697973933899910/threads/1172911162808074281) but I'm assuming that'll get fixed up.)
> 0.12 Migration: multi-threaded feature is not just for bevy_ecs and bevy_tasks users

- sass/pages/_assets.scss
- static/assets.js
- templates/assets.html
This PR extends work that was done in [734](https://github.com/bevyengine/bevy-website/pull/734) and adds filter to select the latest supported version 
it does some version normalization:
- ignores any non digits
- pads version with 0
```
^0.9 -> 0.9.0
0.12 -> 0.12.0
0.12.* -> 0.12.0
~0.8 -> 0.8.0
>=0.9 -> 0.9.0
```
also, there are some cases of versions that I don't know how to treat: 'git', '*', 'main'. But all of them are shown when a filter is reset to `all`
P.S. seems like my IDE added some formatting to older code. Hope this will not be an issue )
https://github.com/bevyengine/bevy-website/assets/30506/b9ab467d-35d1-44af-9cbc-264e39a8c3db
for some reason vide does not capture select box, but it is there. Believe me!
> add version filter to assets

- static/tools.js
Fixes #841
Examples keep a "loading" bar with meta files as they are never loaded
Consider every http request with a status different than 200 as finished loading
> ignore http errors when loading assets

- content/learn/book/contributing/_index.md
- content/learn/book/next-steps/_index.md
- content/learn/book/plugin-development/_index.md
- content/learn/book/troubleshooting/_index.md
This PR intends to add a chapter on developing third party plugins to the book to make the info on this topic easily findable.
Closes #298
> Add plugin development chapter to book

- content/learn/book/introduction/_index.md
Update the Godot Rust link from gdnative to gdext, which is compatible with the latest Godot version. This also captures a change in ownership of both of these repos to the org https://github.com/godot-rust
> Update Godot Rust link

- templates/index.html
Updates the landing page's audio feature description to use Audio-as-Entities since the audio feature changed in `0.11`.
Closes #744
> Update landing page audio feature description

- sass/components/_syntax-theme.scss
- static/assets/error_icon.svg
- templates/shortcodes/incorrect_code_block.html
Adds a warning icon with alternative and title text that is in the DOM before the example meaning it _should_ be read before the example by screen readers, probably.
Example of change:
Closes #418
> Make incorrect code examples accessible

- content/learn/links.toml
- content/learn/quick-start/_index.md
- content/learn/quick-start/contributing/_index.md
- content/learn/quick-start/getting-started/plugins/_index.md
- content/learn/quick-start/getting-started/setup/_index.md
- content/learn/quick-start/introduction/_index.md
- content/learn/quick-start/next-steps/_index.md
- content/learn/quick-start/plugin-development/_index.md
- content/news/2020-08-10-introducing-bevy/index.md
- content/news/2020-09-19-bevy-0.2/index.md
- content/news/2020-11-03-bevy-0.3/index.md
- content/news/2020-12-19-bevy-0.4/index.md
- content/news/2021-04-06-bevy-0.5/index.md
- content/news/2021-08-10-bevys-first-birthday/index.md
- content/news/2022-01-08-bevy-0.6/index.md
- content/news/2022-04-15-bevy-0.7/index.md
- content/news/2022-07-30-bevy-0.8/index.md
- content/news/2022-08-10-bevys-second-birthday/index.md
- content/news/2022-11-12-bevy-0.9/index.md
- content/news/2023-03-06-bevy-0.10/index.md
- content/news/2023-05-17-bevy-webgpu/index.md
- content/news/2023-07-09-bevy-0.11/index.md
- content/news/2023-08-10-bevys-third-birthday/index.md
- content/news/2023-09-21-community-reflection-on-bevys-third-year/index.md
- content/news/2023-11-04-bevy-0.12/index.md
- templates/layouts/base.html
Changes references inside the quick start guide from book to quick start guide, fixes links inside of the quick start guide that used to go to the book. It also clarifies and fixes the last section in next steps.
Closes #875 
Fixes #261
> Change current book to quick start guide

- content/learn/migration-guides/0.11-0.12/_index.md
I just commited a change that calls the new behavior a simple rename. I have however made a mistake and the involved types need to be used differently. I've documented this now :)
> Update untyped handle usage

- content/news/2024-02-03-bevy-0.13/index.md
If we look at previous blog posts, they use capitalized titles. The titles in the template also have some missing code formatting and some typos (Animatible -> Animatable, gltF -> glTF)
> Fix typos and capitalize titles in 0.13 template

- sass/elements/_table.scss
I added table styling in #904, but I suddenly realized that I only added the inside borders for the last column 🙈
Tables larger than the two-column one I was using look like this:
This is now fixed:
> Fix table borders

- .github/workflows/ci.yml
97fef72 was committed to the `new-book` branch, adding a job to CI that would test all code blocks and validate them. Unfortunately something in #893 messed it up when merging / rebasing. This PR fixes that by configuring the code validation job to actually validate the code.
Additionally, it also removes the warning from uploading an empty artifact:
[As seen in this run](https://github.com/bevyengine/bevy-website/actions/runs/7787748624)
> Actually run code validation in CI

- .github/workflows/build-wasm-examples.yml
- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .github/workflows/update-screenshots.yml
This PR increases the versions of actions used by CI. The specific actions being updated are split by commit. They are:
- `actions/checkout` to v4 (b9166c2a802a1dbfed418250daa7f2bf3d8d2f68)
- `actions/upload-artifact` and `actions/download-artifact` to v4 (c1cc6afd44ce0f9a17bd622556ae957fa79b2964)
- `actions/cache` to v4 (bc782e70af1a5931cb6ef3129cded2e54b936e4e)
- `peter-evans/create-pull-request` to v6 (459e9c9cb046e0d349f4b692b8916e1d4bf319a2)
A few versions were inconsistent across the project, so this fixes that too. I don't believe any of the breaking changes affect us, since most of the changes were bumping the NodeJS runtime to version 20. The other breaking changes are documented in the commit descriptions.
Many actions were targeting the `master` branch. Since `master` was …
> Bump Github Actions versions

- write-rustdoc-hide-lines/Cargo.lock
- write-rustdoc-hide-lines/Cargo.toml
- write-rustdoc-hide-lines/src/code_block_definition.rs
- write-rustdoc-hide-lines/src/formatter.rs
- write-rustdoc-hide-lines/src/hidden_ranges.rs
From Discord:
> doup — Today at 2:33 AM
> there is a CLI tool in the repo that adds the required zola annotations to the code blocks, go to write-rustdoc-hide-lines folder and run ./write_rustdoc_hide_lines.sh… it doesn't support indented code blocks (e.g. ones inside ul/ol lists)
I don't believe there are actually any code blocks like this currently in the repo. I added a test though, and tried it out on one of the book pages.
Use a regex that accounts for whitespace rather than `starts_with` throughout the code.
Rust tests pass, but it would be nice to ensure this is producing identical output.
> Fix lines not being hidden in indented code blocks

- templates/layouts/base.html
Changes a link to the book into a link to the quick start guide in the mobile page menu.
Fixes #929
> Fix missed mobile page menu link to book

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
Closes #920. This should fix the final warning emitted by the CI. :)
> Use Environmental Files instead of `set-output` command

- content/learn/quick-start/getting-started/setup/_index.md
Sorry, I didn't fully read CONTRIBUTING.md)but this is a very trivial link path change. Just spotted it as I was going through get-started.
> Fix broken fast build file link

- content/news/2024-02-03-bevy-0.13/index.md
For #891 announcement post.
I also added a subsection on relations, since it's a primary motivator for dynamic queries.
But, it feels like it's just too much for this section. Maybe push it to the "what's next?" section… Could use it as a synthesis for all the changes that brings us closer to relations.
@james-j-obrien, @jakobhellermann, @suficio, or anyone. Please tell if anything is wrong or misleading.
I think I got it alright: context + motivation in two sentences, despite the subject being complex and not immediately useful to end users. Then spin it in a way that is interesting (I think) thanks to the amazing projects people are already building on top of dynamic queries, since **those projects** are useful for end users.
> 0.13: Add Dynamic Queries section

- README.md
Trivial PR to fix the link to `CONTRIBUTING.md` from `README.md`.
Fixes #943
> Fix link to CONTRIBUTING in README

- templates/example.html
I think this indentation was added mistakenly in #893. It's already correct in `example-webgpu.html`.
> Fix extra whitespace in example code block

- generate-assets/generate_assets.sh
- generate-community/generate_community.sh
- generate-errors/generate_errors.sh
- generate-wasm-examples/clone_bevy.sh
- generate-wasm-examples/generate_wasm_examples.sh
- write-rustdoc-hide-lines/write_rustdoc_hide_lines.sh
This calls:
```shell
$ cd $(dirname $0)
```
at the beginning of all shell scripts in this repository. This guarantees the assumption that a script will be operating in the same directory it lives in. Namely, the following commands will do the same thing:
```shell
(bevy-website) $ ./generate-assets/generate_assets.sh
(bevy-website/generate-assets) $ ./generate_assets.sh
```
Technically a portion of this was implemented for specifically `write-rustdoc-hide-lines` in #923, but that is not yet merged and this widens the change to all scripts. There will be merge conflicts, but I'll fix them. :)
<details>
<summary>But what is the command actually doing?</summary>
```shell
$ cd $(dirname $0)
```
Let's break it down.
- `cd` stands for "change directory." It changes the current directory to …
> Let shell scripts be called from any directory

- generate-community/generate_community.sh
- generate-wasm-examples/clone_bevy.sh
- generate-wasm-examples/generate_wasm_examples.sh
Many of the shell scripts clone Git repositories such as `bevyengine/bevy` or `bevyengine/bevy-community`. Unlike normal developers, the scripts do not need the full commit history. Because of this, they usually pass `--depth=1` to Git, which only fetches the latest commit on the specified branch.
A few of these scripts have been accomplishing this by doing the following:
```shell
$ git init bevy
$ cd bevy
$ git remote add origin https://github.com/bevyengine/bevy
$ git pull --depth=1 origin latest
```
This can be simplified to:
```shell
$ git clone --depth=1 https://github.com/bevyengine/bevy bevy
```
This PR does exactly that. It reduces the shallow clones to a single command. From my testing, there is no behavioral difference and similar performance.
This is a follow up of #966.
> Simplify shallow clones in shell scripts

- generate-release/src/github_client.rs
Fixes #977 and unblocks #978.
- `NaiveDate::and_hms` is deprecated in favor of `NaiveDate::and_hms_opt`, which returns an `Option` instead of panicking.
- `DateTime::from_utc` is deprecated in favor of `TimeZone::from_utc_datetime`, which I believe does the same thing with a few extra checks.
The deprecated warnings are not shown in CI because `generate-release`'s `Cargo.lock` file is out of date. The reason the error showed up in #977 is because is regenerated the lockfile, causing dependencies to be updated.
> Remove deprecated `chrono` usage

- templates/news.html
Adds public draft support to the news section so that we can have the release notes as public draft and be incrementally worked on during a release cycle rather than leave it as a huge chore for the end.
Relevant discord discourse (and it's surrounding messages): https://discord.com/channels/691052431525675048/692572690833473578/1208084275069722664
Related to #969
> Add public draft support to news section

- content/news/2024-02-17-bevy-0.13/index.md
Fix for #891 
Does what it says on the tin.
> 0.13: Fix author attribution in Entity Opt/Query for_each/TableRow sections

- sass/pages/_content.scss
I accidentally re-created slightly different (and conflicting) table styling in the 0.13 blog post. This removes that in favor of the original, which is slightly better.
> Remove redundant + conflicting table styling

- content/news/2024-02-17-bevy-0.13/index.md
Reported on discord https://discord.com/channels/691052431525675048/691052431974465548/1208509821330923552
> Fix 'chose' 'choose' typo in 0.13 blog

- content/news/2024-02-17-bevy-0.13/index.md
This link is currently pointing to the new book.
> 0.13 news: Fix link to quick start guide

- content/learn/migration-guides/0.12-to-0.13.md
Closes #989 
The idea is to help users when they are just searching for their deprecated primitives, which will help to find the PR that introduced the change.
> Explicit add deprecated shapes on migration guide

- content/learn/migration-guides/0.12-to-0.13.md
The current text/code feels like a lot for this change, and I think the current phrasing could be interpreted as "you need to use this."
The vast majority of users won't be using `Window` without `..default()`, and I would imagine that most folks don't need / want to figure out what value to put in there.
> 0.13 migration: Simplify entry for 7650

- content/learn/migration-guides/0.12-to-0.13.md
The struct was renamed in https://github.com/bevyengine/bevy/pull/10342/commits/694b7c5a63139412e5fbc1f7b6d8b8923f26e9b4 and the migration guide section wasn't updated to accommodate. Reported on Discord here: https://discord.com/channels/691052431525675048/691052431974465548/1208862407477436426
> Rename `DefaultGizmoGroup` to `DefaultGizmoConfigGroup` in `0.12 -> 0.13 Migration Guide`

- content/learn/quick-start/getting-started/apps.md
- content/learn/quick-start/getting-started/ecs.md
Makes a couple prelude boilerplate statements visible again and notifies readers that further use of it will be hidden. Caught after a user experienced issues with the tutorial on Discord: https://discord.com/channels/691052431525675048/691052431974465548/1208911025223761920
> Add back in necessary prelude boilerplate to getting started

- content/learn/migration-guides/0.12-to-0.13.md
The breaking changes were removed in a follow-up PR: https://github.com/bevyengine/bevy/pull/11597 . As such these changes, and their migration guide, were old and irrelevant to the released version of 0.13.
Reported on Discord: https://discord.com/channels/691052431525675048/695741366520512563/1208644034864750683
Notice of removal of breaking changes noted in https://github.com/bevyengine/bevy/pull/11597 's migration guide section.
> Remove `bevy_reflect: Type parameter bounds` migration guide

- content/learn/quick-start/getting-started/_index.md
Closes #894, alternative to #932.
This adds a note to the [getting started] page that mentions platform specific dependencies. This should help guide Linux users into discovering the [Linux Dependencies] guide, as well as help Windows and Mac users.
[getting started]: https://bevyengine.org/learn/quick-start/getting-started/
[Linux Dependencies]: https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md
> Add a note about platform-specific dependencies in quick start

- content/learn/migration-guides/0.12-to-0.13.md
Clarifies the `Texture Atlas rework` migration guide. Uses @rparrett's [migration guide notes](https://gist.github.com/rparrett/508035fa19d3324db0adf8e509e7affd#httpsgithubcombevyenginebevypull10099) and https://github.com/bevyengine/bevy/pull/5103 's change log as a base. 
Resolves #1025
> Clarify `Texture Atlas rework` migration guide

- content/learn/migration-guides/0.12-to-0.13.md
The angle brackets in this section were being treated as html and were not rendered correctly.
> 0.13 Migration: Fix formatting of "simplify conditions" section

- content/learn/migration-guides/0.12-to-0.13.md
This migration isn't required, and following it would break your scenes.
Fixes #1030
> 0.13 migration: Remove name serialization section

- content/learn/migration-guides/0.12-to-0.13.md
This takes the statement of default values from the first section and adds them with updated values to the second section.
Fixes #1034
> Combine `Change light defaults & fix light examples` migration guide with `New Exposure and Lighting Defaults (and calibrate examples) `

- content/learn/migration-guides/0.12-to-0.13.md
This is somewhat implied, but I would have having this all spelled out would have saved me a moment.
> 0.13 migration: Add note about `new_absolute` and `new_relative` being removed

- content/learn/migration-guides/0.12-to-0.13.md
replace `:` where `=` should have been used
The migration guide had a couple cases where `let x: value;` was used, instead of `let x: Type = value;` or `let x = value;`
> Fix assigns in Migration guide

- content/learn/migration-guides/0.12-to-0.13.md
`RenderAssetPersistencePolicy` didn't exist in 0.12, so we don't need to tell users how to migrate it.
The changes described in this section were already applied to the section for the PR that introduced the type in #991.
> 0.13 migration: Remove section for change of type not present in 0.12

- content/learn/migration-guides/0.12-to-0.13.md
The [AtlasImageBundle struct](https://docs.rs/bevy/latest/bevy/prelude/struct.AtlasImageBundle.html#structfield.texture_atlas) does not have a `atlas` field of type `TextureAtlas`, it does however have the `texture_atlas` field.
I think the migration guide did a copy/paste from the [SpriteSheetBundle](https://docs.rs/bevy/latest/bevy/prelude/struct.SpriteSheetBundle.html#structfield.atlas) guide, where the field was renamed to `atlas`
> AtlasImageBundle field name typo in migration guide

- content/learn/links.toml
This PR makes the page that lists Bevy's errors for current release viewable from the learn page.
Closes #766
> Add learn/errors link card to the learn page

- content/learn/migration-guides/0.12-to-0.13.md
And other improvements. I went in there to fix the clippy thing and things sort of snowballed.
- Moved the text to a subsection of the PR that caused the breakage
- Added some context about why it's not a `char` and what else might be in there.
- Added a sentence about a new alternative to `ReceivedCharacter` that folks may want to use instead.
- Modified the previous advice so that it is Clippy-approved.
The previous advice would result in:
```
warning: called `.nth(0)` on a `std::iter::Iterator`, when `.next()` is equivalent
--> src/typing.rs:126:30
|
126 |             let Some(char) = event.char.chars().nth(0) else {
|                              ^^^^^^^^^^^^^^^^^^^^^^^^^ help: try calling `.next()` instead of `.nth(0)`: `event.char.chars().next()`
|
= help: for further information …
```
> 0.13 migration: Use clippy-approved ReceivedCharacter advice

- code-validation/README.md
- generate-assets/README.md
- write-rustdoc-hide-lines/README.md
Part of #1059.
This adds a `README.md` file for the `code-validation` and `generate-assets` tools. It also partially modifies `write-rustdoc-hide-lines`'s `README.md` for consistency.
> Add READMEs to `code-validation` and `generate-assets`

- Cargo.lock
- code-validation/Cargo.toml
- generate-community/Cargo.toml
- generate-errors/Cargo.toml
- generate-release/Cargo.toml
This PR updates `Cargo.lock` by calling `cargo update`. Most of the changes are patch versions; I was unable to find any issues in my brief local testing. Alternative to #834.
<details>
<summary>See all updated crates...</summary>
```shell
Updating git repository `https://github.com/bevyengine/bevy`
Updating crates.io index
Updating ahash v0.8.8 -> v0.8.9
Updating anstream v0.6.11 -> v0.6.12
Updating anyhow v1.0.79 -> v1.0.80
Updating bevy v0.12.0 (https://github.com/bevyengine/bevy#f81aa64c) -> #fd0f1a37
Updating bevy_a11y v0.12.0 (https://github.com/bevyengine/bevy#f81aa64c) -> #fd0f1a37
Updating bevy_animation v0.12.0 (https://github.com/bevyengine/bevy#f81aa64c) -> #fd0f1a37
Updating bevy_app v0.12.0 (https://github.com/bevyengine/bevy#f81aa64c) -> #fd0f1a37
Updating bevy_asset …
```
> Update, prune, and modify dependencies

- .github/workflows/ci.yml
- generate-wasm-examples/clone_bevy.sh
- generate-wasm-examples/generate_wasm_examples.sh
There are several small things that can be done to improve `generate_wasm_examples.sh`, the main entrypoint for generating the WebGL2 and WebGPU examples pages.
- Adds more logging about what the script is doing.
- There are now a few `echo` commands scattered throughout the script.
- Adds comments and update existing ones.
- Deletes `clone_bevy.sh`, merging its contents into the main script.
- `clone_bevy.sh` was likely created so that multiple scripts could all use it for shared functionality. It was only used in CI, so I merged the two scripts into one and updated Github Actions.
- Fetches latest commit if Bevy was already cloned.
- This is primarily for local copies. If you have the `bevy` folder cloned already, it will try to fetch the latest commits. Since it targets the `latest` …
> Improve `generate_wasm_examples.sh`

- content/learn/quick-start/getting-started/setup.md
It would seem that [`sold`](https://github.com/bluewhalesystems/sold?tab=readme-ov-file#sold-linker) is now licensed as MIT, https://github.com/bluewhalesystems/sold/commit/41b49175f58c73dbc0fc769128581de6b981863d
> Sold in MacOS now is MIT licensed

- content/learn/quick-start/getting-started/plugins.md
- content/learn/quick-start/getting-started/resources.md
The `update_people` related code added in the ECS part of the Getting Started docs was not present in further steps (Plugins and Resources), but no instruction was made to remove it.
> Make demo code consistent with previous tutorial steps

- templates/example-webgpu.html
- templates/example.html
- templates/layouts/base.html
Fixes #1067.
By removing some stray `}` chars.
And fixes the first-line indentation that showed up again in the code blocks on the example pages.
> Fix examples

- .github/workflows/ci.yml
In CI, all of the linters are grouped together and run before any of the `generate-*` jobs, except for typos.
Typos was added in #1057. I [originally praised it](https://github.com/bevyengine/bevy-website/pull/1057#pullrequestreview-1901511010) for being separate from the rest of the linters, to increase parallelism. Unfortunately, increasing parallelism is not a viable solution ([as pointed out](https://github.com/bevyengine/bevy-website/pull/1061#issuecomment-1969742951) by mockersf in #1061) because only a limited amount of job runners are allowed per organization. Increasing parallelism for the website would only steal runners from the main Bevy repo, which arguably needs them more.
Since lints should all be run before the longer `generate-*` jobs, this PR adds `typos` to their …
> Group `typos` with linters in CI

- content/learn/quick-start/getting-started/apps.md
Adds a forgotten link to `Plugin` in quick start's getting started apps section.
> Add forgotten link to `Plugin` in quick start's getting started apps section

- content/learn/quick-start/getting-started/_index.md
- content/learn/quick-start/getting-started/setup.md
- content/learn/quick-start/plugin-development.md
I've noticed that bevy is still not updated to `0.13` in the learning sections. A comment to check for new versions is always included but I still think, that this section should use the newest major bevy release
> Update bevy version on `learn` chapters

- content/learn/quick-start/getting-started/plugins.md
Reading through the documentation I noticed a small typo. 
I hope it is fine creating a PR without an issue first for this.
> Docs: Fixed typo and a mistake in the code in plugins.md

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
Closes #1066.
This adds a cache for `generate-assets`, which is the CI job currently takes the longest at ~7 minutes, and reduces its runtime to 11 seconds. The cache is updated ever time the website is deployed using `deploy.yml`. The cache is then used in `ci.yml` when no run in the merge queue.
> Cache `generate-assets` output in CI

- .github/workflows/ci.yml
- .mega-linter.yml
Closes #1087.
This configures the `mega-linter` CI check to use the [Javascript](https://megalinter.io/latest/flavors/javascript/) flavor, as suggested by Trial in https://github.com/bevyengine/bevy-website/issues/1087#issuecomment-1987113660. Flavors are customized version of the default image are smaller and more specialized.
~~The goal of this PR is to decrease the `mega-linter` runtime from 3 minutes to at least 2 minutes, so it will no longer be the slowest job.~~ This appears to decrease the runtime for the `mega-linter` job from 3 minutes to <1 minute!
> Use Javascript `mega-linter` flavor

- templates/donate-community.html
Individual maintainer sponsorship is no longer how to add your logo to the Bevy credits, so we should remove this section from the community donation page.
> Remove mention of site rewards on community donate page

- content/learn/quick-start/getting-started/ecs.md
The reference style markdown links break without new line it seems.
> Make the Query struct link work in getting started ECS page

- content/foundation/meeting-minutes/2024-02-03/index.md
- content/news/2024-03-11-bevy-foundation/index.md
The authors are taken from the `authors` attribute instead of `extra.author`.
This caused the author to show up as the default "Bevy Contributors", both for the news post and the first meeting minutes.
> Fix authors of Bevy Foundation posts

- content/learn/book/getting-started/_index.md
- content/learn/quick-start/getting-started/_index.md
Fixes https://github.com/bevyengine/bevy-website/issues/1088 by adding a redirect from the Book page and removing the unused alias on the Quick Start page. The latter is not necessary for functionality, but included for clarity.
> fix: book/getting-started doesn't redirect to quick-start

- content/learn/quick-start/introduction.md
- templates/index.html
Updates the wording to correspond with current Bevy licensing.
Fixes #190
> Describe the MIT-Apache dual license in the quick start guide.

- content/learn/book/ecs/entities-components.md
- write-rustdoc-hide-lines/src/main.rs
Alternative to #1069.
This makes `write-rustdoc-hide-lines` emit error annotations using [workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) when a file is not formatted correctly and when running through Github Actions. These annotations show up in the job summary:
This additionally groups the list of files checked into a collapsible section when running in Github Actions, so they are not confused with the files that need formatting. Fixes #1100.
Collapsed:
Expanded:
In order for this to work, I needed to switch some `eprintln` calls to `println`, because Github Actions was not detecting them sequentially and error messages were being hidden.
When `write-rustdoc-hide-lines` fails, it will now print a …
>  Github Actions improvements for `write-rustdoc-hide-lines` (v2)

- sass/components/_sponsors.scss
Currently logos that are smaller than the available height will not use the space given to them. This is problematic for SVGs hard-coded to smaller heights.
I've also adjusted the existing heights for diamond and corporate bronze accordingly.
> Make donor logos take up available height

- .djlintrc
- content/donate/individual-sponsors.toml
- content/donate/tiers.toml
- sass/components/_sponsors.scss
- templates/individual-sponsors.html
- templates/sponsors.html
1. Moves base logo sizing config to `tiers.toml`
2. Uses css `calc()` per-logo to calculate the max-height
3. Adds `square_logo` to sponsor config to give square logos a fair area bump relative to wider aspect ratios. This is nice because it removes the need for direct style overrides and makes the rules consistent across sponsors.
4. Adds `logo_scale` which will further scale the final result. This can be configured per-sponsor
5. Fixes mobile clipping introduced in #1120 
In general this allows us to move away from direct style overrides (although they are still supported)
> Improve logo size configurability and fix mobile scale

- .github/workflows/build-wasm-examples.yml
- .github/workflows/update-screenshots.yml
update the script to not use the tools from main. the tools from latest should work, and main has patches that no longer work on latest
compute the number of pages to run the build in a required job
> wasm examples: update the GitHub actions

- sass/components/_sponsors.scss
- templates/sponsors.html
Donors in the Past Donors section are currently too visible relative to actual active donors. This rebalances the size (and aligns the text color with text elsewhere). Smaller text makes sense here because this will likely grow to be pretty large. There might even come a time where we need to remove it entirely (or build a separate page for it).
> Rebalance Past Donor Visibility

- static/tools.js
Try to not display the loading bar on 404s for meta files on wasm examples on the website
I can't reproduce the issue locally, but this seems to close the loading bar even faster in case of 404
Hopefully fixes #1128 and fixes #1119
> bypass the loading bar as much as possible for 404s

- content/learn/book/development-practices/fast-compiles.md
for some reason book/development-practices/fast-compiles.md refers to the "dynamic" feature instead of the actual name "dynamic_linking". so i fixed it.
> correct name of the dynamic_linking feature

- .github/workflows/ci.yml
At the moment if you commit multiple times to a PR while CI is still going it takes up the amount of jobs that can be run at once. Instead we should cancel in progress jobs on new pushes to a PR.
> Cancel in progress CI jobs on PRs

- templates/docs-base.html
There are some cases where the footer links don't show up, or show the incorrect link, for example:
- Previous Page link not showing: https://bevyengine.org/learn/book/getting-started/why-bevy/
- Next page link incorrect: https://bevyengine.org/learn/book/getting-started/bevy-community/
This PR fixes these issues. I've double checked in all the other pages and it seems to work correctly (e.g. `Breakout` draft page doesn't show up).
On this branch.
First case (previous page correct):
Second case (next page correct):
> Fix docs footer navigation

- content/learn/migration-guides/0.12-to-0.13.md
Hello,
While [updating bevy_slippy_tiles to support Bevy 0.13](https://github.com/edouardpoitras/bevy_slippy_tiles/pull/5), I noticed a typo in the migration guide.
> docs: fix incorrect migration path for `poll_once` in docs

- sass/components/_tree-menu.scss
Minor tweaks to `tree-menu` BEM component used in most of the sidebar menus. Changes:
- Reduce horizontal padding to 12px
- Reduce sub-menu (ul > ul) items offset to 12px
- Remove border-radius to the open/close chevron
- Increase line-height for better legibility in multi-line entries
- Balance text in multi-line entries when possible (avoids widows and should look more "balanced")
**DEMO BEFORE/AFTER**
> [!WARNING]  
> Ignore cursor icon in the video, the video recording app sometimes messes the cursor.
https://github.com/bevyengine/bevy-website/assets/188612/6a5cc7c4-ba5b-4a66-8b89-48da495bc552
> Tweak `tree-menu` styling

- content/learn/quick-start/getting-started/setup.md
Adds relevant config file info for using LLD linker in Rust and Bevy to avoid confusion.
Closes #727
> Improve LLD fast compile instructions

- content/learn/book/getting-started/installation.md
Decided to put the linux dependencies on the installation page but no reason they couldn't be on their own page if y'all want.
Mostly copied from [bevyengine/docs/linux_dependencies.md](https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md) but I added a Nix Flake.
> add linux dependency instructions and some placeholder headers

- sass/_vars.scss
- sass/components/_header.scss
- sass/components/_logo.scss
- sass/components/_main-menu.scss
Since there are more items in the header this sometimes leads to overflowing issues for tablet-landscape:
This PR changes the breakpoint settings so that the mobile menu shows earlier. Now, in tablet-landscape (e.g. ipads landscape) we should see the mobile menu:
We will eventually need to rethink the header, but this way this can be postponed. 😅
> Show the mobile header on tablet-landscape

- templates/atom.xml
Fixes #1103 
Adds an `atom.xml` template file that hides pages which are public draft from the news feeds, primary line of code relevant being `Line 23`.  Note, this doesn't modify the last updated date, so that is still tracking the latest file regardless of public draft, but that is a minor issue that I think is irrelevant to our situation so far.
> Add custom `atom.xml` template to hide public draft news articles

- static/on-this-page.js
minor followup to #1147 
I realized that the `on-this-page.js` still referred to it as "page content navigation" or "page_nav" or etc, from before i decided that the one true name:tm: of the feature was "on this page". then i got a bit carried away with jsdoc, and improved the initialization logic.
> Minor On This Page Script Changes

- content/learn/book/development-practices/logging.md
I figured that there should be a page on logging. so i added one under Development Practices.
it's just a placeholder; i just wanted to get it in the book so it's not forgotten.
> create logging page

- content/learn/quick-start/getting-started/_index.md
- content/learn/quick-start/introduction.md
- sass/components/_callout.scss
- sass/site.scss
- templates/shortcodes/callout.html
This PR adds a new `callout()` shortcode. Wrap some markdown in it to show it as a callout/alert/admonition… It implements three styles:
> Add `callout` shortcode

- templates/index.html
Some users might miss the _Stability Warning_ because the homepage `Getting Started` link skips the _Introduction_ and directly points to _Getting Started_. Change the link so there are more chances of seeing the warning.
> Change homepage `Get Started` link so that users don't miss the "Stability Warning"

- sass/_vars.scss
- sass/elements/_html.scss
- sass/fonts/_firamono.scss
- sass/pages/_content.scss
This is just some clean-up. It adds two CSS variables (design tokens) for the website's font families. I would eventually like to add more design tokens (variables/palettes) and use those in the CSS. But for now, let's start small.
This also fixes the paths for `Fira Mono` and uses that font in the code examples.
> Add `--font-family-*` tokens

- templates/shortcodes/callout.html
A quick follow-up fix to #1167 to make the element used semantic.
> Change callout from div to aside

- templates/docs.html
https://github.com/bevyengine/bevy-website/pull/1149 introduced a bug in docs page titles. See: https://bevyengine.org/learn/quick-start/plugin-development/
**BEFORE**
**AFTER**
Fixes #1173.
> Fix doc pages title with special characters

- sass/components/_on-this-page.scss
- sass/components/_tree-menu.scss
Right now TOC is not adding line breaks in the Migrations pages so the text is overflowing:
---
This is after the fix:
> Fix TOC overflow in Migration Guides

- sass/components/_on-this-page.scss
TOC is quite dense and sometimes is difficult to identify the different entries. This PR increases the space between the TOC entries so it's more legible.
See discussion and screenshots in https://github.com/bevyengine/bevy-website/pull/1171#issuecomment-2116859193.
> Increase TOC spacing between entries

- sass/components/_on-this-page.scss
The new "On This Page" section for the sidebar has blue links, which feel out of place and look a bit distracting.
This PR changes the text colors to gray for non-active items and a near-white for active items, also removing the on-hover text shadow in favor of simply lightening the text color.
Before:
https://github.com/bevyengine/bevy-website/assets/57632562/4a3948a2-543b-48f8-9e3f-4d7526d3b119
After:
https://github.com/bevyengine/bevy-website/assets/57632562/d7bdc83f-eb5d-4df7-98a1-df7ced88dcc6
Note that the whole website appears lighter in the above videos for some color encoding reasons, and don't perfectly reflect what it actually looks like.
Here are close-up screenshots with more accurate colors:
(ignore that black border on the right and bottom, not sure what that's about)
> Change text colors for "On This Page" section

- sass/components/_on-this-page.scss
#1175 made the sidebar table of contents less dense, but it still looks too dense. It's hard to distinguish between what is a different entry or just an entry with a name that spans multiple lines, and it just looks a bit out of place with the rest of the layout being more spacious.
Before:
After:
Note: The screenshots above use the text styling from #1176, but these changes are not included in this PR.
> Increase TOC spacing between entries (again)

- sass/_print.scss
- sass/site.scss
- templates/docs.html
- templates/layouts/base.html
- templates/layouts/page-with-menu.html
- Hides everything but the content
- asks the browser nicely to not put page breaks after headers, inside headers, inside paragraphs, or inside code
- hides anchor links (`#`es beside headers)
- Shows link URLs
- fully outlines callouts
example of a whole printed page: [Setup.pdf](https://github.com/bevyengine/bevy-website/files/15383780/Setup.pdf)
> add print styling

- sass/components/_on-this-page.scss
- static/on-this-page.js
- templates/macros/docs.html
scope-creep edition!
- sort by the actual Y position. and not the top border width.
- sort in the correct direction
- handle the case where there are no `<h2>`s (which is the case on migration guides)
- compare `<a href>` which need to be there anyway instead of `<li data-fragment>`
> Fix On This Page algorithm

- templates/docs.html
- templates/layouts/base.html
Hopefully should unblock #1178 
The previous, more procedural, way of determining docs root sections did not take into consideration possible docs sections outside of `/learn/*`. I would've done a better procedural way, but the lack of while loops in Tera threw a wrench in that plan, so for now this is the best I can do without further blocking progress on the contributing guide.
> Hard-code possible docs template root sections

- generate-release/README.md
There were a couple of typos and some shortcodes/paths were outdated. I've added some extra backticks also.
> Fix a couple of typos and improve style in `generate-release` README

- static/assets.js
Fixes #1183
The default value for the version filter was `*`, but the filtering code is looking for `all_versions` as a filter bypass.
This might be indicative of some sort of deeper issue with version comparison.
Either way, `all_versions` seems like the correct value given the following relevant code:
https://github.com/bevyengine/bevy-website/blob/070dfd1a11b4fd684e07a58aa085a78db150c299/static/assets.js#L114-L116
https://github.com/bevyengine/bevy-website/blob/070dfd1a11b4fd684e07a58aa085a78db150c299/templates/assets.html#L18
> Fix default version filter

- generate-release/src/migration_guides.rs
> Bit of a nit, but I'm not a fan of all the white space inconsistency in the migration guide. How easy would it be to call str::trim on the file contents, then write an extra \n?
- @BD103 in https://github.com/bevyengine/bevy-website/pull/1191#issuecomment-2126861114
Progress towards #1195.
> Normalize migration guide whitespace

- generate-release/src/markdown.rs
Fixes #1190.
Poking through the code here, this is the only form of logging of this sort found. Since a TODO section is added anyways, there's no value in manually logging this error case.
We could instead log which PR this was associated with, but that's noisy and unhelpful: all of these need to be manually checked anyways and a stub is generated already.
> Remove confusing logging about "migration guide not found"

- generate-release/src/release_notes.rs
It's sometimes useful to have a reference to what the PR is when writing the notes.
> Generate a comment with PR link for release notes

- templates/layouts/base.html
https://canary.discord.com/channels/691052431525675048/695741366520512563/1245150398663360542
so i did it:
> show [DRAFT] in the <title> of draft pages

- templates/docs.html
- templates/layouts/base.html
Since public draft no longer applies only to docs pages, these tags should be in a universal place. Otherwise, for example, the news posts would still be visible to search engines generally.
Issue pointed out on Discord here by HopelessPlatonic / SIGSTACKFAULT: https://discord.com/channels/691052431525675048/695741366520512563/1245168247368712212
> Move public draft meta tags to base template

- release-content/0.14/release-notes/10690_Upgrade_to_Taffy_04.md
- release-content/0.14/release-notes/_release-notes.toml
@nicoburns, I'd appreciate your review here for correctness and context :)
> Remove taffy upgrade from release notes

- sass/pages/_foundation.scss
Currently, the foundation page has a horizontal scrollbar on most mobile devices due to the foundation logo having a fixed size larger than the page width.
This PR adds a maximum width of 100% to the logo style to avoid this issue.
> Make foundation logo responsive to avoid horizontal scrollbar on mobile

- release-content/0.14/release-notes/12672_Make_dynamic_linking_a_noop_on_wasm_targets.md
- release-content/0.14/release-notes/_release-notes.toml
Closes #1304.
I fear this may be too brief, but it gets the point across.
> Release notes for 12672: Dynamic linking no-op on WASM

- release-content/0.14/release-notes/13347_Add_on_unimplemented_Diagnostics_to_Most_Public_Traits.md
> Write Release Notes for `on_unimplemented` Update

- release-content/0.14/release-notes/5781_bevy_reflect_Recursive_registration.md
Fixes #1236 
Adds release notes for recursive registration in `bevy_reflect`.
---
There's a small amount of nuance that I chose to gloss over such as why we're doing this instead of using `inventory` or `linkme`, or which specific things actually rely on these registrations.
I also chose not to go into detail about how this works under the hood via changes to `GetTypeRegistration` since most users probably don't even know that trait exists.
I did, however, mention that there is still an opportunity for a footgun if a type that's used on its own (i.e. a component, a resource, etc.) is implicitly registered by another type. This is hopefully a lot less likely to occur than forgetting to register an internal type, but still a possibility. This isn't required information, so we can remove it …
> Add release notes for PR #5781: bevy_reflect: Recursive registration

- release-content/0.14/release-notes/13270_Extrusion.md
- https://github.com/bevyengine/bevy/pull/13688 has recently added the `BoundedExtrusion` trait.  This trait was not mentioned in the release notes before, but now it is.
> Update Extrusion release notes to mention `BoundedExtrusion`

- release-content/0.14/migration-guides/12234_Move_commands_module_into_bevyecsworld.md
The description and code example for the [Move commands module migration guide](https://bevyengine.org/learn/migration-guides/0-13-to-0-14/#move-commands-module-into-bevy-ecs-world ) did not match. Checked that the example was wrong and changed it.
> 0.14 migration: Fix example code for moved commands module

- release-content/0.14/migration-guides/12709_Error_info_has_been_added_to_LoadStateFailed.md
It looks like these three separate sentences were intended to have some line breaks. In the current rendered migration guide, they end up all smooshed into one big crazy paragraph.
I also added a small code block for one specific scenario I encountered.
This section might need some more work (is the third item even breaking?) but I'm not really sure what to suggest for people who were ordering `LoadState` because I don't understand why someone would have needed to do that.
Happy to implement suggestions / nuke the third line, but would prefer to get this formatting improvement in without doing more research on this changeset.
> 0.14 migration: Fix formatting of LoadStateFailed migration

- release-content/0.14/migration-guides/13216_Separate_state_crate.md
I was blocked for a while when migrating to 0.14 because I didn't realize that on top of adding the `bevy_state` feature you need to add the `StatesPlugin`
I'm actually a bit confused as to why adding the `StatesPlugin` was needed:
- https://github.com/bevyengine/bevy/blob/main/crates/bevy_state/src/app.rs#L193 it doesn't seem to do much apart from inserting an empty `StateTransition`  schedule
- but then inserting a new state (https://github.com/cBournhonesque/bevy/blob/a4f324fdb490d75d808fd8cb54690a7b35af2f9d/crates/bevy_state/src/state/transitions.rs#L148-L148) doesn't add the sets inside the `StateTransition` schedule
Is it correct that we need the  `StatesPlugin` for states to work? It seemed to me that states did not work if I was just using the MinimalPlugins
> Mention StatesPlugin in the migration docs

- release-content/0.14/migration-guides/13216_Separate_state_crate.md
Minor, but this might save someone a second, or help them find the right section with ctrl-f.
Also added emphasis to `crate` and `feature` in lines above, as I remember that being misread by someone.
> 0.14 migration: Show new paths to state types

- release-content/0.14/migration-guides/9202_Refactor_App_and_SubApp_internals_for_better_separation.md
See https://github.com/bevyengine/bevy/pull/13754#issuecomment-2158517375
App is not `Send` anymore, because `App` will contain the Non-Send resources (so that World and SubApp can be completely Send)
> Explain that `App` is not `Send` anymore

- templates/docs.html
- templates/layouts/base.html
- templates/macros/base.html
Before in the mobile page menu the page name / docs section name for the menu was showing as Migration Guides for all but the Book since the page name hadn't been updated as new docs sections has been added.
> Fix wrong docs section name showing up in the mobile page menu

- release-content/0.14/release-notes/13453_add_handling_of_all_missing_gltf_extras_scene_mesh__materi.md
> docs(gltf_extras): added small description of the newly added gltf_extras

- release-content/0.14/migration-guides/12868_Deprecate_ReceivedCharacter.md
This primarily fixes an issue where the behavior in the code was not matching this comment:
```
// Only check for characters when the key is pressed.
```
I believe the comment is correct. In places where users were previously using `ReceivedChar`, they would want the character immediately upon the key being pressed rather than waiting for release.
> Fix reversed logic in ReceivedCharacter section

- release-content/0.14/migration-guides/12163_Migrate_from_LegacyColor_to_bevy_colorColor.md
These are simple changes to migrate, but we are asking users to do a lot of research and could be helping them out a bit more.
I think these three colors were the extent of the damage for "color values getting changed," though maybe we could also throw "colors that simply had their names changed" into the table as well.
Do we have a handy list of those? I thought they were listed in some iteration of the migration guide previously.
For reference:
https://github.com/bevyengine/bevy/pull/12451
https://github.com/bevyengine/bevy/pull/12333
https://github.com/bevyengine/bevy/pull/12328
> 0.14 migration: Slightly more help for users who had their colors changed

- Cargo.lock
- code-validation/src/lib.rs
- generate-release/Cargo.toml
- generate-release/src/github_client.rs
Fixes #1399!
This change disables the [`clippy::doc_markdown`] lint for our `code-validation` tool. This lint requires code-like text to be surrounded by backticks. The problem with it is that it thinks Tera templates `{{ ... }}` and front-matter are code-like, and wants backticks around them. Doing so would break the website, though.
[`clippy::doc_markdown`]: https://rust-lang.github.io/rust-clippy/stable/index.html#/doc_markdown
While it is nice to catch missing backticks, it's not `code-validation`'s first responsibility. It's first responsibility is to test all of our code blocks to ensure they are valid.
One final note: I originally tried using the `[lint]` table in `Cargo.toml` to disable this lint, but `workspace = true` is incompatible with this: I would have had to duplicate all …
> Allow `clippy::doc_markdown` in `code-validation` and fix `lint-tools` job

- sass/elements/_table.scss
Fixes #1271
Also apply border radius to first/last `th` elements.
Tested in chrome and firefox on macos.
> Fix top of table borders

- Cargo.lock
- code-validation/Cargo.toml
- generate-assets/Cargo.toml
- generate-community/Cargo.toml
- generate-errors/Cargo.toml
- generate-release/Cargo.toml
- write-rustdoc-hide-lines/Cargo.toml
All of the Cargo projects in this repository are internal and should never be published on <https://crates.io>. This PR sets the [`publish`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field) field to false to prevent `cargo publish` from accidentally succeeding.
Furthermore, this also removes the `version` field. These tools do not need a version field because nothing outside of the repository should be depending on them.
> Set `publish = false` for all tools

- sass/elements/_details.scss
Went on a tangent to give `details > .callout` the same styles as `details > pre.z-code`.
before:
after:
also turns out that I used the wrong sibling selector in #1155 DX
> add styles for details > .callout

- content/learn/book/development-practices/fast-compiles.md
- content/learn/quick-start/getting-started/setup.md
Fixes #45. Fixes #1085.
Completely removed the "Fast Compiles" page in the book and replaced it with strongly-worded instructions for when the book ships. Then rewrote the fast compiles section in quick-start while i was at it.
> Deduplicate and rewrite Fast Compiles section

- Cargo.lock
- code-validation/Cargo.toml
We're in the release stage! 🥳 Because of this, we should begin testing all website code on the latest release candidate. I additionally updated the comment to take into account the release candidate process.
When a new release candidate (or stable 0.14!) is published, this should be updated again.
I rebased this on #1403, so consider this blocked until that is merged. If you're reviewing before then, just take a look at b581c219e2938028aa9b0a66cbf7205d1811e5c4.
> Bump `code-validation` to Bevy 0.14.0-rc.2

- code-validation/src/lib.rs
- content/learn/book/getting-started/app-appbuilder-world.md
- content/learn/book/getting-started/apps-worlds.md
AppBuilder got BLAPPED in [bevy#2351](https://github.com/bevyengine/bevy/pull/2531)
also write a bit of actual content.
> rename "App, Appbuilder, and World" => "Apps and Worlds"

- content/learn/migration-guides/0.12-to-0.13.md
> Fixed casing for a migration guide title

- release-content/0.14/migration-guides/12218_Deprecate_SpriteSheetBundle_and_AtlasImageBundle.md
The code blocks may be a bit too much. I'm not attached to them.
But I found the previous wording somewhat unclear.
> 0.14 migration: Touch up SpriteSheetBundle deprecation section

- release-content/0.14/migration-guides/12313_Disentangle_bevy_utilsbevy_cores_reexported_dependencies.md
Cleaned up and explicitly mention the previously re-exported `bytemuck` types for searchability.
> 0.14 migration: Touch up bevy_utils re-exports section

- release-content/0.14/migration-guides/11823_Immediately_apply_deferred_system_params_in_Systemrun.md
- release-content/0.14/migration-guides/11986_Remove_the_UpdateAssets_and_AssetEvents_schedules.md
- release-content/0.14/migration-guides/12038_fix_some_typos.md
- release-content/0.14/migration-guides/12105_Made_bevy_color_a_dependency_of_bevy_render.md
- release-content/0.14/migration-guides/12163_Migrate_from_LegacyColor_to_bevy_colorColor.md
- release-content/0.14/migration-guides/12164_Make_sysinfo_diagnostic_plugin_optional.md
- release-content/0.14/migration-guides/12234_Move_commands_module_into_bevyecsworld.md
- release-content/0.14/migration-guides/12302_Allow_setting_RenderAssetUsages_for_gLTF_meshes__materials.md
- release-content/0.14/migration-guides/12311_Remove_ComponentStorage_and_associated_types.md
- release-content/0.14/migration-guides/12314_Clean_up_type_registrations.md
- release-content/0.14/migration-guides/12512_Update_to_fixedbitset_05.md
- release-content/0.14/migration-guides/12526_Solve_some_oklaba_inconsistencies.md
- release-content/0.14/migration-guides/12550_Use_asyncfn_in_traits_rather_than_BoxedFuture.md
- release-content/0.14/migration-guides/12575_Color_maths_4.md
- release-content/0.14/migration-guides/12655_Removed_IntoAssedIdT_for_HandleT_as_mentioned_in_12600.md
- release-content/0.14/migration-guides/12709_Error_info_has_been_added_to_LoadStateFailed.md
- release-content/0.14/migration-guides/12827_Consolidate_RenderUiMaterials2d_into_RenderAssets.md
- release-content/0.14/migration-guides/13022_Make_AppExit_more_specific_about_exit_reason.md
- release-content/0.14/migration-guides/13080_Deprecate_dynamic_plugins.md
- release-content/0.14/migration-guides/13159_Improve_tracing_layer_customization.md
- release-content/0.14/migration-guides/13177_Make_AssetMetaCheck_a_field_on_the_asset_plugin.md
- release-content/0.14/migration-guides/13209_move_wgsl_color_operations_from_bevy_pbr_to_bevy_render.md
- release-content/0.14/migration-guides/13465_Make_LoadContext_use_the_builder_pattern_for_loading_depen.md
- release-content/0.14/migration-guides/13637_Move_state_installation_methods_from_bevy_app_to_bevy_stat.md
- release-content/0.14/migration-guides/9202_Refactor_App_and_SubApp_internals_for_better_separation.md
- release-content/0.14/migration-guides/_guides.toml
Another round of migration guides! (Part of #1396.)
~~@james7132, would you mind confirming that I was correct in removing https://github.com/bevyengine/bevy/pull/12314 from the migration guide? It would only be a breaking change if it no longer registered a type that was registered previously. (Non-blocking, though, if you don't find the time for this!)~~
> The Bevy of birds are migrating south for the summer

- release-content/0.14/release-notes/10756_hooks_and_observers.md
- release-content/0.14/release-notes/_release-notes.toml
Fixes #1409. Hooks apparently didn't get an issue, but that's fine.
I've decided to tackle these together, focusing on the context of "why and how should I use all these different tools".
Talking to users about the feature, this was the primary confusion / area to clarify: not the API.
> Release notes for hooks and observers

- release-content/0.14/release-notes/10756_hooks_and_observers.md
Revised #1428 following [feedback](https://discord.com/channels/691052431525675048/1239930965267054623/1253065476775481404).
> Improve clarity on observers vs hooks

- release-content/0.14/release-notes/10756_hooks_and_observers.md
@cart justifiably complained that there were no code samples!
I've swapped out some of the text for code covering the same points, while also demonstrating the API.
> Add code samples to hooks-and-observers release notes

- release-content/0.14/migration-guides/12163_Migrate_from_LegacyColor_to_bevy_colorColor.md
I included a mistake in this table when I added it -- `GREEN`'s new equivalent is `LIME`, not `LIME_GREEN`. `LIME_GREEN` isn't even a thing anymore, it's `LIMEGREEN`. 😅
Also alphabetized the list and added a few more examples. This may still not be totally comprehensive, but I did a quick side-by-side scan of the color constants before/after.
> 0.14 migration: Fix an error in colors table and add more colors

- release-content/0.14/release-notes/13123_Implement_a_SystemBuilder_for_building_SystemParams.md
Fixes release blog currently rendering like this:
> 0.14 release: Fix unclosed code tag

- release-content/0.14/release-notes/12013_Upstreaming_bevy_color.md
Mainly fixing this: 
```
let blue = Oklcha = tailwind::BLUE_500;
```
But cleaned up some whitespace as well.
> 0.14 release: Minor cleanup in upstreaming bevy color section

- release-content/0.14/release-notes/10756_hooks_and_observers.md
Updated the relevant example in the release notes to properly reflect the current state of the codebase and also encourage a more ergonomic approach to use of the observer type
> Updated observer example

- release-content/0.14/release-notes/12889_Implement_GPU_frustum_culling.md
First time writing release notes!
This admittedly feels pretty bland, mostly due to the fact that the change isn't clearly motivated yet. I'm not that familiar with the subject matter, so I wasn't able to glean exactly what the benefit is, though I can only assume that there are performance implications depending on the use case.
I think I have the bones in place, but might need some help filling in the gaps!
Fixes #1307.
> Add release notes for GPU frustum culling

- generate-release/src/migration_guides.rs
- generate-release/src/release_notes.rs
This will make generated toml by these tools more closely match the formatting that is produced by `taplo` (as recommended in `CONTRIBUTING.md`). This should result in less of a mess when someone's editor auto-formats them.
There are some places where this still won't match because there are many entries in the array and they won't fit on one line. We should probably be using the `toml` crate to generate this instead of building it manually.
```diff
[[guides]]
title = "Decouple `BackgroundColor` from `UiImage`"
url = "https://github.com/bevyengine/bevy/pull/11165"
- areas = ["Rendering","UI"]
+ areas = ["Rendering", "UI"]
file_name = "11165_Decouple_BackgroundColor_from_UiImage.md"
```
```diff
[[release_notes]]
title = "Upstreaming bevy_color."
- authors = ["@viridia","@mockersf"]
+ …
```
> Add spaces to match formatting by taplo in guide and notes generators

- release-content/0.14/migration-guides/12889_Implement_GPU_frustum_culling.md
- release-content/0.14/migration-guides/_guides.toml
Adds migration notes for https://github.com/bevyengine/bevy/pull/12889 . Closes #1454 .
> Add migration notes for 12889 Implement GPU frustum culling

- release-content/0.14/release-notes/13270_Extrusion.md
- release-content/0.14/release-notes/_release-notes.toml
Fixes #1458.
I've used h4 headings instead of h2, which look much better. There are a couple other nits that I grabbed while I was here.
> Clean up extrusions section of release notes

- release-content/0.14/release-notes/10756_hooks_and_observers.md
Replaced `Targeting` with `Target`.
> Fix typo in `ECS Hooks and Observers` section

- release-content/0.14/release-notes/_release-notes.toml
I am listed in some release notes as an author even though I don't consider myself to be one, so I thought I'd remove myself from there. For the `VectorSpace` PR, I didn't even comment or participate in any other way, so I'm not sure how I ended up there :P
> Remove Jondolf as author from some release notes

- generate-release/src/migration_guides.rs
Sometimes migration guides section are empty.
Skip them and log it so the person that ran the tool is aware of the potential false positive.
> Skip empty migration guides

- release-content/0.14/release-notes/12747_Move_Point_out_of_cubic_splines_module_and_expand_it.md
Removed last paragraph that talked about a small change to `VectorSpace`, all of it is included in the top paragraph.
Merged the remaining last two paragraphs, improved wording, fixed typos and broke up a long chained sentence.
> Tidy up release notes for PR 12747 and cubic splines

- content/learn/migration-guides/0.13-to-0.14.md
- release-content/0.14/migration-guides/12314_Clean_up_type_registrations.md
- release-content/0.14/migration-guides/12547_Add_AsyncSeek_trait_to_Reader_to_be_able_to_seek_inside_as.md
- release-content/0.14/migration-guides/12551_Remove_WorldCell.md
- release-content/0.14/migration-guides/12666_FIX12527_Changes_to_make_serde_optional_for_bevy_color.md
- release-content/0.14/migration-guides/_guides.toml
This builds on @BD103's excellent work refining these, and closes #1396.
A few small corrections,  and I've moved the most vital breaking changes to the top for prominence.
We could go further, but I'm very happy with the state of this as it is now.
> Editing pass for the migration guide

- content/learn/migration-guides/introduction.md
The TOC for the migration guides page currently looks like this:
The 0.14 migration should not be before the introduction page. The order of these pages is determined by the "weight" property of each, the larger the weight the higher up it will be.
To fix this issue, I increased the weight of the introduction to 999 so it should realistically never happen again. (Can't wait for Bevy 1.1004.0.)
> Fix 0.14 migration guide being before the introduction

- content/news/draft-bevy-0.14/index.md
- release-content/0.14/changelog.toml
```
cargo run -- --from v0.13.0 --to release-0.14.0 --release-version 0.14 changelog
```
tool output:
```
❯ cargo run -- --from v0.13.0 --to release-0.14.0 --release-version 0.14 changelog
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
Running `/Users/chris/github/bevyengine/bevy-website/target/debug/generate-release --from v0.13.0 --to release-0.14.0 --release-version 0.14 changelog`
Getting list of all commits from v0.13.0 to release-0.14.0
Page: 1 (250 commits)
Page: 2 (250 commits)
Page: 3 (250 commits)
Page: 4 (167 commits)
Page: 5 (0 commits)
Found 917 commits
Getting list of all merged PRs from v0.13.0 to release-0.14.0 with label None
Page: 1 (59 prs)
Page: 2 (64 prs)
Page: 3 (66 prs)
Page: 4 (64 prs)
Page: 5 (64 prs)
Page: 6 (61 prs)
Page: 7 (58 prs)
Page: 8 …
```
> generate changelog

- templates/news-page.html
The hard coded image size (specifically the height) prevents it from following the aspect ratio of the image, resulting in it stretching when there isn't enough space. These were added in #1026 ... I don't think this is a good rule to enforce.
> Remove hard-coded width and height from news page image

- templates/news-page.html
This PR adds the `aspect-ratio` property to the image header of all news posts (defaults to 16:9). This lets the browser allocate space on the page for it before the image loads, reducing layout shifts after the first paint. [See this link for an example of layout shifts.](https://web.dev/articles/optimize-cls#images-without-dimensions)
The aspect ratio is set using inline CSS so it is loaded with the very first request, in case the normal style sheet is delayed. I use `aspect-ratio: auto 16 / 9` to tell the browser that the image is usually 16:9, but `auto` says to override this ratio once the image loads in case it is different. [See this section on `auto`.](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio#auto_ratio)
This PR is a follow up to #1519, which removed the …
> Add aspect ratio to news images

- content/learn/quick-start/getting-started/setup.md
Fix path by switching `.config/cargo.toml` to `.cargo/config.toml`
[source](https://github.com/rust-lang/rustc_codegen_cranelift?tab=readme-ov-file#download-using-rustup) for fix
> Fix path of config.toml

- content/learn/quick-start/introduction.md
Fixes #1549 
Changes the contributing page link on the quick start introduction page from the old contributing section, which is a dead link, instead to the `CONTRIBUTING.md` file for the Bevy engine repository.
> Fix broken contributing page link in quick start introduction

- release-content/0.14/migration-guides/13022_Make_AppExit_more_specific_about_exit_reason.md
- release-content/0.14/migration-guides/9202_Refactor_App_and_SubApp_internals_for_better_separation.md
Fixes #1540. This now mentions how `App::set_runner()` requires the function to return `AppExit`, and how `App`'s properties are now private.
> Fix migration guide related to `App`

- .github/workflows/update-screenshots.yml
- Fixes #1534.
- This PR adds an image compression step to the [`Update Screenshots`](https://github.com/bevyengine/bevy-website/actions/workflows/update-screenshots.yml) GitHub Action.
- The whole compression overhead (installing `oxipng` and running it with the maximum compression level) adds about a minute to the workflow runtime, which is minuscule when compared to the avg. ~3h completion time.
> Automatically run `oxipng` on example screenshots

- Cargo.lock
- code-validation/Cargo.toml
It's been a while since the lockfile was refreshed, and a few dependencies are out-of-date.
This is semi-adopted from #1545, except it updates **all** dependencies.
Furthermore, this also increases the minimum required version of `bevy` in `code-validation` to 0.14.
If there are any issues here, CI should catch it. :)
> Run `cargo-update` and bump `bevy` in `code-validation`

- content/donate/faq/index.md
#1564 Removed the legacy sponsors section, but a reference remained within the donation FAQ.
> Remove remaining reference to legacy sponsors page

- Cargo.lock
- generate-assets/Cargo.toml
- generate-assets/src/bin/generate.rs
- generate-assets/src/lib.rs
Help users find up-to-date assets quicker
Fixes #760
Fixes https://github.com/bevyengine/bevy-assets/issues/297
Sorts assets by the following key:
```rust
(
// Any existing order defined in the bevy-assets metadata.
// e.g. for "official" templates and learning material
existing_order,
// Uses the semver crate to compare the "version requirement" from the asset with
// the latest Bevy version
is_semver_compatible_with_latest_bevy,
// If all else is equal, randomize
random
)
````
> Sort assets that use the latest Bevy version first

- content/donate/faq/index.md
The info on donation page updates only every  8  hours.
Fix statement in FAQ claiming that the update happens within one hour.
> Donation FAQ: Correct expected update time for donation page

- code-validation/src/lib.rs
- generate-assets/src/lib.rs
It's new Rust day!
Similar to #1403, a new clippy lint was complaining about markdown in the book.
And also some trivial indentation in `generate-assets` doc comments.
> Fix clippy lints for Rust 1.80

- content/learn/migration-guides/0.12-to-0.13.md
This seems to be necessary.
It's possible that it's not necessary when specifying a canvas by id, but I didn't test that. Either way, with Bevy's defaults, I believe this is needed.
note: `fit_canvas_to_parent` was re-added in Bevy 0.14, but seemingly only as a convenience for users without the ability to use css. So I am pretty sure this is still relevant.
> 0.13 migration: Fix canvas size css

- release-content/0.14/migration-guides/13317_12502_Remove_limit_on_RenderLayers.md
Fixes #1554 
This was an undocumented breaking change in https://github.com/bevyengine/bevy/pull/13317 which missed initial migration guides writing.
> Mention in migration guide 13317 that `Copy` trait is no longer implemented on `RenderLayers`

- release-content/0.14/migration-guides/10973_Contextually_clearing_gizmos.md
- release-content/0.14/migration-guides/_guides.toml
Fixes #1551 
Mentions that `insert_gizmo_group` is now `insert_gizmo_config`.
> Add contextually clearing gizmos Migration Guide for 0.13 to 0.14

- release-content/0.14/release-notes/13366_fix_upgrade_to_winit_v030.md
Fixes #1559 
The reference link portion existed, but was not used, and the name the example was referred to in the document was labelled incorrectly (`window/custom_winit_event.rs` rather than `window/custom_user_event.rs`). This PR fixes both issues.
> Fix 13366 release note `window/custom_user_event` link

- generate-release/src/main.rs
Fixes #1465 
Currently `generate-release` uses the relative path of `../release-content`, but this is dependent on where you're calling from and as such is undesirable.
This PR instead uses the `current_exe()` function to get the absolute path to the executable, which in our use cases will always be `{workspace}/target/{debug|release}/{executable}`. So if we get the workspace directory (equivalent to the root of the project, which is what we want), then we always have the correct directory regardless of if we call it in `generate-release` or `{workspace}`.
It has not been tested fully; when I try to run it, it seems to require a `GITHUB_TOKEN` to make issues and PRs which is undesirable in testing imo.
> Change generate-release to use a better path to release-content

- content/contributing/_index.md
- content/contributing/helping-out/_index.md
- content/contributing/helping-out/reporting-issues.md
This updates the layout of the Contributor's Guide to mirror the layout in [HackMD](https://hackmd.io/qWCaVBIuR6aF692yZNPvTA). It also fixes some issues where sections where missing, and removes redundant configuration.
Instead of trying to comprehend the changes, I recommend running `zola serve` and seeing the changes for yourself. You can find the guide at <http://127.0.0.1:1111/contributing/>.
> Fix Contributor's Guide layout

- templates/sponsors.html
Square logos are currently slightly too small relative to the average "width dominant" logo. Lets give them a buff :)
> Bump square_logo scale

- Cargo.lock
- generate-release/src/main.rs
- generate-release/src/release_notes.rs
Closes #1587.
`generate-release`, by default, creates many issues and comments for missing release notes. This is easy to do accidentally and annoying to clean up. There is the `--local` flag, which is the equivalent of `--dry-run`, but it's easy to miss.
This PR replaces `--local` with `--create-issues`, which has the opposite effect of its predecessor. Now if you want to create an issue, you **must** specify `--create-issues`. By default, it will now just print the expected issue content without creating anything.
> Inverse `--local` flag for `generate-release`

- generate-release/src/release_notes.rs
Fixes #1468 
These are being separated since contributors can include changes on the level of typo fixes which is not desired for the authors position. 
Tested with cargo check, clippy, and fmt.
> Separate contributors from authors for release notes

- content/contributing/helping-out/how-you-can-help.md
Zola renders shortcode content within a different context, so you need to specify links within them.
This is the callout block before this PR (note "[Discord]"):
> Fix Discord link in callout

- README.md
Currently, the build process uses Zola `0.17.2` (ref https://discord.com/channels/691052431525675048/695741366520512563/1272241115558314037) so added that to the README so people don't try to use the latest Zola version (which is currently incompatible)
Also changed the link to go directly to the installation page, and changed the wording from `Download Zola` to `Install Zola`, small copyedits :)
> Add specific zola version currently being used

- README.md
Unfortunately I didn't have time to catch #1600 before it was merged. The website actually uses Zola 0.18, not 0.17.2! It was updated last February in #1018. 
Note how we pull in `shalzz/zola-deploy-action@v0.18.0`:
https://github.com/bevyengine/bevy-website/blob/e285dfdc5149b13129b81472c5ad201abdf61d08/.github/workflows/ci.yml#L247-L253
https://github.com/bevyengine/bevy-website/blob/e285dfdc5149b13129b81472c5ad201abdf61d08/.github/workflows/deploy.yml#L47-L53
> Fix README to specify Zola 0.18

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- CONTRIBUTING.md
- config.toml
- content/contributing/helping-out/writing-docs.md
Closes #1601 
Update Zola to v0.19.2 so that folks can just use the latest version without worry.
Modify the the `config.toml` to account for the support for multiple types of feeds (RSS, and Atom), and remove an erring line on our part (`highlight_themes` seems to be only valid under the `[markdown]` category, and I don't know why this didn't error before).
Change the work flows to use v0.19.2 of Zola.
Also update the CONTRIBUTING.md and Contributing Guide to reflect that we've changed versions
> Update Zola to v0.19.2

- templates/news-page.html
> Fix date formatting for days with one digit

- content/foundation/meeting-minutes/2024-02-03/index.md
- content/learn/migration-guides/0.6-to-0.7.md
- content/learn/migration-guides/0.7-to-0.8.md
- content/news/2020-08-19-scaling-bevy/index.md
- content/news/2021-08-10-bevys-first-birthday/index.md
- content/news/2023-08-10-bevys-third-birthday/index.md
- content/news/2024-02-17-bevy-0.13/index.md
Fixes #1607 
Run the command `find . -type f - exec sed -i 's/Github/GitHub/g' {} +` in `/content` to search and replace all references of `Github` to `GitHub` in the website's content.
1. Clone or get my `bevy-website` fork as a remote
2. Fetch the remote.
3. `git switch trialdragon/1607_fix_github_capitalization` to get my working branch.
4. Run `zola serve` to see a local version of the website and check if the changes are made user-side.
> Change Github to GitHub across the website's content

- content/learn/contribute/helping-out/how-you-can-help.md
Fixes #1611
Changes the `TODO` links in `how-you-can-help` to their proper links (and updates a reference to `Your First Pull Request` to the current `Opening Pull Requests`).
1. Clone or get my `bevy-website` fork as a remote
2. Fetch the remote.
3. `git switch 1611_fix_todos_in_contribute` to get my working branch.
4. Run `zola serve` to see a local version of the website and check if the changes are made user-side.
> Change TODO links to proper links in How You Can Help

- content/learn/contribute/helping-out/opening-pull-requests.md
Migrate the `bevy` repository's `.github/contributing/engine_style_guide.md` to the Opening Pull Requests page, so that the modern guide has parity with the old contributing guide and materials for https://github.com/bevyengine/bevy/issues/14884
Create a new second-level header for the style guide and copy the engine style guide to it verbatim.
Run `zola serve --open` on the branch `trialdragon/migrate_engine_style_guide`, and explore `/learn/contribute/helping-out/opening-pull-requests#style-guide`.
> Migrate engine style guide to Contributing Guide

- content/learn/contribute/helping-out/how-you-can-help.md
- content/learn/contribute/project-information/working-groups.md
Bring the Contributing Guide's Working Group page up to date with the `bevy` repository's `CONTRIBUTING.md`.
Port over the last two commits relevant to working groups (https://github.com/bevyengine/bevy/commit/68db79862227885bb5d4794c2636e1749e36e574 https://github.com/bevyengine/bevy/commit/4a312a12e79ccf32b54ba2d3e99053685028c055).
Run `zola serve --open` in `trialdragon/bring_working_groups_up_to_date`, and check that the changes didn't break render, or that Zola runs.
> Bring Contributing Guide Working Groups Documentation Up to Date

- content/learn/contribute/helping-out/opening-pull-requests.md
- content/learn/contribute/helping-out/reviewing-pull-requests.md
- content/learn/contribute/project-information/bevy-organization.md
- content/learn/contribute/reference/triage.md
Centralize, and add back missing, PR merging rules to the Contributing Guide.
Put the four merging rules in the Reviewing Pull Requests page under How Pull Requests are merged. Deduplicate partial mentions of these rules, and instead direct to this section as a single source of truth.
Run `zola serve --open` on the `trialdragon/clarify_pr_merge_rules` branch, and check that the changed areas render correctly, and that Zola does indeed run.
> Clarify PR Merging Rules in Contributing Guide

- content/learn/contribute/project-information/release-process.md
mostly adds a shell script so that I don't miss PRs when cherry picking a milestone
> better documentation for patch releases

- content/news/2024-09-10-dream-job/index.md
The current deploy 404s, this fixes it using Zola's newer [internal linking symbol](https://www.getzola.org/documentation/content/linking/) that grabs the specific file.
> Fix internal link to birthday post

- content/learn/contribute/helping-out/opening-pull-requests.md
- content/learn/contribute/reference/triage.md
Currently it's not clear if PRs up for adoption should be closed or left opened until they are adopted. Both cases have happened.
I propose to change it to close by default, open a tracking issue, and claim the issue when you are working on it.
I propose to review X-Controversials after 6 months of inactivity: after such a delay, we should be able either to tell if nobody cares about it anymore (then close it), or take a final decision instead of leaving it hanging.
I propose a new status `S-Needs-Help` to mark PRs that could use help to resolve conflicts, pass CI and so on. Working on this PRs either with the original author or one of the maintainers to add commits and get it merged.
> few improvements in process to help close PRs

- .github/workflows/ci.yml
- content/foundation/meeting-minutes/actions-without-meeting/index.md
This page was [missing the `date` field](https://github.com/bevyengine/bevy-website/actions/runs/11250795257/job/31280424360), as helpfully pointed out by @TrialDragon. I filled it out based off the merge date of #1628.
While I was there, I also added the author field, since it was missing.
This will not fix the website not deploying, since there's an issue with the donation page, but it will silence the only other warning.
> Fix warning on `actions-without-meeting` minutes

- config.toml
- templates/sponsors.html
Public HTML comments have been converted to private so that they are not displayed over and over again in the loop and thus fill up the entire HTML.
Also written into the config that the HTML is minified by default.
> Changed public to private comment and minifyed HTML

- templates/donate.html
This is no longer relevant on this page, as we default to every.org.
> Remove corporate stripe note

- content/learn/contribute/reference/triage.md
The existing use of `C-` for release notes / breaking changes was confusing and inconsistent. I've added a new `Meta` category over on `bevy` with its own color! This PR updates the contributing guide to reflect the changes.
> Add Meta category to triage scheme

- Cargo.lock
- content/learn/contribute/helping-out/how-you-can-help.md
- content/learn/contribute/project-information/release-process.md
- generate-release/Cargo.toml
- generate-release/README.md
- generate-release/src/migration_guides.rs
- generate-release/src/release_notes.rs
- release-content/0.14/migration-guides/_guides.toml
- release-content/0.14/release-notes/_release-notes.toml
- sass/pages/_migration_guide.scss
- templates/shortcodes/migration_guides.md
- templates/shortcodes/release_notes.md
Fixes #1354
Fixes #1350 I believe
Adds support for Meta category labels to the `generate-release` tool solving https://github.com/bevyengine/bevy-website/pull/1646#issuecomment-2407903312
This PR aims to make the release notes and migration guides generators easier to use with merged release notes, and edited release notes. (Also, overall improving the tool in slight ways as I go along, by accident).
It now tracks whether a PR exists by the release note and migration guide metadata, and allows for multiple PRs per a note or guide, and PR URLs per note or guide. It should only ever create a file if a PR is not included in any notes or guides metadata, so no more overwriting note files or note or guide metadata if it isn't a new PR as far as the generator is concerned. If a release note or …
> Improve `generate-release` workflow involving editing and merging notes and guides

- sass/components/_contributors.scss
- sass/site.scss
- templates/shortcodes/contributors.md
Change `contributors.md` shortcode styling so it shows contributors in columns. The number of columns will automatically change based on the available space:
> Change contributors shortcode styling so it's more compact

- templates/sponsors.html
The change ensures that if a donor's name is not provided, the `alt` attribute for the donor's logo will use the filename (without the extension) as the alternative text.
* [`templates/sponsors.html`](diffhunk://#diff-d8ee107f524a55dc818ad29b30faf95d6f235424d7b12a83a874d24971fd1777R76-R77): Added a fallback for the `alt` attribute to use the donor's logo filename if the donor's name is not available.
> Write in a alternative logo-title if name is not given

- release-content/0.15/release-notes/14791_Required_Components.md
- release-content/0.15/release-notes/_release-notes.toml
While investigating #1724, I re-ran the tool. It only found the require components PR, which I've added the release notes label to after running the tool the first time.
We might as well add the stub for it now though.
> Add stub for required components

- release-content/0.15/release-notes/13889_Make_Tasks_functional_on_WASM.md
- release-content/0.15/release-notes/14316_Fast_renormalize.md
- release-content/0.15/release-notes/14703_Use_docfake_variadic_to_improve_docs_readability.md
- release-content/0.15/release-notes/14863_Expose_bevy_math_ops.md
- release-content/0.15/release-notes/14964_Migrate_bevy_transform_to_required_components.md
- release-content/0.15/release-notes/15341_Add_UI_GhostNode.md
- release-content/0.15/release-notes/_release-notes.toml
I've only tackled the ones that don't warrant release notes at all, rather than attempting to merge them.
1. Closes #1710.
2. Closes #1699.
3. Closes #1676.
4. Closes #1672.
5. Closes #1664.
6. Closes #1660.
> Remove unwarranted release note stubs

- release-content/0.15/release-notes/15419_Gpu_readback.md
> Gpu readback

- release-content/0.15/release-notes/15281_Add_core_and_alloc_over_std_Lints.md
First draft of the `no_std` release notes. The PR itself is only a couple of lints, but it's more about what work we can undertake now that this first step has been taken, so I focussed more on that.
> Update #15281 Release Notes for 0.15 (no_std)

- content/learn/migration-guides/0.14-to-0.15.md
Once this is merged, the page will be hidden as a public_draft as long as https://github.com/bevyengine/bevy-website/issues/1741 remains open.
> Create public draft for 0.15 migration guide

- release-content/0.15/migration-guides/14387_Deprecate_is_playing_animation.md
- release-content/0.15/migration-guides/_guides.toml
Pretty sure all I need to do is remove these two things, but let me know if this isn't the right way to remove this from the migration guide.
Refs https://github.com/bevyengine/bevy/pull/16121
> Remove deprecate is_playing_animation release notes

- content/learn/contribute/project-information/release-process.md
add some helper scripts that I wrote for the 0.15 rc:
* script to check that all crate docs are correctly built on docs.rs
* script to merge all the merged PRs from a milestone to a branch that are not already on that branch
* also increase the number of PRs queried in the patch script for the day we have more than 30 PRs in a patch
> Scripts for rc

- content/learn/migration-guides/0.10-to-0.11.md
- content/learn/migration-guides/0.11-to-0.12.md
- content/learn/migration-guides/0.12-to-0.13.md
- content/learn/migration-guides/0.9-to-0.10.md
- generate-release/src/migration_guides.rs
- release-content/0.14/migration-guides/_guides.toml
- sass/pages/_content.scss
- sass/pages/_migration_guide.scss
- templates/shortcodes/migration_guides.md
- Change `migration_guides.rs` so that it generates sorted `_guides.toml` each time
- Add area sections in migration guides and improve styling
https://github.com/user-attachments/assets/c45dc82e-2360-4f3a-923d-18ac1b021945
> Sort migrations by area and improve styling

- release-content/0.15/release-notes/14838_bevy_reflect_add_Type_type.md
- release-content/0.15/release-notes/_release-notes.toml
`Type` was added in this PR: https://github.com/bevyengine/bevy/pull/14838
> Add release note for `Type`

- release-content/0.15/release-notes/15475_bevy_reflect_Generic_parameter_info.md
- release-content/0.15/release-notes/_release-notes.toml
- release-content/0.15/release-notes/type_info_improvements.md
Fixes #1705
I chose to group a collection of `TypeInfo` improvements here:
- [#15475: bevy_reflect: Generic parameter info](https://github.com/bevyengine/bevy-website/issues/1705)
- [#13321: bevy_reflect: Nested TypeInfo getters](https://github.com/bevyengine/bevy/pull/13321)
- [#13320: bevy_reflect: TypeInfo casting methods](https://github.com/bevyengine/bevy/pull/13320) (with a brief mention of [#15235: bevy_reflect: Add ReflectRef/ReflectMut/ReflectOwned convenience casting methods](https://github.com/bevyengine/bevy/pull/15235))
> Added release note for `TypeInfo` improvements

- release-content/0.15/release-notes/5772_bevy_reflect_Add_Reflectable_trait.md
Fixes #1687
I chose not to include a code snippet here as I didn't think it was particularly interesting to show `T: Reflect + GetTypeRegistration + Typed + TypePath` -> `T: Reflectable`, but let me know if it would be better with an example!
> Add 0.15 release notes for `Reflectable`

- release-content/0.15/release-notes/6042_bevy_reflect_Reflect_remote_types.md
> Add 0.15 release notes for remote reflection

- release-content/0.15/release-notes/13818_Created_an_EventMutator_for_when_you_want_to_mutate_an_eve.md
- release-content/0.15/release-notes/_release-notes.toml
Fixes #13818. @BobG1983, can I get your review here?
> Event mutator release notes

- release-content/0.15/release-notes/14646_feat_add_insert_if_new_14397.md
- release-content/0.15/release-notes/_release-notes.toml
Closes #1675. Closes #1732.
As the linked PR discusses, it's quite hard to motivate this API with the removal of first-party bundles and generally deprioritization of the pattern.
I still think the API is useful to have in Bevy, but it's gone from "very helpful" to "niche" with the required components changes, and I don't think it warrants a release note.
> Remove insert_if_new release notes

- release-content/0.15/release-notes/12770_Implement_gamepads_as_entities.md
- release-content/0.15/release-notes/_release-notes.toml
Fixes #1700.
This PR directly adapts the example by @s-puig in https://github.com/bevyengine/bevy/pull/12770 to demonstrate the new API, and the ergonomic improvements over the previous one. Thanks!
> Gamepads as entities release notes

- release-content/0.15/release-notes/14269_Basic_isometry_types.md
- release-content/0.15/release-notes/_release-notes.toml
Closes #1656.
Add release notes for the shiny new isometry types! Feel free to help cut this down if it's too long.
Also let me know if I should change the authors in some way. I of course kept mweatherley as the primary author for originally adding these types in https://github.com/bevyengine/bevy/pull/14269 and adding conversions to/from `Transform`, but I also added myself as a secondary author for fleshing out the docs, adding several helpers, making gizmo and bounding APIs nicer with `Into` conversions, and helping out in reviews.
> Add 0.15 release notes for isometries

- content/news/2024-??-??-bevy-0.15/index.md
Apparently this stub didn't exist yet! I needed this for #1730, and it's cleaner to ship this as its own PR.
When reviewing, please be *very* sure that I didn't screw up the draft status of the post.
Sections marked TODO are, you know, still to be done. I've used a consistent symbol so we can easily double check before publication.
> Add stub for Bevy 0.15 release blog post

- release-content/0.15/release-notes/14791_Required_Components.md
- release-content/0.15/release-notes/15269_Allow_a_closure_to_be_used_as_a_required_component_default.md
- release-content/0.15/release-notes/15458_Runtime_required_components.md
- release-content/0.15/release-notes/_release-notes.toml
> 0.15 Release Notes: Required Components

- release-content/0.15/release-notes/14848_Improved_text_batching.md
- release-content/0.15/release-notes/_release-notes.toml
As discussed in #1722, these no longer warrant a release note due to the additional performance-impacting changes.
> Remove text batching release notes

- release-content/0.15/migration-guides/15756_Type_safe_retained_render_world.md
I notice Lommix found the lack of a `RenderVisibleEntities` note in the migration guide [confusing](https://discord.com/channels/691052431525675048/1306210871877566475). Not sure if I've captured it correctly here, please tweak as required.
> Mention RenderVisibleEntities

- sass/components/_bevy-instance.scss
Before this PR the behavior was:
- the progress bar HTML is visible by default
- the progress bar JS shows the progress bar when it starts loading an asset and hides the progress bar when it finishes the loading
The problem is that some examples don't have any asset so they don't run the JS script, hence the progress bar stays visible. This PR changes the default style for the progress bar to `hidden` to avoid this issue.
Fixes #1795.
> Hide example progress bar by default

- sass/pages/_content.scss
#1743 changed the default content font color in a way that significantly reduced contrast. The old color was a better default content color.
> Revert to old content font color

- release-content/0.15/migration-guides/14842_Replace_the_wgpu_trace_feature_with_a_field_in_bevy_render.md
When I initially wrote the migration guide for https://github.com/bevyengine/bevy/pull/14842, I was under the impression that it would be read and rewritten to better suit the migration guide.
However, I wasn't aware that there were tools being used to create the migration guides, much less that they would copy my migration guide verbatim.
Realizing this, I decided to rewrite this migration guide. I'm much happier with the result - though any feedback is welcome!
P.S. Thanks to @TrialDragon for teaching me how to make a note callout!
> Rewrite the migration guide for PR 14842

- release-content/0.15/release-notes/15260_Added_HeadlessPlugins_15203.md
- release-content/0.15/release-notes/_release-notes.toml
This was tackled a different way in https://github.com/bevyengine/bevy/pull/16401, and probably doesn't warrant a release note in its current form.
Closes #1689.
> Behead Headless Plugins release notes

- release-content/0.15/release-notes/13014_Dedicated_Reflect_implementation_for_Setlike_things.md
- release-content/0.15/release-notes/_release-notes.toml
Write the section mentioned in #1665
> 0.15 Release Notes: `Set` Reflection

- release-content/0.15/release-notes/13991_Minimal_Bubbling_Observers.md
- release-content/0.15/release-notes/_release-notes.toml
Fixes https://github.com/bevyengine/bevy-website/issues/1657.
> Bubble and trouble: release notes for bubbling observers

- release-content/0.15/release-notes/15614_Allow_Worldentity_family_of_functions_to_take_multiple_ent.md
> Release notes for #15614: Allow World::entity family of functions to take multiple entities and get multiple references back

- content/learn/quick-start/introduction.md
It was https://github.com/bevyengine/bevy/blob/main/CONTRIBUTING.md, before, but the contributing information is now on the actual bevy website (https://bevyengine.org/learn/contribute/introduction). Changed the hyperlink to that.
#1549
> Changed the contributing link

- release-content/0.15/release-notes/14920_Add_cached_run_system_API.md
- release-content/0.15/release-notes/15276_Reduce_runtime_panics_through_SystemParam_validation.md
- release-content/0.15/release-notes/15800_Add_mesh_picking_backend_and_MeshRayCast_system_parameter.md
- sass/pages/_news.scss
- templates/shortcodes/release_notes.md
This improves release note style and functionality in a number of ways:
1. We now link to author github profiles when in the form `@X` 
1. Prefers single-line formatting. This was particularly heinous with new lines for each PR
2. Harmonize "pr" and "author" formatting
2. Group prs under a single "PRs" section, rather than labeling each one `PR #1, PR #2, etc`
3. When breaking lines to run out of room, break by PR/Author section first
4. Makes section headings `##` instead of `###`. They were "too small" in their current form / the wrong section level
5. Reduces prominence of PR / Author sections by reducing font size and replacing blue link color with white
6. Reduced the space between the section heading and the author/pr section. This helps logically group them together / helps the …
> Improve release note styling

- release-content/0.15/migration-guides/15591_Text_rework.md
The data type appears to have been renamed since the guide was written
> TextUiWriter rename

- release-content/0.15/migration-guides/15320_Retained_Rendering.md
- release-content/0.15/migration-guides/15756_Type_safe_retained_render_world.md
- release-content/0.15/migration-guides/_guides.toml
Prompted by #1794, I noticed that we had two distinct sections for the migration guide that cover retained rendering. I've condensed those, and then done an editing pass.
> Revise and condense retained rendering migration guide

- release-content/0.15/release-notes/14630_A_Curve_trait_for_general_interoperation__Part_I.md
- release-content/0.15/release-notes/_release-notes.toml
Closes #1681.
We don't have a clear enough vision for color gradients by @RobWalt to write a full release note for them, but I've now mentioned them here.
The much larger changes here are making this release note approachable to the average game dev, who has high-school level math :) I've tried my best to keep precision while expanding on the context and toning down the jargon.
~~I've also added a paragraph clearly extolling the super cool easing work by @mockersf this cycle. I expect that for many users, this will be one of the most common and practical applications.~~ This already has its own section just below.
> Rewrite curves release note to be more approachable and add a brief note about color curves

- release-content/0.15/release-notes/14630_A_Curve_trait_for_general_interoperation__Part_I.md
I initially prepared to find and fix more typos but it seems there is only one, just a misplaced bracket
> Typos fixes and cleanup in curves release notes

- generate-release/src/helpers.rs
Partially `fixes` #1851
I think there still may be a bit of a mismatch because we only fetch PRs from a particular date range, or whatever. But this should at least help with the renamed PRs.
> Use PR number for matching commits to PRs in release/guide generator

- release-content/0.15/migration-guides/14082_AssetReader_read_now_returns_an_opaque_type.md
- release-content/0.15/migration-guides/15090_Deprecate_LoadAndSave_Asset_Processor.md
- release-content/0.15/migration-guides/_guides.toml
Fixes #1831, finally. These were just copied from the PRs responsible, but I did improve the title of the AssetReader one.
> Add final missing migration guides

- release-content/0.15/release-notes/15013_Implement_animation_masks_allowing_fine_control_of_the_tar.md
- release-content/0.15/release-notes/15282_Allow_animation_clips_to_animate_arbitrary_properties.md
- release-content/0.15/release-notes/15800_Add_mesh_picking_backend_and_MeshRayCast_system_parameter.md
* Pares down the picking example to its bare essentials
* Adapts property animation to use the changes in https://github.com/bevyengine/bevy/pull/16484
* Adds some clarity to the animation mask section
> 0.15 Editorial Pass 2

- content/news/2024-XX-XX-bevy-0.15/index.md
I noticed that these were inconsistent. I don't really care about which style we use, just that it's consistent. So I checked the 0.14 release notes and copied them.
I also reworded one bullet point about volumetric fog into one sentence for consistency and to reduce punctuation weirdness.
> Remove periods from release highlight bullet points

- content/community/links.toml
Link wasn't updated to the new handle so it linked to the old one.
> Update bluesky link to new handle

- release-content/0.15/release-notes/13991_Minimal_Bubbling_Observers.md
- release-content/0.15/release-notes/14099_Allow_volumetric_fog_to_be_localized_to_specific_optionally.md
Noticed a couple of missing links in the 0.15 release notes that showed up like this:
This PR adds all the missing links.
> Fix missing links in 0.15 release notes

- release-content/0.15/release-notes/_release-notes.toml
Noticed that two sections in the 0.15 release notes ended with a period. No other section title does that, so I figured I'd remove them because it looked a bit out of place.
> Remove periods from 0.15 release note titles

- release-content/0.15/migration-guides/15482_bevy_reflect_Add_ReflectDeserializerProcessor.md
- release-content/0.15/migration-guides/15591_Text_rework.md
- release-content/0.15/migration-guides/15898_Migrate_UI_bundles_to_required_components.md
- release-content/0.15/migration-guides/_guides.toml
- sass/pages/_content.scss
- Move migrations that were at the bottom to their respective areas
- Add missing `</details>`
- Change some migration headings to `<h4>`
- Improve `<h4>` styling so it's more prominent than regular text
> Fix migration guides issues

- release-content/0.15/migration-guides/13859_Change_SceneInstanceReady_to_trigger_an_observer.md
- release-content/0.15/migration-guides/14416_feat_Add_Worldget_reflect_and_Worldget_reflect_mut.md
- release-content/0.15/migration-guides/14842_Replace_the_wgpu_trace_feature_with_a_field_in_bevy_render.md
- release-content/0.15/migration-guides/15281_Add_core_and_alloc_over_std_Lints.md
- release-content/0.15/migration-guides/15666_Split_out_bevy_mesh_from_bevy_render.md
- release-content/0.15/migration-guides/_guides.toml
This is just barely scratching the surface to fix some low hanging fruit.
- 13859: The formatting in this one was really messed up
- 14416: No breaking changes, removed.
- 14842: Used callout shortcode that doesn't work here
- 15281: I think this is outdated, and is covered by general warning at top of page, removed.
- 15666: `bevy_render` -> `bevy::render` for user code. Hopefully a little less confusing now too
> Various migration guide fixes

- release-content/0.15/migration-guides/15320_Retained_Rendering.md
- release-content/0.15/migration-guides/_guides.toml
This file was added earlier in #1786, but it was never actually included in the index.
Also adjusted the headings to be the correct level / one level smaller than PR titles.
> 0.15 migration: Fix missing retained rendering guide

- release-content/0.15/migration-guides/10193_Cosmic_text.md
> 0.15 migration: Fix name of subpixel feature that was removed

- generate-assets/src/lib.rs
Originally reported by @ChristopherBiscardi over on [discord](https://discord.com/channels/691052431525675048/745355529777315850/1312992286795370519).
`bevy_renet` is currently showing that it depends on Bevy 0.11, despite having recent releases depending on more recent versions of Bevy.
This seems to be due to a bug in the way we parse and sort version numbers in sql. The `patch` portion of the version number is being treated and sorted as a string. Here's the output of the relevant subquery for `bevy_renet` with the `LIMIT 1` removed, showing the incorrect sorting.
```
850228|MIT OR Apache-2.0|0|0|9
803802|MIT OR Apache-2.0|0|0|8
747658|MIT OR Apache-2.0|0|0|7
666460|MIT OR Apache-2.0|0|0|6
594323|MIT OR Apache-2.0|0|0|5
590568|MIT OR Apache-2.0|0|0|4
573573|MIT OR Apache-2.0|0|0|3 …
```
> Fix sorting of patch version numbers in crates.io metadata retrieval

- release-content/0.15/release-notes/13912_featgltf_add_name_component_to_gltf_mesh_primitive.md
Thank you for this amazing project. The blog is really interesting to read!
I found other typos earlier but didn't found this repository before and I cannot recall where they were.
> :pencil2: Fix "the this" typo

- static/on-this-page.js
Apply the header offset to `on-this-page.js` intersection observer. This way the sidebar will highlight the next section as soon as the old section gets below the header. [Previously it waited until exiting the viewport](https://github.com/bevyengine/bevy-website/pull/1907#issuecomment-2520945939).
Fixes #1908.
New behavior (header opacity reduced to 0.5 and yellow header **just for visualization**)
https://github.com/user-attachments/assets/e5b597e3-d13c-4609-a16f-82daa216aeb6
> Fix sidebar section highlighter

- sass/_utils.scss
Hide heading anchors (`#`) by default to reduce noise:
https://github.com/user-attachments/assets/c1b080a6-c53b-429d-9675-b7b94afa6db4
> Hide heading anchors by default

- sass/pages/_migration_guide.scss
- templates/shortcodes/migration_guides.md
Fixes a minor detail 😅. Right now Migration guides H3 headings have the `border-top` set. The problem is that when the user clicks on the sidebar links (or `#`) the scrolls aligns with the horizontal line because that's part of the heading.
The solution is to remove the `border-top` from the H3 heading and use `<hr>` instead, this way the scroll aligns with the text instead of the horizontal line.
Demo:
- First old behaviour
- Then this PR behaviour
https://github.com/user-attachments/assets/380a8c4d-6e74-4dee-bb06-0dcd0d07e563
> Use `<hr>` instead of `border-top` in Migration headings

- content/community/links.toml
- sass/components/_footer.scss
- templates/layouts/base.html
Links now come from `links.toml` so it's easier to maintain the footer list.
Styling changes:
- Smaller icons
- Change color of icons to grey (opacity 0.65); white on hover
- Replace gap with link padding so there isn't any "non-interactive gaps" between icons and increases icon link "hit-area"
- Increased footer vertical padding
- Added CSS transition to scale/opacity
https://github.com/user-attachments/assets/dfd5f513-7228-48d8-813a-6475f5f6d007
Fixes #1867. Fixes #1866.
> Add Bluesky link in footer and tweak styling

- templates/macros/header.html
I added a trailing slash to the URL to avoid GitHub Pages' automatic redirect from slashless URLs.
The redirection process incurs an additional HTTP request on each menu load, marginally impacting the page load time.
> add slash to route

- static/assets.js
- templates/assets.html
- templates/layouts/examples.html
Since the beginning the website has favored non-JS solutions when possible. But there are features than can only be implemented with JS. For those users that have JS disabled in their browser we shouldn't show these features.
**This PR hides assets/examples filters to non-JS users.**
To try this in Firefox:
- Go to: `about:config`
- Set `javascript.enabled` to `false`
- Navigate to assets/examples, you shouldn't see the filters
> Hide assets/examples filters to non-JS users

- config.toml
- sass/components/_example.scss
- sass/components/_tabs.scss
- sass/site.scss
- syntaxes/WGSL.sublime-syntax
- templates/layouts/example.html
- Adds tabs in the example page (they also work with keyboard once focused)
- Adds `tabs` BEM _component_
- Adds `.wgsl` syntax highlighter. It's using https://github.com/relrelb/sublime-wgsl/tree/main which is an [outdated version of this](https://github.com/PolyMeilex/vscode-wgsl/blob/master/syntaxes/wgsl.tmLanguage.yml). If someone is willing to convert the VSCode version to the Sublime format apparently there is a way of doing it within Sublime, but I couldn't make it work.
(ignore the changing cursor, it's because of my screen recorder)
https://github.com/user-attachments/assets/0f91e339-8b5d-4a76-87fb-60c44ec559a1
> Use tabs for examples code

- release-content/0.15/migration-guides/16163_Dont_reëxport_bevy_image_from_bevy_render.md
- release-content/0.15/migration-guides/_guides.toml
This change resulted in some pretty weird-looking breakage and deserves a bit of love. Some of Bevy's examples used these re-exports, so they are likely to be in other codebases.
The list of types was gleaned from changes to Bevy code / examples from the original PR.
> 0.15 migration: Fix up guide for 16163

- content/learn/contribute/helping-out/opening-pull-requests.md
There's some pretty funky stuff going on in [this document](https://bevyengine.org/learn/contribute/helping-out/opening-pull-requests/#contributing-code) with lists. The "Contributing Code" section in particular is written as a nested numbered list, but the second layer of nesting is not really a series of numbered steps. One of them only has one "sub step."
This PR:
- Flattens some numbered sub-lists into sub-paragraphs.
- Marks the fast-compiles steps as optional (I wouldn't mind deleting this step though)
- Does some other misc tidying in the `Contributing Code` section
- Expands the content in the adoption section, hopefully hitting the main points of https://github.com/bevyengine/bevy/issues/12160 without going too crazy.
Here's a before / after for the number list formatting.
> Fix up list formatting and expand adoption section in contributing guide

- templates/sponsors.html
Tidy up this section of the tera template.
The output should be identical, except without the space between names and the following comma.
- Replace manual array filtering with `filter` filter
- Replace manual array index tracking with `loop`
- Get rid of pesky space between names and comma
- Replace spaces in names with non-breaking spaces so they don't get split onto two lines.
> Tidy up "past sponsors" markup

- content/learn/contribute/introduction.md
Both of these were missing, but should be much more prominently linked due to how helpful they are.
> Link dev docs and example runner in Contributing Guide

- content/learn/contribute/reference/triage.md
While adding the S-Nominated-To-Close tag in another PR, I noticed that S-Ready-For-Implementation was one of the most common labels.  While it's probably pretty straightforward without explanation, I felt this might be a good call to action (which is why I added it to the top of the list).
> Add S-Ready-For-Implementation to triage docs

- content/learn/quick-start/plugin-development.md
Document where to find information for plugin development now that Bevy includes `no_std` support.
Added a small section on `no_std` compatibility to _Plugin Development_ calling out that developers either want to just enable the `std` feature in Bevy if they have to, _or_ consider reading the `no_std/library` example for details on how to potentially make their plugin `no_std` compatible.
---
- I wasn't sure how best to link to an example, would love some feedback on that point in particular!
- I _could_ migrate some of the information out of the example itself and into the development guide directly, but I think it's cleaner to keep the somewhat niche information in its own area.
> Add `no_std` section to Plugin Development

- release-content/0.16/release-notes/14780_Link_iOS_example_with_rustc_and_avoid_C_trampoline.md
- release-content/0.16/release-notes/15607_Track_callsite_for_observers__hooks.md
- release-content/0.16/release-notes/15858_Introduce_methods_on_QueryState_to_obtain_a_Query.md
- release-content/0.16/release-notes/16047_track_change_detection_Also_track_spawnsdespawns.md
- release-content/0.16/release-notes/16434_Getting_QueryState_from_immutable_World_reference.md
- release-content/0.16/release-notes/16575_Move_required_components_doc_to_type_doc.md
- release-content/0.16/release-notes/16758_Add_no_std_support_to_bevy_ecs.md
- release-content/0.16/release-notes/16795_Tab_navigation_framework_for_bevy_input_focus.md
- release-content/0.16/release-notes/16826_Extend_cloning_functionality_and_add_convenience_methods_t.md
- release-content/0.16/release-notes/16874_Add_no_std_support_to_bevy_app.md
- release-content/0.16/release-notes/17043_Add_Result_handling_to_Commands_and_EntityCommands.md
- release-content/0.16/release-notes/17258_Proportional_scaling_for_the_sprites_texture.md
- release-content/0.16/release-notes/17423_BRP_resource_methods.md
- release-content/0.16/release-notes/17482_Replace_Ambient_Lights_with_Environment_Map_Lights.md
- release-content/0.16/release-notes/17753_featecs_configurable_error_handling_for_fallible_systems.md
- release-content/0.16/release-notes/17967_Upgrade_to_Rust_Edition_2024.md
- release-content/0.16/release-notes/18017_allow_Call_and_Closure_expressions_in_hook_macro_attribute.md
- release-content/0.16/release-notes/18093_Transform_Propagation_Optimization_Static_Subtree_Marking.md
- release-content/0.16/release-notes/_release-notes.toml
This is the first crucial editing pass on the generated release notes. It's best reviewed commit-by-commit, as I've gone and done an organization pass by area at the very end to make it easier to find segments for now. Once the content is written we can do a proper editorial organization pass.
If you think one of the PRs that was cut is vital to talk about, make your case and I'll revert that commit if I agree.
> Cull, organize and sort release notes for 0.16

- content/learn/migration-guides/0.15-to-0.16.md
- content/news/2025-XX-XX-bevy-0.16/index.md
The critical thing to double-check is that I got public_draft usage right for the release note page.
> Generate stub root pages for release notes and migration guides for Bevy 0.16

- release-content/0.16/migration-guides/_guides.toml
Adds back-ticks to render some title text as `<code>`, otherwise the generics are interpreted as HTML elements.
> Add backticks to generics in 0.16 migration guides

- release-content/0.16/release-notes/17955_Add_no_std_support_to_bevy.md
- Fixes #2001
- I wasn't quite sure how to include an image in the release notes, and I'm not even certain we want to include a screenshot of one of my rather ugly examples running in an emulator!
- I've included links to some community crates as examples of adding `no_std` support in libraries. Not sure if there's a policy around not showing favour to particular 3rd party crates so I thought I'd call that out here.
- I've tried not to go into too much detail into how `no_std` itself works, just saying that having it lets your code work on more platforms.
- I did try to see if I could embed a WASM GameBoy Advance emulator, but it looked pretty non-trivial, and wasn't very polished.
> Add `no_std` Release Notes

- .github/workflows/build-wasm-examples.yml
- I want to be able to confirm building all examples in wasm work before updating the `latest` tag
- CI is updated to be able to target other tags/branches of the Bevy repo, and to publish to cloudflare only when needed
> can use CI to check if building all examples to wasm works before updating latest

- release-content/0.16/migration-guides/18555_Improved_require_syntax.md
- release-content/0.16/migration-guides/_guides.toml
- release-content/0.16/release-notes/18555_Improved_require_syntax.md
- release-content/0.16/release-notes/_release-notes.toml
Release notes and migration guide for https://github.com/bevyengine/bevy/pull/18555
Fixes #2026.
> #18555: Release notes and migration guide

- release-content/0.16/release-notes/13120_Add_DefaultQueryFilters.md
- release-content/0.16/release-notes/_release-notes.toml
I've opted not to include a code snippet: I think the verbal explanations were clearer and more concise.
Fixes #1982.
> Add release notes for default query filters and entity disabling

- release-content/0.16/release-notes/_release-notes.toml
While I led the `no_std` effort and authored all the relevant PRs, many other contributors were involved in the process. I've updated the release notes metadata to link to all the various PRs that (combined) added `no_std` support to `bevy`, and included all the contributors to those PRs (sorted alphabetically). I think that also better conveys the magnitude of the changes involved in getting `no_std` Bevy across the line.
> Give Proper Credit for `no_std` Support

- release-content/0.16/migration-guides/18421_Add_more_methods_to_RelationshipSourceCollection.md
- release-content/0.16/migration-guides/_guides.toml
The migration guide for #18421 does not apply for `bevy@0.15.3` to `bevy@0.16.0`, since it is for new methods in the trait `RelationshipSourceCollection`, which was added after 0.15.3.
Remove the unnecessary migration guide.
> Remove #18421 Migration Guide

- release-content/0.16/migration-guides/15481_Remove_labeled_assets_from_LoadedAsset_and_ErasedLoadedAss.md
- release-content/0.16/migration-guides/18013_Make_adding_a_subasset_label_return_a_result_for_if_there_.md
- release-content/0.16/migration-guides/_guides.toml
These were reverted in https://github.com/bevyengine/bevy/pull/18567.
> Remove migration guides for 15481 and 18013 which have both been reverted.

- release-content/0.16/release-notes/16778_Event_source_location_tracking.md
- release-content/0.16/release-notes/_release-notes.toml
> Release notes for "Better source location tracking"

- content/learn/quick-start/getting-started/setup.md
The previous link was redirecting to a page that has quite a lot of options (which only install Visual Studio IDE as far as I can see) but not an option to get the build tools installer. I'm changing this to the link provided in Rust's [getting started](https://www.rust-lang.org/learn/get-started) guide.
> Update MSVC build tools link

- sass/_vars.scss
- sass/elements/_table.scss
Fix light-mode table header colors.
**[Before](https://bevyengine.org/learn/migration-guides/0-15-to-0-16/#utils):**
**After:**
https://github.com/user-attachments/assets/a6354399-575f-4b44-9bc1-7b90b9ae0aff
> Fix light-mode table colors

- release-content/0.16/migration-guides/16894_Move_Name_out_of_bevy_core.md
- release-content/0.16/migration-guides/16897_Remove_bevy_core.md
- release-content/0.16/migration-guides/_guides.toml
- release-content/0.16/migration-guides/bevy_core_removed.md
`bevy_core` was entirely removed during the 0.16 development cycle, but its items were moved during several PRs. To aid in migration, these PRs should be combined.
- Combined the migration guides for PRs 16894 and 16897
- Directly compared `bevy_core@0.15.3` to `bevy@0.16.0-rc.2` using `docs.rs`
> Combine and  refine `bevy_core`  migrations

- release-content/0.16/migration-guides/18451_Get_names_of_queued_components.md
- release-content/0.16/migration-guides/_guides.toml
[18451](https://github.com/bevyengine/bevy/pull/18451) was (hopefully) the last breaking change of 0.16!
It was created after most migration guides were auto-generated, but this PR adds the migration guide for it.
> Write migration guide for 18451

- sass/_vars.scss
- sass/components/_button-square.scss
- sass/components/_tabs.scss
- sass/elements/_details.scss
- sass/pages/_migration_guide.scss
#1771 introduced the usage of [CSS Relative Colors](https://caniuse.com/css-relative-colors) but this feature is not **widely** available yet (even if it's part of the [2024 Baseline](https://web-platform-dx.github.io/web-features/)). This PR moves the relative colors computation from CSS to SASS.
Once CSS Relative Colors has **wide support** this PR should be reverted.
Fixes #1951
Fixes #1937
> Remove CSS Relative Colors usage

- release-content/0.16/migration-guides/17029_Refactor_hierarchyrelated_commands_to_remove_structs.md
- release-content/0.16/migration-guides/_guides.toml
bevyengine/bevy#17029 removed hierarchy-related struct-commands and recommended equivalent methods, and some of those methods were later changed by the big relations stuff. This updates them (and also adds a bit of another PR (bevyengine/bevy#16999) that didn't get a migration guide but seemed relevant).
~(EntityCommands doesn't actually have insert_children on main, but will with https://github.com/bevyengine/bevy/pull/18675)~ (It does now)
> Update methods in pre-relations hierarchy-related migration guide

- release-content/0.16/release-notes/17398_Relationships_nonfragmenting_onetomany.md
- release-content/0.16/release-notes/17521_Improved_Spawn_APIs_and_Bundle_Effects.md
- release-content/0.16/release-notes/_release-notes.toml
> 0.16 Release Notes: Relationships and Spawn APIs

- release-content/0.16/release-notes/16502_Multiple_box_shadow_support.md
- release-content/0.16/release-notes/_release-notes.toml
Close #1958. While a nice feature, I don't think it's essential enough to go into the release notes. It doesn't unlock anything fundamentally new or solve a critical flaw in bevy_ui.
> Delete multiple box shadows release note

- release-content/0.16/migration-guides/17398_Relationships_nonfragmenting_onetomany.md
The `Parent` component has been renamed to `ChildOf` but the migration guide `17398_Relationships_nonfragmenting_onetomany.md` still refers to `Parent`.
Relevant: https://github.com/bevyengine/bevy-website/blob/bf214ec9efda4b5e73fd69f6e81f26c62ea60c89/release-content/0.16/migration-guides/17427_Parent__ChildOf.md?plain=1#L1
> Replace deprecated `Parent` with `ChildOf` in relationships migration guide

- release-content/0.16/migration-guides/EntityCommands_apply_signature.md
- release-content/0.16/migration-guides/_guides.toml
Fixes #2067. I didn't notice any other migration guide issues to mention relative to Bevy 0.15.
> Migration guide for EntityCommands::apply

- templates/macros/base.html
The page name macro was still expecting the Contributors Guide section to be under "/contribute" and not "/learn/contribute" so the Guide had no page name, and thus no name in the mobile nav menu switches, nor in the page headers by the logo.
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
> Fix contributors guide page header message using wrong path

- content/learn/migration-guides/0.15-to-0.16.md
This is added so that folks who see the migration guide are not confused at a migration guide being out for an unreleased version, and so that folks know that it is a work in progress.
> Add release candidate warning to `0.15 to 0.16` migration guide

- release-content/0.16/migration-guides/_guides.toml
- release-content/0.16/migration-guides/panicking_closures.md
Covers the issue reported in https://github.com/bevyengine/bevy/issues/18778.
> Write migration guide for 2024 edition panicking closure inference regression

- content/learn/migration-guides/0.15-to-0.16.md
After chewing on it, this stood out to me as one of the more important / common breaking changes of the 0.16 cycle, so I figured we can declare it upfront.
> Add no_std to migration guide highlights

- release-content/0.16/release-notes/13120_Add_DefaultQueryFilters.md
- release-content/0.16/release-notes/14069_Add_support_for_specular_tints_and_maps_per_the_KHR_materi.md
- release-content/0.16/release-notes/16372_Add_Immutable_Component_Support.md
- release-content/0.16/release-notes/16810_Add_AssetChanged_query_filter.md
- release-content/0.16/release-notes/17096_Anamorphic_Bloom.md
- release-content/0.16/release-notes/17398_Relationships_nonfragmenting_onetomany.md
- release-content/0.16/release-notes/17559_Basic_UI_text_shadows.md
- release-content/0.16/release-notes/occlusion_culling.md
- release-content/0.16/release-notes/unified_error_handling.md
- release-content/0.16/release-notes/virtual_geometry_improvements.md
- Fixes #2082
Replaced the `dev-doc` links in release note files in the `release-content/0.16/release-notes/` directory.
> release-notes: replace all `dev-docs` links with 0.16 `doc.rs` links

- release-content/0.16/migration-guides/17447_Dont_reexport_EntityHashSet_and_EntityHashMap.md
- release-content/0.16/migration-guides/_guides.toml
Solves https://github.com/bevyengine/bevy/issues/18841
I also renamed the md file, since the name seems like a mistake to me.
I didn't test the md - should I compile the docs locally? Or is a review enough?
The 0.16 doesn't get any rust analyzer errors and go to definition works for it, and the 0.15 version compiles. (I didn't have a compiling 0.16 projects at hand)
> Update and rename EntityHashSet 0.16 migration section

- content/learn/migration-guides/0.15-to-0.16.md
Since we're no longer in the release candidate phase, this warning should be removed :)
> Remove release candidate warning in migration guide

- release-content/0.16/release-notes/_release-notes.toml
@Jondolf was a significant contributor to https://github.com/bevyengine/bevy/pull/17758, having worked largely on the [initial demo](https://github.com/Jondolf/bevy_docs_extension_demo/). He should be credited for his hard work! :)
> Mark Jondolf as co-author to docs trait tags PR

- .github/workflows/build-wasm-examples.yml
- .github/workflows/update-screenshots.yml
* screenshots workflow failed on dependency that doesn't exist anymore: https://github.com/bevyengine/bevy-website/actions/runs/14663792163/job/41153825762#step:5:71
* don't install it, it's the fix we did for the main repo
* Example wasm files are now too big to upload to cloudflare
* optimise for size even more
> Fix example workflows for screenshots and wasm

- release-content/0.16/migration-guides/16348_Remove_deprecated_component_reads_and_writes.md
- release-content/0.16/migration-guides/17233_If_there_is_no_movement_DragStart_is_not_triggered.md
- release-content/0.16/migration-guides/17605_Support_decibels_in_bevy_audioVolume.md
- release-content/0.16/migration-guides/17743_Fix_rounding_in_steps_easing_function.md
I've noticed that generated listing in the migration guides (`release-content/0.16/migration-guides`) doesn't reflect the newest migration guides supplied from the respective PR (e.g. after being edited by the author). 
I found several typos and table formatting that breaks when rendered on the bevy website.
Additional note: a TODO is still found in [Cold Specialization](https://bevyengine.org/learn/migration-guides/0-15-to-0-16/#cold-specialization). It might need additional guide, considering its size.
> Fix several typos on 0.15 to 0.16 migration guides

- Cargo.lock
- learning-code-examples/Cargo.toml
This way the code validation is updated and won't break if any new examples use 0.16 exclusive features (doesn't seem we had anything break in the quick start guide).
> Update learning code examples to use 0.16 for validation

- release-content/0.16/migration-guides/17029_Refactor_hierarchyrelated_commands_to_remove_structs.md
> fix: mis-rendered table

- Cargo.lock
- generate-assets/Cargo.toml
- generate-assets/src/lib.rs
Asset metadata retrieval currently fails for assets that use Rust 2024 edition with the following error:
```
GITHUB_TOKEN=xxx ./generate-assets.sh
```
```
(...)
Error getting metadata from root cargo file from github: TOML parse error at line 4, column 11
|
4 | edition = "2024"
|           ^^^^^^
data did not match any variant of untagged enum Inheritable
```
Update `cargo_toml`
Some tests in `generate-assets` fail, but they also fail on main in the same way. See #2121
> Fix metadata retrieval for assets using Rust 2024 edition

- .github/workflows/ci.yml
- generate-assets/src/lib.rs
- generate-errors/download_errors.sh
- generate-errors/generate_errors.sh
- learning-code-examples/README.md
- learning-code-examples/examples/quick-start/getting_started_v3.rs
- learning-code-examples/examples/quick-start/getting_started_v7.rs
- learning-code-examples/examples/quick-start/getting_started_v9.rs
- learning-code-examples/validate_examples.sh
Fixes #2121 
I also did the following:
* Add `test-crates` job that runs all tests in the workspace
* Remove `test-code-examples` as it is covered by the lint/check jobs
* Fix that the output of clippy was discarded when checking code examples, and fix the warnings
> Remove old failing tests from generate-assets and run tests in CI

- content/learn/quick-start/getting-started/ecs.md
"in to" is grammatically incorrect and should be changed. The placement of "up" is stylistic; I might even remove it. Thoughts?
>  break datatypes up in to -> break up datatypes into

- content/learn/contribute/helping-out/creating-examples.md
As Bevy grows and matures, the need for better documentation grows with it. While we've gotten our API-focused documentation to a fairly good state with our existing examples + rustdoc, that only answers the "what does this API do?" question.
Users, especially experienced game developers, will commonly ask "how do I a specific task in Bevy", and will come up empty-handed. Instead, they're told to read or community-maintained resources, ask questions in our community spaces,or just "figure it out". While these can be excellent strategies, they're inefficient, commonly outdated, and are a missed opportunity to showcase how simple and effective a lot of these common tasks are in Bevy.
I've opted to build on the excellent work by @fallible-algebra over in #1949 to propose a new category of …
> Create "usage examples" category of first-party Bevy examples

- templates/layouts/example.html
This adds a warning-type callout to the example pages, if the browser detects that JavaScript is disabled for one reason or another. This callout is between the header (which says the name of the example) and the canvas showing the example.
A couple thoughts:
* I thought about linking to a resource on how to enable javascript, but I'm unsure if it's wanted.
* I thought about putting the warning inside the canvas (similar to how the loading bar does), but I'm proficient enough with CSS to understand how to do that - plus, I don't know how to ensure it looks nice on mobile (or how to test on mobile, for that matter).
* Yes, the `<aside>` tag used is copied from the callout below the canvas. I'm lazy, and it works anyways. :P
In any case, I'm satisfied with the result thus far. So I'm …
> Add a callout to the example pages if JavaScript is disabled

- content/learn/book/storing-data/entities-components.md
The .insert() api hasn't been needed for a while and is not used in this example
> Yeet mention of .insert

- content/learn/quick-start/getting-started/setup.md
Regarding `resolver` in virtual workspaces: Bevy with default plugins runs for me regardless of value, but cargo will warn and default to `resolver = "1"` if none is specified.
```
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2024 which implies `resolver = "3"`
note: to use the edition 2024 resolver, specify `workspace.resolver = "3"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
```
> Update setup guide Rust edition to 2024

- content/learn/book/storing-data/local-system-param.md
This page wasn't particularly helpful in explaining why these exist, and its information about defaults was wrong. I've opted for a complete (but still brief) rewrite.
> Rewrite Local page

- content/learn/book/intro/the-three-letters.md
The wikipedia link is invalid, add the missing `e`
> Fix typo in wikipedia link

- content/learn/book/storing-data/local-system-param.md
Copying out of the local fails with a compiler error. Even if we "fix" that by making `NoGoodDefaultValue` `Copy`, it fails to modify the local - only modifying the copy.
We need to turn the option into an `Option<&mut _>` option before attempting to unwrap it.
See [comment on the PR that introduced this](https://github.com/bevyengine/bevy-website/pull/2173#discussion_r2191066505) for slightly more detail, also for the [alternative proposal](https://github.com/bevyengine/bevy-website/pull/2173#discussion_r2190535621) (to use `get_or_insert_with`) that I prefer but was previously rejected.
> Don't try to copy out of `Local` system param.

- content/learn/book/releasing-projects/profiling.md
[bevyengine/bevy/docs](https://github.com/bevyengine/bevy/blob/main/docs/) should not exist 😩 Please, I just want to have all of our documentation in a clear home. 
One of the only important bits in there is the [profiling docs](https://github.com/bevyengine/bevy/blob/main/docs/profiling.md). I've started by copying it over directly, without editing beyond cutting the redundant table of contents. It could use some love and I'd like to crosslink it, but "simply copy it over" is easy tor review.
> Port profiling docs to the new book

- release-content/0.16/migration-guides/18555_Improved_require_syntax.md
There were unbalanced brackets
> Fix typo in 18555_Improved_require_syntax.md

- content/learn/book/control-flow/systems.md
- content/learn/book/the-game-loop/fixed-time.md
- content/learn/book/the-game-loop/time-and-timers.md
Some notes for reviewers:
- I've opted not to try and explain how to do delayed actions, waiting for a fix via https://github.com/bevyengine/bevy/issues/15129
- the lack of first-party interpolation seriously sucks (see https://github.com/bevyengine/bevy/issues/1259), but it's important to call out the problem. I've opted to lay out the broad shape of the solution, and hint "go look for `bevy_transform_interpolation`" without drawing controversy by straight-up linking it
> Add book page on time, fixed time and timers

- generate-assets/src/bin/generate.rs
- generate-assets/src/lib.rs
- sass/components/_asset-card.scss
- templates/macros/assets.html
Related to https://github.com/bevyengine/bevy-assets/pull/552.
See also, related [discord discussion](https://discord.com/channels/691052431525675048/695741366520512563/1410673856561021038).
This is super basic, without any way of disabling the blur.
Tested locally in FF/Chrome on macOS.
Requires a followup PR to add `nsfw=true` to that specific `toml` in the `bevy-assets` repo.
> Add blur for assets with nsfw=true

- static/assets/bevy_logo_light_dark_and_dimmed.svg
This logo is used in docs, but markdown link doesn't work from outside of the Bevy repo.
Add it to the website so we can have an URL for it
> add Bevy dimmed logo to the website

- content/learn/quick-start/getting-started/_index.md
Was brought to my attention by #2230 that https://github.com/bevyengine/bevy/issues/20475 had happened and that our current quick start instructions for running the examples currently breaks, or could break if someone used a version prior to 0.17.
Add a warning that the examples are broken on versions 0.16.x and earlier when ran with Rust 1.89 and later and give workarounds for this issue for those using 0.16.x and earlier.
> Add warning about 0.16.x and earlier examples in quick start guide

- content/learn/migration-guides/0.16-to-0.17.md
Fixes https://github.com/bevyengine/bevy/issues/21194, fixes https://github.com/bevyengine/bevy/issues/21041.
Adopts work by @janis-bhm that was originally opened on https://github.com/cart/bevy-website/pull/10.
> Add more migration guides for Bevy 0.17

- content/learn/migration-guides/0.16-to-0.17.md
bevyengine/bevy#20163 made breaking changes, as noted in bevyengine/bevy#21228.  
Add a migration guide for those changes.
> Migration guide for changes to optional access and default query filters

- syntaxes/LICENSE-RON
- syntaxes/README.md
- syntaxes/RON.sublime-syntax
As Zola does not support RON out of the box, this PR adds RON syntax definitions from <https://github.com/ron-rs/sublime-ron> and its corresponding Apache-2.0 license. I also created `README.md` that describes the purpose of the `syntaxes` folder and gives proper credit to the syntax definitions we have.
Fixes #2258.
From <https://bevy.org/learn/migration-guides/0-14-to-0-15/#use-fromreflect-when-extracting-entities-in-dynamic-scenes>
> Support highlighting RON syntax

- content/learn/migration-guides/0.16-to-0.17.md
As [noticed](https://discord.com/channels/691052431525675048/1404237363550486751/1422544673523630150) on [Discord](https://discord.com/channels/691052431525675048/1404237363550486751/1422685434504282334), the heading levels in the 0.17 migration guide are slightly messed up.
This PR fixes these issues with the following rules:
- Individual migration guides have level 3 headings (`###`)
- These are the sections that each have their own `{{ heading_metadata(prs=[...]) }}`, and represent a distinct set of PRs.
- Subsections within a migration guide have level 4 headings (`####`)
- Sub-subsections within a migration guide have level 5 headings (`#####`)
- Sub-sub-subsections within a migration guide don't exist and can't hurt you  <img width="24" height="29" alt="image" …
> Fix indentation of headings in 0.17 migration guide

- content/learn/migration-guides/0.16-to-0.17.md
Simple fix. Tripped on this while migrating some game logic.
> Replace `On::original_entity()` in migration guide with `On::original_event_target()`
