bevyengine/bevy-website

content/learn/book/getting-started/setup/_index.md
This commit resolves #6 
A commit on the main bevy repository has [already been submitted](https://github.com/bevyengine/bevy/pull/161) to create the linked document.
=> Adds OS dependencies section to Setup

content/news/2020-08-10-introducing-bevy/index.md
Added `mut` to `position` in relation to [this issue.](https://github.com/bevyengine/bevy/issues/123)
=> Fix broken code example

content/learn/book/getting-started/queries/_index.md, content/learn/book/getting-started/resources/_index.md
The code in the tutorial didn't compile anymore because the Timer::from_seconds() method needs two arguments to work. So I rewrote the code to work with the new version of the Timer::from_seconds() method.
=> Updated code in the tutorial

sass/_book.scss
=> Added min-width to book-content class

content/learn/book/getting-started/setup/_index.md
Update the bevy version in the dependencies of the Cargo.toml part.
=> Update version in setup

templates/base.html
=> Small update on base.html

content/learn/book/getting-started/troubleshooting/_index.md
In particular with the solution to the issue https://github.com/bevyengine/bevy/issues/509
=> Added troubleshooting section to "Getting Started"

content/learn/book/contributing/code/_index.md
As per https://github.com/bevyengine/bevy/pull/1309
=> Fill out the 'Contributing Code' page.

content/learn/book/contributing/code/_index.md
=> Update 'cargo fmt' command to match updated ci

.github/workflows/rebase.yml
this should enable bevy organization members to rebase pull requests automatically by commenting with `/rebase`.
=> add rebase action

content/news/2020-08-10-introducing-bevy/index.md
Inspired be a recent comment in discord
> are pages like this up-to-date with the latest releases? https://bevyengine.org/news/introducing-bevy/
But I have personally, in my early days with bevy, done something like
- Remember "hm, bevy can do ___ right? I think I read that somewhere"
- Googled "bevy ___"
- Stumbled on this post, and not immediately realize it's talking about a very old version of bevy.
Not a big issue obviously, opening this in case there's agreement. (And I was curious about zola)
=> Make this post more clearly historical for folks coming in from google

content/learn/book/contributing/code/_index.md
Update CI documentation corresponding to https://github.com/bevyengine/bevy/pull/1508#pullrequestreview-605710015
=> Update local CI instructions

content/learn/book/getting-started/_index.md, content/learn/book/getting-started/ecs/_index.md, content/learn/book/getting-started/resources/_index.md, content/learn/book/getting-started/setup/_index.md
Updated for 0.5! Please review to try and catch issues before our new users do :p
Style-wise, I'm not sure I prefer `commands.spawn_batch()` over `commands.insert().insert()` for the initial Hello World example. Let me know your preferences and we can change it.
=> Update Book for 0.5

content/learn/book/getting-started/ecs/_index.md
command chaining doesn't work with the new API
=> fix entity spawning

content/learn/book/migration-guides/0.4-0.5/_index.md
Hopefully this will reduce the number of people who hit [#1847](https://github.com/bevyengine/bevy/issues/1847).
=> Document the changes to `State`.

content/learn/book/migration-guides/0.4-0.5/_index.md
I ran into this when upgrading and it wasn't obvious what was wrong.
=> Add gltf loading change to migration guide

content/learn/book/getting-started/resources/_index.md
Tupled type GreetTimer needs `.0` to access `Timer.tick`
=> minor fix to timer resource example so it compiles

templates/community.html
=> Remove protocol from itch url in subtitle for consistency

content/learn/book/migration-guides/0.4-0.5/_index.md
A project I am working got hit by an ambiguous system ordering issue; adding this here to help out the next person :)
cc @alice-i-cecile
=> Mention system ordering behavior in 0.4-0.5 migration guide

README.md
Borrowed from https://bevyengine.org/learn/book/contributing/docs/
=> Add instructions on running the site locally

content/learn/book/getting-started/setup/_index.md
Explain how it can be added, and that it should be removed before
releasing the final game.
Fixes https://github.com/bevyengine/bevy/issues/2102.
=> Show how to set feature "dynamic" in the Cargo.toml

templates/book-macros.html
Fixes #153.
https://user-images.githubusercontent.com/29580620/119469437-a5632d00-bd47-11eb-8159-a2b9553f7eac.mov
=> Add section folding in Book

templates/shortcodes/file_code_block.html
=> allow anchors in file code block

README.md
Fixes the numbered list nesting not working.
=> readme: fix steps list nesting

generate-assets/src/lib.rs
needed for https://github.com/bevyengine/awesome-bevy/pull/105
=> ignore .github folder when generating assets

templates/assets-macros.html, templates/assets.html
for https://github.com/bevyengine/bevy-assets/issues/112
assets that are not in a subcategory will now be displayed
=> display assets on parent categories

templates/assets.html
as noticed in https://github.com/bevyengine/bevy-website/pull/173#issuecomment-857058445
=> assets - do not display empty div when no pages in section

config.toml, sass/_syntax-theme.scss, sass/site.scss
Adds a new custom css syntax theme tweaked to my preferences with much improved rust-specific highlighting.
=> Improved syntax highlighting

sass/_syntax-theme.scss
=> shell syntax theme improvements

.github/workflows/deploy.yml
=> add rust wasm target

.github/workflows/deploy.yml
=> fix order of actions

content/learn/book/getting-started/ecs/_index.md, content/learn/book/getting-started/plugins/_index.md, content/learn/book/getting-started/resources/_index.md, content/learn/book/getting-started/setup/_index.md
2018 will cause rendering to break badly.
=> More fixes for 0.6

generate-wasm-examples/generate_wasm_examples.sh
Since https://github.com/bevyengine/bevy/pull/3452 was merged, this is no longer an issue 🎉
=> WebGL2 examples: do not reduce window size

content/news/2022-01-08-bevy-0.6/index.md
I helped `@nside` out with the text2d work. 😄 
https://github.com/nside/bevy/pull/1
=> Credit for text2d work

content/news/2022-01-08-bevy-0.6/index.md
It really looked like a note to do something had been left in as text, so hopefully this is on the right track :)
=> Add implied missing link.

content/news/2022-01-08-bevy-0.6/index.md
=> 0.6 - add missing backtick in resolver paragraph

.github/bors.toml
Modelled after https://github.com/bevyengine/bevy/blob/main/.github/bors.toml
=> Enable bors on bevy-website repo

content/learn/book/getting-started/_index.md, content/learn/book/getting-started/setup/_index.md, generate-wasm-examples/generate_wasm_examples.sh
Just bump some version numbers
=> Update Book to 0.8

content/learn/book/getting-started/setup/_index.md
this instructions => these instructions
=> Fixed grammar

content/learn/book/introduction/_index.md
not sure if the "use godot" recommendation should be kept? 
closes: #616
=> Include new warning wording from the readme

content/learn/book/getting-started/setup/_index.md
Changed `mimimal` -> `minimal`.
=> Fixed small spelling mistake.

content/news/2023-07-07-bevy-0.11/index.md
Part of https://github.com/bevyengine/bevy-website/pull/657
=> 0.11 Section: Resource Support in Scenes

content/learn/migration-guides/0.10-0.11/_index.md, content/learn/migration-guides/0.4-0.5/_index.md, content/learn/migration-guides/0.5-0.6/_index.md, content/learn/migration-guides/0.6-0.7/_index.md, content/learn/migration-guides/0.7-0.8/_index.md, content/learn/migration-guides/0.8-0.9/_index.md, content/learn/migration-guides/0.9-0.10/_index.md, generate-release/src/markdown.rs
Generated the migration guide with the generate-release tool
=> Migration guide 0.10 -> 0.11

content/news/2023-07-09-bevy-0.11/index.md
=> fix aspect-ratio of tonemapping section images

content/news/2023-07-09-bevy-0.11/index.md
=> 0.11: gizmo creds

content/learn/book/getting-started/_index.md, content/learn/book/getting-started/ecs/_index.md, content/learn/book/getting-started/plugins/_index.md, content/learn/book/getting-started/resources/_index.md, content/learn/book/getting-started/setup/_index.md
=> Update Bevy Book for 0.11

.github/workflows/build-wasm-examples.yml
=> workflow to build examples

content/learn/migration-guides/0.10-0.11/_index.md
=> Improve note on const styles

content/news/2023-08-10-bevys-third-birthday/index.md
=> fix link to bevy-jam-2

content/news/2023-10-21-bevy-0.12/index.md
adds section for "Ignore Ambiguous Components and Resources".
=> 0.12 ignore ambiguous components and resources

content/news/2023-10-21-bevy-0.12/index.md
Added section for `AnimationPlayer` API improvements.
=> 0.12 AnimationPlayer updates section

content/news/2023-10-21-bevy-0.12/index.md
Added section describing the quality of life improvements to `Time` and `FixedUpdate`.
=> 0.12: Add section on `Time`/`FixedTime` changes

content/news/2023-10-21-bevy-0.12/index.md
add section for Pitch Audio Source for #754
=> 0.12: Pitch Audio Source

content/news/2023-09-21-community-reflection-on-bevys-third-year/index.md
Sorry, my site generator was setup to do dates wrong. Should be fixed going forwards.
=> Fix broken link

content/learn/book/getting-started/setup/_index.md
Just a quick version number bump.
=> Update book to Bevy 0.12

content/learn/book/getting-started/setup/_index.md
=> Add clang to install directions for mold

content/learn/migration-guides/0.11-0.12/_index.md
Fixes https://github.com/bevyengine/bevy/issues/10402
=> Add migration guide notes on asset hot reloading

content/news/2023-11-04-bevy-0.12/index.md
=> Fix up sentences in animation section

content/news/2023-12-11-sme-announcements/index.md, content/news/2023-12-12-sme-announcements/index.md
Time to announce some new SMEs!
=> News: SME Announcements

sass/components/_sponsors.scss, templates/index.html
Foresight bumped their support from platinum to diamond :heart: 
(I also took this as a chance to remove MeetKai, who recently cancelled their sponsorship)
=> Increase Foresight sponsorship to Diamond

content/learn/book/getting-started/ecs/_index.md
Fixes some wording from #845. #849 did the same but got closed.
=> Fix some wording in the ECS chapter

content/learn/book/contributing/_index.md
i understand if it gets denied because it's controversial
priority: EXTREME
=> Fix minor typo

content/learn/book/_index.md, content/learn/links.toml, templates/index.html
Hides the book until it is ready to be viewed by the public.
Closes #874
=> Hide the book at top-level

content/learn/book/getting-started/setup/_index.md
it said perfomance instead of performance
=> fixed typo in setup section

content/learn/book/platforms/android/_index.md, content/learn/book/platforms/ios/_index.md, content/learn/book/platforms/web/_index.md
Apparently these got put in wrong pages when book structure was made. This trivial PR fixes that.
=> Switch ios and android pages right way around

CONTRIBUTING.md, code-validation/src/lib.rs, content/learn/book/assets/_index.md, content/learn/book/audio/_index.md, content/learn/book/development-practices/_index.md, content/learn/book/ecs/entities-components/_index.md, content/learn/book/game-logic/_index.md, content/learn/book/getting-started/_index.md, content/learn/book/graphics/_index.md, content/learn/book/input/_index.md, content/learn/book/performance-optimizations/_index.md, content/learn/book/platforms/_index.md, content/learn/book/ui/_index.md, content/learn/quick-start/contributing/docs/_index.md, content/learn/quick-start/getting-started/apps/_index.md, content/learn/quick-start/getting-started/ecs/_index.md, content/learn/quick-start/getting-started/plugins/_index.md, content/learn/quick-start/getting-started/resources/_index.md, content/learn/quick-start/getting-started/setup/_index.md, content/learn/quick-start/introduction/_index.md, content/learn/quick-start/plugin-development/_index.md
Cleans up various issues noticed by author whilst going thru all the pages. Please review this with high scrutiny since this will be the penultimate review before merging into main and is overall a good place to shove any trivial concerns / issues noticed.
Most of the commit names should be self explanatory. For the few (or one at the time of writing this) that are not:
Polish CONTRIBUTING:
Adding in missing content to CONTRIBUTING.md from the contributing pages since it will be the main place for this info soon.
Minor Quick Start Grammar Improvement:
Using ellipses as `this is ... not ideal` vs `this is... ideal` didn't read fluidly. Can be reverted.
Closes #878
=> Clean up `new-book` before final merging into `main`

content/learn/book/development-practices/fast-compiles/_index.md
=> Fix a link error

content/news/2024-02-03-bevy-0.13/index.md
For #891 announcement post. I tried to split the section into a couple of smaller chunks to help with reading. This might be a bit too lengthy, so please feel free to make suggestions!
=> 0.13: Add Extensionless Asset Support Section

content/news/2024-02-03-bevy-0.13/index.md
For https://github.com/bevyengine/bevy-website/pull/891 announcement post.
=> 0.13: Add Auto Sync Points Section

content/news/2024-02-03-bevy-0.13/index.md
For https://github.com/bevyengine/bevy-website/pull/891 announcement post.
=> 0.13: transmute queries

content/news/2024-02-03-bevy-0.13/index.md
=> 0.13: Write 'Type-safe labels for `RenderGraph`' section

content/news/2024-02-03-bevy-0.13/index.md
Im not sure if I put the ui text to the right title, pls check before merge
=> Fix content in blog

content/news/2024-02-03-bevy-0.13/index.md
for #891 (technically a late heads-up though)
=> 0.13: Events Live Longer

content/news/2024-02-03-bevy-0.13/index.md
=> What's next: Bevy dev tools

content/news/2024-02-03-bevy-0.13/index.md
=> 0.13: glTF extensions

content/news/2024-02-03-bevy-0.13/index.md
=> 0.13: Lights <3 RenderLayers

content/news/2024-02-03-bevy-0.13/index.md
=> Notes on Winit upgrade

templates/macros/disallow.html
Potentially fixes #928. Related: https://github.com/bevyengine/bevy-website/pull/927#issuecomment-1933137387.
This PR updates the `disallow.html` macro to automatically strip all whitespace except for after `Disallow: ...`. The macro doesn't look... great, but the generated `robots.txt` is much better.
```
User-agent: *
Sitemap: https://bevyengine.org/sitemap.xml
Disallow: /learn/quick-start/3d-puzzle-game/
Disallow: /learn/quick-start/falling-sand/
Disallow: /learn/quick-start/breakout/
Disallow: /learn/advanced-examples/
Disallow: /learn/advanced-examples/sudoku/
Disallow: /learn/advanced-examples/text-adventure/
Disallow: /learn/book/
Disallow: /learn/book/audio/
Disallow: /learn/book/ui/
Disallow: /learn/book/game-logic/
Disallow: /learn/book/input/
Disallow: …
```
=> Remove whitespace in `robots.txt`

content/learn/migration-guides/0.12-to-0.13.md
Closes #984 
Updated guide to include changes on bevyengine/bevy/pull/11399.
=> Update "Unload render assets from RAM"

content/learn/migration-guides/0.12-to-0.13.md
A tiny one from my notes.
This one is a bit obvious, but I rewrote it like a migration guide entry. Pruning this entry could be an alternative.
=> 0.13 migration: Provide advice for 10822

content/news/2024-02-17-bevy-0.13/index.md
Gets the typos listed in #1002 
Closes #1002
=> Fix various typos

content/learn/migration-guides/0.12-to-0.13.md
Incorporates #991 and includes additional updates to address outdated information.
=> Removed outdated statements about asset_usage

content/learn/migration-guides/0.12-to-0.13.md
=> ReceivedCharacter.char

content/learn/migration-guides/0.12-to-0.13.md
This component was renamed very recently.
=> 0.13 migration: Fix name of Exposure and link to it in entry for 11347

.github/workflows/update-screenshots.yml
This is needed to update the example screenshots on the website:
- add a new page as there are more examples
- remove temp workaround not needed anymore
- fix dependencies
=> Update screenshot job

content/learn/quick-start/getting-started/apps.md
A change to satisfy a review was made right after #1021 was added to merge queue and as such was lost.
=> Follow up #1021

content/learn/migration-guides/0.12-to-0.13.md
Fixing what looks like a search/replace error.
=> 0.13 Migration: Fix duplicated version numbers

templates/index.html
=> Add old sponsor Meetkai to past sponsors list

content/learn/migration-guides/0.11-to-0.12.md
Alternative to #826. (See https://github.com/bevyengine/bevy-website/pull/826#issuecomment-1958301010)
Closes #825 
Closes #826
=> 0.12 migration: Add view transformations section

templates/docs-base.html
I messed up; forgot to put the actual if block that was needed in #962 before it got merged.  I'm sorry. This fixes that and everything should be back to normal.
Fixes #1055
=> Fix mistake in next and previous page navigation

.github/workflows/ci.yml, typos.toml
Same as https://github.com/bevyengine/bevy/pull/12036
=> Add typos - Source code spell checker

content/learn/quick-start/getting-started/plugins.md
The file pointed at by the current link does not exist.
=> Fix dead contributing.md link

templates/individual-sponsors.html, templates/sponsors.html
=> Fix sponsor image links

content/donate/faq/index.md, content/donate/foundation-sponsors.toml, content/donate/metrics.toml, sass/components/_sponsors.scss, templates/individual-sponsors.html, templates/sponsors.html
These sadly still aren't automated so here is round 2 of the metrics updates.
I also added an FAQ entry and some style tweaks.
=> Update Donation Metrics (again)

content/donate/individual-sponsors.toml
=> Re-add past sponsor

content/news/2024-02-17-bevy-0.13/index.md
=> Update link to avoid 404

content/learn/quick-start/plugin-development.md
=> Remove extra backtick from `plugin-development.md`

content/donate/individual-sponsors.toml, templates/individual-sponsors.html
Some sponsors have moved to the Bevy Foundation (Foresight and abledbody) and others have cancelled their individual sponsorships over the past month. This updates our list to account for that.
=> Update Individual Sponsors

content/contributing/_index.md, templates/layouts/base.html
A part of #1146
A simple public draft folder like the Bevy Book's folder that the rest of the Contributor's Guide content can be put into as each phase commences.
=> Phase 1 of Contributor's Guide – Foundational Folder

static/components.js
a whopping one line of code to make #1046 happy.
=> add aria-label to image compare slider

content/learn/migration-guides/0.12-to-0.13.md
There were code breaking mistakes about syntax.
=> Corrected code breaking syntax corrections 0.12-to-0.13.md

content/learn/quick-start/getting-started/setup.md
=> Update macOS linking advice

generate-release/src/migration_guides.rs, generate-release/src/release_notes.rs, sass/pages/_news.scss, templates/shortcodes/release_notes.md
=> Generate authors list for release notes

release-content/0.14/release-notes/13162_Add_a_process_for_working_groups.md, release-content/0.14/release-notes/_release-notes.toml
@Jondolf I've removed you from the list of authors here, lemme know if you wanna be added back in. The wording help was useful but probably not the correct way to assign credit :)
=> Release notes for working groups

content/news/draft-bevy-0.14/index.md
The highlights:
> - **Shiny 3D rendering features:** depth of field, god rays, meshlets, motion blur and more! Bevy's 3D rendering is quickly closing the feature gap.
> - **Better colors:** type-safe colors make it clear which color space you're operating in, and offer an awesome array of useful methods.
> - **Animation blending:** our new low-level animation graph unblocks animation blending, and sets the stage for first- and third-party graphical, asset-driven animation tools.
> - **Observers and hooks:** automatically respond to component addition and removal as we lay the foundations for fast, reliable relations between entities.
> - **Computed states and substates:** modelling complex app state is a breeze with these type-safe extensions to our `States` abstraction.
> - **Rounded …
=> Add initial intro for Bevy 0.14 release notes

release-content/0.14/release-notes/11426_Computed_State__Sub_States.md, release-content/0.14/release-notes/_release-notes.toml
This is an unusually complex feature: please complain if you can't follow the example or don't understand the point of the feature!
=> Initial release notes for computed and substates

release-content/0.14/release-notes/11426_Computed_State__Sub_States.md
Fixes https://github.com/bevyengine/bevy-website/issues/1211
=> Fix typo in release notes for computed and sub-states

release-content/0.14/migration-guides/11426_Computed_State__Sub_States.md, release-content/0.14/migration-guides/12997_multi_threaded_feature_rename.md, release-content/0.14/migration-guides/13216_Separate_state_crate.md
Just cleaning up and adding a link, some inline code blocks, etc.
There's one bit that I wasn't quite sure about -- I'll add a review comment.
=> Clean up state-related migration guides

release-content/0.14/migration-guides/11165_Decouple_BackgroundColor_from_UiImage.md, release-content/0.14/migration-guides/12234_Move_commands_module_into_bevyecsworld.md, release-content/0.14/migration-guides/12732_Move_FloatOrd_into_bevy_math.md
Jazzing these up as I come across them in my own migration efforts.
=> Add code blocks and clean up a few migrations

release-content/0.14/release-notes/11426_Computed_State__Sub_States.md
=> Fix bevy_states typo

release-content/0.14/release-notes/12100_Add_WinitEvent_aggregate_event_for_synchronized_window_eve.md, release-content/0.14/release-notes/_release-notes.toml
Fixes #1235. @ukoehb, your review would be welcome here too :)
=> Add release notes for `WinitEvent` / unified event stream

release-content/0.14/release-notes/12792_Implement_Auto_Exposure_plugin.md, release-content/0.14/release-notes/13317_12502_Remove_limit_on_RenderLayers.md, release-content/0.14/release-notes/13366_fix_upgrade_to_winit_v030.md, release-content/0.14/release-notes/13418_Implement_optin_sharp_screenspace_reflections_for_the_defe.md, release-content/0.14/release-notes/13453_add_handling_of_all_missing_gltf_extras_scene_mesh__materi.md, release-content/0.14/release-notes/13489_Normalise_matrix_naming.md, release-content/0.14/release-notes/13501_Implement_Rhombus_2D_primitive.md, release-content/0.14/release-notes/13572_Implement_motion_vectors_and_TAA_for_skinned_meshes_and_me.md, release-content/0.14/release-notes/13586_glTF_labels_add_enum_to_avoid_misspelling_and_keep_uptodat.md, release-content/0.14/release-notes/13650_Map_entities_from_a_resource_when_written_to_the_world.md, release-content/0.14/release-notes/13653_Added_CompassQuadrant_and_CompassOctant_as_per_13647.md, release-content/0.14/release-notes/_release-notes.toml, typos.toml
Several PRs were merged since the last time I ran this tool. We should generate the stubs accordingly.
Like #1285, but with a non-broken git history!
=> Add newly merged PRs to release notes

release-content/0.14/release-notes/13489_Normalise_matrix_naming.md
=> Write release notes for PR #13489: Normalise matrix naming

release-content/0.14/release-notes/10701_Cubic_splines_overhaul.md, release-content/0.14/release-notes/12747_Move_Point_out_of_cubic_splines_module_and_expand_it.md, release-content/0.14/release-notes/_release-notes.toml
Fixes #1231 
Release notes for https://github.com/bevyengine/bevy/pull/10701
=> Release notes for Cubic Splines overhaul

release-content/0.14/release-notes/13366_fix_upgrade_to_winit_v030.md
=> Release notes for PR #13366: fix: upgrade to winit v0.30

release-content/0.14/migration-guides/11986_Remove_the_UpdateAssets_and_AssetEvents_schedules.md, release-content/0.14/migration-guides/12550_Use_asyncfn_in_traits_rather_than_BoxedFuture.md, release-content/0.14/migration-guides/12605_Make_AssetActionIgnore_not_copy_assets_to_imported_assets.md, release-content/0.14/migration-guides/12655_Removed_IntoAssedIdT_for_HandleT_as_mentioned_in_12600.md, release-content/0.14/migration-guides/_guides.toml, release-content/0.14/release-notes/12547_Add_AsyncSeek_trait_to_Reader_to_be_able_to_seek_inside_as.md, release-content/0.14/release-notes/12709_Error_info_has_been_added_to_LoadStateFailed.md
=> More migration guides

release-content/0.14/migration-guides/12045_Add_access_to_App_within_LogPluginupdate_subscriber.md, release-content/0.14/migration-guides/13159_Improve_tracing_layer_customization.md, release-content/0.14/migration-guides/_guides.toml
See https://github.com/bevyengine/bevy/pull/12045#issuecomment-2155320433
=> Update migration guide for logging changes

release-content/0.14/release-notes/13270_Extrusion.md
Mention the `custom_primitives` example
=> Mention the `custom_primitives` example

release-content/0.14/migration-guides/12163_Migrate_from_LegacyColor_to_bevy_colorColor.md
Just adding these methods in with the others.
=> 0.14 migration: mention with_a for searchability

templates/sponsorship-pledge.html
I believe @alice-i-cecile is full-time these days :)
=> Tiny fix in sponsorship pledge

content/learn/book/getting-started/installation.md
also hit the format button while I was in there
=> make the "Gentoo" header a link

content/donate/faq/index.md
=> Fixed FAQ to mention auto credits updates

sass/elements/_kbd.scss, sass/site.scss
=> Added style for kbd element

release-content/0.14/migration-guides/13216_Separate_state_crate.md, release-content/0.14/migration-guides/13343_constrain_WorldQueryget_state_to_only_use_Components.md, release-content/0.14/migration-guides/13442_constrain_WorldQueryinit_state_argument_to_ComponentInitia.md, release-content/0.14/migration-guides/13594_Unify_transition_names_to_exited_and_entered.md, release-content/0.14/migration-guides/13626_Combine_transition_systems_of_Substates.md, release-content/0.14/migration-guides/_guides.toml
I had to go to [RhymeZone](https://www.rhymezone.com/r/rhyme.cgi?Word=migration&typeofrhyme=perfect&org1=syl&org2=l&org3=y) to get that title to alliterate...
Part of #1396.
=> It's migration translation Tuesday (34%)

release-content/0.14/migration-guides/13159_Improve_tracing_layer_customization.md
=> Fix 13159 punctuation

release-content/0.14/release-notes/12622_Throttle_render_assets.md
Fixes https://github.com/bevyengine/bevy-website/issues/1306
Trying my hand at writes some release notes.
=> Render throttle notes

release-content/0.14/release-notes/13586_glTF_labels_add_enum_to_avoid_misspelling_and_keep_uptodat.md
Fixes https://github.com/bevyengine/bevy-website/issues/1327
=> glTF labels

release-content/0.14/release-notes/13123_Implement_a_SystemBuilder_for_building_SystemParams.md
Fixes https://github.com/bevyengine/bevy-website/issues/1323
=> System builder release notes: we love systems

release-content/0.14/release-notes/12547_Add_AsyncSeek_trait_to_Reader_to_be_able_to_seek_inside_as.md
=> Async seek

release-content/0.14/release-notes/11906_Run_the_multithreaded_executor_at_the_end_of_each_system_t.md, release-content/0.14/release-notes/_release-notes.toml
=> 0.14 executor improvements

release-content/0.14/release-notes/13317_12502_Remove_limit_on_RenderLayers.md
Fixes https://github.com/bevyengine/bevy-website/issues/1316
Hard to get creative on this one. I opted to show a snippet for context, then explain what's new.
Let me know if a note about the possible slight perf regression should be mentioned
=> Render layers

release-content/0.14/release-notes/11989_Implement_the_AnimationGraph_allowing_for_multiple_animati.md, release-content/0.14/release-notes/_release-notes.toml
=> Add release notes for the animation graph feature

release-content/0.14/migration-guides/12012_Move_AlphaMode_into_bevy_render.md, release-content/0.14/migration-guides/12018_Add_Direction3dA_and_move_direction_types_out_of_primitive.md, release-content/0.14/migration-guides/12055_configure_surface_needs_to_be_on_the_main_thread_on_iOS.md, release-content/0.14/migration-guides/12169_Add_an_index_argument_to_parallel_iteration_helpers_in_bev.md
I'm not sure what order these are being done in.
I grabbed a couple that haven't been changed since they were generated.
=> 0.14 migration: Pretty up a few entries

release-content/0.14/release-notes/_release-notes.toml
Deeply inspired by https://github.com/bevyengine/bevy-community/pull/52.
This removes my credit as author for PRs where I made only minor changes, such as typo fixes and formatting.
=> Yeet BD103

release-content/0.14/release-notes/13417_implement_the_full_set_of_sort_methods_on_QueryIter.md
Closes #1322
~~This is an initial draft, I still want to have a read through the existing release notes, and match the language/tone if necessary.
I'll also see if there's anything I would like to expand upon/change/cut before requesting review.~~
=> add release notes for query iter sorts

content/donate/individual-sponsors.toml
Related to: https://github.com/bevyengine/bevy-website/pull/741
=> Remove Wunder Software as a sponsor

release-content/0.14/migration-guides/12189_Rename_Direction2d3d_to_Dir23.md, release-content/0.14/migration-guides/12574_Make_cardinal_splines_include_endpoints.md, release-content/0.14/migration-guides/12686_Meshing_for_Triangle3d_primitive.md, release-content/0.14/migration-guides/12747_Move_Point_out_of_cubic_splines_module_and_expand_it.md, release-content/0.14/migration-guides/12757_Update_glam_version_requirement_from_025_to_027.md, release-content/0.14/migration-guides/12796_Remove_VectorSpace_impl_on_Quat.md, release-content/0.14/migration-guides/13087_Use_Vec3A_for_3D_bounding_volumes_and_raycasts.md, release-content/0.14/migration-guides/13186_Wgpu_020.md, release-content/0.14/migration-guides/_guides.toml
This content has been brought to you by The Legend of Zelda: Breath of the Wild soundtrack. :)
Part of #1396.
=> Migration guides to study / relax / work to (49%)

release-content/0.14/release-notes/9135_Add_pipeline_statistics.md, release-content/0.14/release-notes/_release-notes.toml
Fixes https://github.com/bevyengine/bevy-website/issues/1264.
This is deeper into the rendering stack than I usually delve, and I struggled quite a bit to piece things together. While the docs are clear, they don't cover usage very effectively, and the set of tracked-by-default diagnostics is very hard to uncover.
That said, I'm pretty happy with this: it should provide the bread crumbs needed for experts to start poking at and improving this feature.
=> Write pipeline diagnostics release notes

release-content/0.14/release-notes/10756_hooks_and_observers.md
Fixes #1479.
Co-authored-by: @ChristopherBiscardi
=> Improve code example for observers

release-content/0.14/migration-guides/12218_Deprecate_SpriteSheetBundle_and_AtlasImageBundle.md
Fixes #1473. @mscottmcbee, I'd appreciate your review here.
=> Add motivation to deprecation of `SpriteSheetBundle`

release-content/0.14/migration-guides/11698_Prefer_UVec2_when_working_with_texture_dimensions.md, release-content/0.14/migration-guides/11766_Fix_CameraProjectionPlugin_not_implementing_Plugin_in_some.md, release-content/0.14/migration-guides/11904_Add_support_for_KHR_texture_transform.md, release-content/0.14/migration-guides/11939_rename_Camera3dBundles_dither_field_to_deband_dither_to_al.md, release-content/0.14/migration-guides/12012_Move_AlphaMode_into_bevy_render.md, release-content/0.14/migration-guides/12024_reflect_treat_proxy_types_correctly_when_serializing.md, release-content/0.14/migration-guides/12711_Fix_Ord_and_PartialOrd_differing_for_FloatOrd_and_optimize.md, release-content/0.14/migration-guides/12715_Fix_TypeRegistry_use_in_dynamic_scene.md, release-content/0.14/migration-guides/12721_bevy_reflect_Rename_UntypedReflectDeserializer_to_ReflectD.md, release-content/0.14/migration-guides/12732_Move_FloatOrd_into_bevy_math.md, release-content/0.14/migration-guides/12757_Update_glam_version_requirement_from_025_to_027.md, release-content/0.14/migration-guides/12986_Make_Transformrotate_axis_and_Transformrotate_local_axis_u.md, release-content/0.14/migration-guides/13182_Implement_Reflect_for_ResultT_E_as_enum.md, release-content/0.14/migration-guides/13264_Use_Dir3_for_local_axis_methods_in_GlobalTransform.md, release-content/0.14/migration-guides/13411_Common_MeshBuilder_trait.md, release-content/0.14/migration-guides/13580_Add_subdivisions_to_PlaneMeshBuilder.md, release-content/0.14/migration-guides/13605_Additional_options_to_mesh_primitives.md, release-content/0.14/migration-guides/5781_bevy_reflect_Recursive_registration.md, release-content/0.14/migration-guides/_guides.toml
Part of #1396.
I'm going to continue working today, but I'm cutting this here so it can be reviewed and merged.
=> A few more migration guides (63%)

release-content/0.14/release-notes/10164_Meshlet_rendering_initial_feature.md
A video for @jms55's feature by @mockersf. I'm just pressing the buttons here!
=> Replace meshlet video

release-content/0.14/release-notes/10756_hooks_and_observers.md
=> Correct the ordering of hooks vs observers

release-content/0.14/migration-guides/11426_on_enter_startup_states.md, release-content/0.14/migration-guides/_guides.toml
I left a review on #1512, but by that time it was already in the merge queue. This PR implements those changes.
=> Small improvements and consistency changes for 11426 migration

release-content/0.14/contributors.toml
```
cargo run -- --from v0.13.0 --to release-0.14.0 --release-version 0.14 contributors
```
Some PRs seem to be missed by the tool for some reason:
```
❯ cargo run -- --from v0.13.0 --to release-0.14.0 --release-version 0.14 contributors
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.27s
Running `/Users/chris/github/bevyengine/bevy-website/target/debug/generate-release --from v0.13.0 --to release-0.14.0 --release-version 0.14 contributors`
Getting list of all commits from v0.13.0 to release-0.14.0
Page: 1 (250 commits)
Page: 2 (250 commits)
Page: 3 (250 commits)
Page: 4 (167 commits)
Page: 5 (0 commits)
Found 917 commits
Getting list of all merged PRs from v0.13.0 to release-0.14.0 with label None
Page: 1 (59 prs)
Page: 2 (64 prs)
Page: 3 (66 prs)
Page: 4 (64 prs)
Page: 5 …
```
=> generate contributors

content/learn/quick-start/getting-started/_index.md, content/learn/quick-start/getting-started/setup.md
I didn't see any breaking changes this release. Nice!
=> Update Bevy Quickstart to 0.14

content/news/2024-07-04-bevy-0.14/index.md
=> typo: tols -> tools

release-content/0.14/release-notes/10164_Meshlet_rendering_initial_feature.md
Found a missing word when reading through the release-post
=> Fix typo in meshlet rendering release note

release-content/0.14/migration-guides/10839_Generalised_ECS_reactivity_with_Observers.md, release-content/0.14/migration-guides/13637_Move_state_installation_methods_from_bevy_app_to_bevy_stat.md, release-content/0.14/migration-guides/_guides.toml
Fixes #1528 and #1526. Thanks @UkoeHB for pointing them out!
=> A few small migration guide fixes

content/learn/quick-start/getting-started/setup.md
Fixes https://github.com/bevyengine/bevy-website/issues/1537.
See also: https://github.com/bevyengine/bevy/pull/14173.
=> Explain how to optimize release builds

content/learn/quick-start/getting-started/setup.md
Also threw in a small wording simplification.
=> Fix header level of "Advanced Wasm optimizations"

release-content/0.14/release-notes/11426_Computed_States__Sub_States.md
Function is named `add_sub_state`
=> Fix typo in release notes

release-content/0.14/release-notes/13162_Add_a_process_for_working_groups.md
=> Fix link in working group section of 0.14 news post

content/learn/quick-start/getting-started/setup.md
Data thanks to @rparrett:
https://github.com/rparrett/bevy_wasm_bench/blob/main/results/d98b3a8_win11_i713700KF_4080super.csv
=> Update optimization suggestions based on benchmark

release-content/0.14/migration-guides/12426_separating_finite_and_infinite_3d_planes.md, release-content/0.14/migration-guides/_guides.toml
=> 0.14 migration: Add section for `Plane3d` changes

content/learn/quick-start/getting-started/setup.md, sass/elements/_details.scss
Fixes #1563 
This PR encapsulates a lot of non-essential sections of the Getting Started Setup page in `<details>` to make it easier to read.
=> Declutter Quick Start Getting Started Setup Page

generate-assets/src/lib.rs
Context: https://github.com/bevyengine/bevy-assets/issues/458.
=> Support `crate` field for Bevy Assets

content/contributing/project-information/_index.md, content/contributing/project-information/bevy-organization.md, content/contributing/project-information/release-process.md, content/contributing/project-information/working-groups.md, content/contributing/reference/_index.md, typos.toml
Part of #1146.
When taken together with #1595, all remaining content from https://hackmd.io/qWCaVBIuR6aF692yZNPvTA will be included on the website, and we can move on to final polish before undrafting this :)
=> Add chapter on the Bevy Organization to the Contributing Guide

.github/workflows/update-screenshots.yml
with recent change on the Bevy org, this job now fails, see https://github.com/bevyengine/bevy-website/actions/runs/10742349389/job/29798612601
add the required permissions to create PR
=> request pr write permissions in the screenshot update job

CONTRIBUTING.md, templates/foundation.html
When I was reading through the website, I found a broken link in the maintainers section. I thought to fix it, and when I went to `CONTRIBUTING.md` to double check what to do, they were also broken!
=> Fix Broken Links

templates/foundation.html
=> Update Bevy Foundation page to reflect 501(c)(3) status

content/learn/contribute/helping-out/creating-examples.md
Opening this for discussion. I'd like to have something to point to when making suggestions or changes like these.
=> Add visual guidelines for examples

release-content/0.15/release-notes/13669_Expose_winits_MonitorHandle.md
=> `Monitor` release notes

release-content/0.15/release-notes/14833_Rewrite_screenshots.md
=> Screenshots release notes

release-content/0.15/release-notes/14284_Add_custom_cursors.md
Fixes #1670
I have a video too but not sure where to put it. 
https://github.com/user-attachments/assets/90dd5ca1-c423-4a83-a303-042423524db5
=> Add custom cursor release notes

release-content/0.15/release-notes/15435_List_components_for_QueryEntityErrorQueryDoesNotMatch.md
=> Release notes for List components for QueryEntityError::QueryDoesNotMatch

release-content/0.15/release-notes/13912_featgltf_add_name_component_to_gltf_mesh_primitive.md
=> Release Note for add name component to gltf mesh primitive #13912

release-content/0.15/release-notes/14817_SystemParamBuilder__Support_dynamic_system_parameters.md, release-content/0.15/release-notes/15189_System_param_for_dynamic_resources.md, release-content/0.15/release-notes/_release-notes.toml
Release note for the various `SystemParamBuilder` PRs.  
Fixes #1679
Fixes #1713
=> Release note for SystemParamBuilder.

release-content/0.15/release-notes/14212_Component_Lifecycle_Hook__Observer_Trigger_for_replaced_va.md
=> Release notes for on_replace component lifecycle hook

release-content/0.15/release-notes/15627_Add_more_tools_for_traversing_hierarchies.md, release-content/0.15/release-notes/_release-notes.toml
=> HierarchyQueryExt release notes

release-content/0.15/release-notes/15056_Add_module_and_supporting_documentation_to_bevy_assets.md, release-content/0.15/release-notes/_release-notes.toml
Closes #1686. I don't think that this is interesting to read about.
=> Remove bevy_assets docs release note

release-content/0.15/release-notes/15207_Add_EntityRefExcept_and_EntityMutExcept_world_queries_in_p.md, release-content/0.15/release-notes/_release-notes.toml
=> Release notes for EntityRefExcept and EntityMutExcept

release-content/0.15/release-notes/15276_Reduce_runtime_panics_through_SystemParam_validation.md
=> Add links to new fallible params

release-content/0.15/release-notes/15184_Support_systems_that_take_references_as_input.md, release-content/0.15/release-notes/_release-notes.toml
Fixes #1695. The example was adapted from the one given in https://github.com/bevyengine/bevy/pull/15184 by @ItsDoot  :)
=> Release notes for reference in system input

release-content/0.15/release-notes/14034_Track_source_location_in_change_detection.md
Fixes #1666. Release notes for https://github.com/bevyengine/bevy/pull/14034 by @aevyrie <3
=> Release notes for track source location in change detection

release-content/0.15/release-notes/14049_Opportunistically_use_dense_iteration_for__archetypal_iter.md, release-content/0.15/release-notes/14673_Opportunistically_use_dense_iter_for_archetypal_iteration_.md, release-content/0.15/release-notes/_release-notes.toml
Fixes #1667 and #1682. @re1032, thanks for this work, and do point out any mistakes I've made while writing this up!
=> Release notes for dense iteration with sparse filters

release-content/0.15/release-notes/15291_UI_Scrolling.md, release-content/0.15/release-notes/_release-notes.toml
Luckily there's not too much API surface to discuss here. My first release note, so let me know what I need to change!
=> Add 0.15 release notes for UI scrolling

release-content/0.15/release-notes/15631_Implement_additive_blending_for_animation_graphs.md
Unfortunately, I think the main thing that would improve this would be something like a video of additive blending in action, but:
1. the animated fox example model isn't particularly good for demonstrating additive animations;
2. none of our examples use additive animation blending as far as I know.
=> Release notes for additive blending

release-content/0.15/release-notes/12770_Implement_gamepads_as_entities.md, release-content/0.15/release-notes/_release-notes.toml
Fixes #1772 following the much-appreciated cleanup tweaks to this API by @Shatur.
=> Incorporate changes to gamepads-as-entities

release-content/0.15/release-notes/14630_A_Curve_trait_for_general_interoperation__Part_I.md
Closes #1669
I'm probably missing something obvious here, but I reached the point where I figured it would be better to request review than to agonize over it. Most of the internal applications will appear in separate release notes, I imagine.
=> 0.15 Release Notes: Curve API

release-content/0.15/release-notes/14630_A_Curve_trait_for_general_interoperation__Part_I.md, release-content/0.15/release-notes/15282_Allow_animation_clips_to_animate_arbitrary_properties.md, release-content/0.15/release-notes/15675_Add_most_common_interpolations.md
=> 0.15 Release Notes: Replace instances of removed curve constructors

release-content/0.15/release-notes/14071_Uniform_mesh_sampling.md
Closes #1654 
A picture might be nice if we find the time to generate one.
=> 0.15 Release Notes: Uniform mesh sampling

release-content/0.15/release-notes/13497_Implement_percentagecloser_soft_shadows_PCSS.md, release-content/0.15/release-notes/_release-notes.toml
=> Remove PCSS release notes section

release-content/0.15/migration-guides/15320_Retained_Rendering.md, release-content/0.15/migration-guides/_guides.toml, release-content/0.15/release-notes/15320_Retained_Rendering.md, release-content/0.15/release-notes/_release-notes.toml
This truly is a terrible first draft, but I had fun writing it and I will probably improve it in the future.
=> 0.15 Release Notes: Retained Rendering

release-content/0.15/release-notes/14920_Add_cached_run_system_API.md
=> 0.15 Release Notes: Cached One-shot Systems

release-content/0.15/release-notes/15170_Enabledisable_UI_antialiasing.md, release-content/0.15/release-notes/15368_Add_the_ability_to_control_font_smoothing.md, release-content/0.15/release-notes/_release-notes.toml
While valuable, these fall into the "pretty modest bug fix category" IMO.
Closes #1671 and closes #1684.
=> Remove UI AA PRs from release notes

release-content/0.15/release-notes/14257_Pack_multiple_vertex_and_index_arrays_together_into_growab.md, release-content/0.15/release-notes/_release-notes.toml
Fixes #1662 
I didnt know if i should include the pictures of tracy, seems a bit noisy, but idk how graphs are usually made for bevy website
=> 14257 Pack multiple vertex and index buffers Release Notes

content/news/2024-XX-XX-bevy-0.15/index.md, release-content/0.15/release-notes/_release-notes.toml
This (begins) reordering sections based on interest, renaming sections for clarity, and adds some initial highlights.
This is not the final ordering or naming.
=> 0.15 Editorial Pass: Reorder and rename sections, initial highlights

release-content/0.15/migration-guides/15196_Rename_push_children_to_add_children.md
For convenience: bevyengine/bevy#15196
- Remove PR description placeholder text
- Mention a few more pub things that changed in that PR
- Format in table
=> 0.15 migration: Touch up entry for PR 15196

release-content/0.15/migration-guides/14862_Picking_event_ordering.md
I lost a few hours figuring this out until I went to the examples.
=> Update to mention additional plugin required

sass/components/_footer.scss
Increases the footer gap from 10px to 25px.
Fixes #1862
=> Increase footer gap

sass/pages/_foundation.scss, templates/foundation.html
=> Fix foundation info spacing

content/learn/migration-guides/0.14-to-0.15.md
=> 0.15 migration: Un-hide guide

content/learn/contribute/reference/triage.md
=> Add S-Nominated-To-Close to triage docs

release-content/0.16/release-notes/16388_Add_optional_transparency_passthrough_for_sprite_backend_w.md
This are very minor edits that I think make the sentences flow a little better. The majority of these notes were great!
=> Address some nits with the flow of the sentences for #16388 release notes.

release-content/0.16/release-notes/17216_Stop_automatically_generating_meta_files_for_assets_while_.md
Fixes #2000.
Link to the original PR: https://github.com/bevyengine/bevy/pull/17216
=> Add release notes for #17216.

release-content/0.16/release-notes/16132_Entity_cloning.md
=> Release notes for #16132

release-content/0.16/release-notes/16810_Add_AssetChanged_query_filter.md, release-content/0.16/release-notes/_release-notes.toml
=> Asset changed release notes

release-content/0.16/release-notes/16372_Add_Immutable_Component_Support.md, release-content/0.16/release-notes/_release-notes.toml
Fixes #1964.
I'm feeling happy about this, but man our example for immutable components feels inadequate: it doesn't teach the observers / hooks pattern at all.
=> Immutable components release notes

release-content/0.16/release-notes/17953_Add_support_for_experimental_WESL_shader_source.md
Fix misspelling from #2027. Thanks @BenjaminBrienen !
=> Fix WESL release note misspelling

release-content/0.16/release-notes/15473_Retained_Gizmos.md
=> Add release notes for Retained Gizmos.

release-content/0.16/release-notes/15074_bevy_reflect_Function_Overloading_Generic__Variadic_Functi.md
=> Add release note for function overloading

release-content/0.16/migration-guides/16331_Rename_PointerDownUp__PointerPressedReleased_in_bevy_picki.md, release-content/0.16/migration-guides/16567_Rename_ArgListpush_methods_to_with_and_add_new_push_method.md, release-content/0.16/migration-guides/17029_Refactor_hierarchyrelated_commands_to_remove_structs.md, release-content/0.16/migration-guides/17233_If_there_is_no_movement_DragStart_is_not_triggered.md, release-content/0.16/migration-guides/17702_Use_target_abi__sim_instead_of_ios_simulator_feature.md, release-content/0.16/migration-guides/_guides.toml, release-content/0.16/migration-guides/bevy_core_removed.md
Fixes some issues with the 0.16 migration guide.
=> Bevy 0.16 migration guide fixes

release-content/0.16/migration-guides/bevy_utils_decimation.md
=> Improve clarity of tracing log macros migration

content/learn/migration-guides/0.15-to-0.16.md, release-content/0.16/migration-guides/16589_Fallible_systems.md, release-content/0.16/migration-guides/18082_Make_Querysingle_and_friends_return_a_Result.md, release-content/0.16/migration-guides/_guides.toml
=> Clean up unified error handling migration guides and mention anyhow

release-content/0.16/release-notes/17559_Basic_UI_text_shadows.md, release-content/0.16/release-notes/_release-notes.toml
Fixes #1991.
We still need a proper image for this (the ones in the PR aren't shiny enough), but this is good to merge without it IMO.
=> Text shadow release notes

release-content/0.16/release-notes/16503_Derivative_access_patterns_for_curves.md, release-content/0.16/release-notes/_release-notes.toml
Fixes #1970.
I initially attempted to describe the collection of traits and their relationship, but:
1. This was extremely complex, and high on both math and type system esoterica.
2. It isn't super useful for the average reader, who mostly wants to go "huh neat"
3. The PR description is already excellent.
4. A comprehensive guide to the relation between this web of traits and types belongs in the module docs, not release notes.
As a result, this is pretty fluffy, focusing on motivation, limitations and usage.
=> Write release notes for the curve derivative work

release-content/0.16/migration-guides/16163_Dont_reëxport_bevy_image_from_bevy_render.md, release-content/0.16/migration-guides/16693_Draw_the_UI_debug_overlay_using_the_UI_renderer.md, release-content/0.16/migration-guides/16694_Cache_systems_by_S_instead_of_SSystem.md, release-content/0.16/migration-guides/16725_BRP_strict_field_in_query.md, release-content/0.16/migration-guides/16778_Event_source_location_tracking.md, release-content/0.16/migration-guides/16863_Replace_bevy_a11yFocus_with_InputFocus.md, release-content/0.16/migration-guides/17051_Convert_to_fallible_system_in_IntoSystemConfigs.md, release-content/0.16/migration-guides/17075_Rename_track_change_detection_flag_to_track_location.md, release-content/0.16/migration-guides/17259_Allow_users_to_customize_history_length_in_FrameTimeDiagno.md, release-content/0.16/migration-guides/17376_Change_Worldtry_despawn_and_Worldtry_insert_batch_to_return.md, release-content/0.16/migration-guides/17499_Support_for_nonbrowser_wasm.md, release-content/0.16/migration-guides/17855_Add_EntityDoesNotExistError_replace_cases_of_Entity_as_an_.md, release-content/0.16/migration-guides/17955_Add_no_std_support_to_bevy.md, release-content/0.16/migration-guides/17967_Upgrade_to_Rust_Edition_2024.md, release-content/0.16/migration-guides/18555_Improved_require_syntax.md, release-content/0.16/migration-guides/_guides.toml
Same as last time (#2053), except now this includes 14 migration guides instead of 11 :)
=> Migration writing pass 2

release-content/0.16/release-notes/17096_Anamorphic_Bloom.md
~~No image for now, but I can bang out the release text for this easily enough.~~
Image added!
=> Write release notes for anamorphic bloom

release-content/0.16/migration-guides/17398_Relationships_nonfragmenting_onetomany.md
=> Extend migration guide for HierarchyQueryExt

release-content/0.16/release-notes/_release-notes.toml, release-content/0.16/release-notes/gpu_tracing.md
=> Release notes for GPU tracing

release-content/0.16/migration-guides/18083_Improved_DeriveEvent.md, release-content/0.16/migration-guides/_guides.toml
=> migration guide for Derive(Event)

release-content/0.16/release-notes/17758_Trait_tags_on_docsrs.md
highlight the next steps for doc tags
=> 0.16: next steps for doc tags

release-content/0.16/migration-guides/15624_Support_using_FilteredResources_with_ReflectResource.md, release-content/0.16/migration-guides/16499_Run_observers_before_hooks_for_on_replace_and_on_remove.md, release-content/0.16/migration-guides/16642_Turn_apply_deferred_into_a_ZST_System.md, release-content/0.16/migration-guides/17447_Support_nonVec_data_structures_in_relations.md, release-content/0.16/migration-guides/17685_Split_Componentregister_component_hooks_into_individual_me.md, release-content/0.16/migration-guides/17694_Shorten_the_world_lifetime_returned_from_QueryLensquery.md, release-content/0.16/migration-guides/17977_Renamed_EventWritersend_methods_to_write.md, release-content/0.16/migration-guides/18028_Use_register_dynamic_for_merging.md, release-content/0.16/migration-guides/18432_Replace_VisitEntities_with_MapEntities.md, release-content/0.16/migration-guides/_guides.toml
This is the last one for now :)
=> Migration writing pass 5

release-content/0.16/migration-guides/17752_Add_ways_to_configure_EasingFunctionSteps_via_new_StepConf.md
=> EasyFunction -> EaseFunction

content/learn/migration-guides/0.15-to-0.16.md, release-content/0.16/migration-guides/bevy_utils_decimation.md, release-content/0.16/release-notes/17955_Add_no_std_support_to_bevy.md
Adapt to https://github.com/bevyengine/bevy/pull/18813
=> bevy_platform_support -> bevy_platform

release-content/0.16/release-notes/gpu_driven_rendering.md
Here are the draft release notes for GPU-driven rendering.
=> Add release notes for GPU-driven rendering

release-content/0.16/release-notes/16314_Procedural_atmospheric_scattering.md, release-content/0.16/release-notes/_release-notes.toml
fixed a typo in the notes, and added recognition for @mate-h's hard work in this area :)
=> Atmosphere notes fix

content/learn/contribute/project-information/working-groups.md
Proposing minor change of `Expertss` to `Expert` inside `working-groups.md`.
First-timer here. Sorry if such writing is intended 🙏
=> Fix possible minor typo on `working-groups.md`

release-content/0.16/release-notes/13120_Add_DefaultQueryFilters.md, release-content/0.16/release-notes/decals.md, release-content/0.16/release-notes/unified_error_handling.md
Hi! Here are some edits/fixes for the release notes.
=> Bevy 0.16 release note edits

release-content/0.16/release-notes/17521_Improved_Spawn_APIs_and_Bundle_Effects.md
=> Add missing close paren in SpawnIter code example

generate-assets/src/lib.rs
It turns out the asset generation is extremely CPU bound in rustqlite queries, which can be avoided by adding some database indices. On my machine this takes every query from 5 seconds to 50ms in release mode.
=> Speed up generate-assets with database indices

content/learn/quick-start/getting-started/setup.md
It seems like this sentence should be inside the details section above it.
=> Move sentence into details section

content/learn/quick-start/getting-started/resources.md
=> fix broken links in quickstart

generate-assets/src/bin/validate.rs, generate-assets/src/lib.rs, generate-community/src/bin/generate.rs, generate-community/src/bin/validate.rs, generate-release/src/changelog.rs, generate-release/src/github_client.rs, generate-release/src/markdown.rs, generate-release/src/migration_guides.rs, generate-release/src/release_notes.rs, write-rustdoc-hide-lines/src/code_block_definition.rs, write-rustdoc-hide-lines/src/formatter.rs, write-rustdoc-hide-lines/src/main.rs
Aims to fix CI failures in #2153.
=> cargo clippy --fix for new Rust version

content/learn/book/intro/what-is-bevy.md
Steal and tweak the note from @viridia from #2161, to clearly highlight some of the best applications for Bevy today.
=> Bevy beyond games note

content/learn/book/modular-architecture/plugins.md
Tackles some of the criticism in #2161.
There are some serious limitations and footguns in our plugin architecture, but I figured we should actually teach new users that they exist / how to work around them, rather than letting them stumble over them on their own.
If it's embarrassing enough, maybe it will motivate us to actually fix them ;)
=> Write the book page for plugins

content/learn/book/storing-data/entities-components.md
=> Update link in Book to Exclusive Systems

sass/fonts/_firasans.scss
=> Remove `local` Fira Sans source to avoid Chromium bug

.github/workflows/ci.yml
=> Update ci.yml to install required rust toolchain components

content/news/2025-09-24-bevy-0.17/index.md
I've tackled most of the changes noted in #2238 in this PR, leaving only a few changes that I either was mixed on or did not have the expertise to implement myself.
These were left as post-merging comments in #2233: I've resolved the conversations for all of the comments addressed in the PR to make work-tracking feasible.
This PR is deliberately composed of many very small commits: I'm happy to revert or revise any of these changes.
=> Apply suggestions for release notes from JMS55

content/learn/contribute/project-information/release-process.md
- removed publish script
- improve some commands
=> Update release process
